// Decompiled with JetBrains decompiler
// Type: MGASystems.IMS.Accounting.GeneralLedger.Forms.formAccountLinking
// Assembly: MgaSystems.IMS.Accounting.GeneralLedger, Version=2.0.0.0, Culture=neutral, PublicKeyToken=e175cb7c4ce15bbd
// MVID: DC511D5D-5AA9-4B52-8578-E2A0BCB046C3
// Assembly location: D:\augusta\fortegra\IMS Project\MgaSystems.IMS.Claims\lib\MgaSystems.IMS.Accounting.GeneralLedger.dll

using Infragistics.Win;
using Infragistics.Win.Misc;
using Infragistics.Win.UltraWinEditors;
using Infragistics.Win.UltraWinGrid;
using MGASystems.Tools;
using System;
using System.ComponentModel;
using System.Drawing;
using System.Resources;
using System.Windows.Forms;

#nullable disable
namespace MGASystems.IMS.Accounting.GeneralLedger.Forms;

public class formAccountLinking : Form
{
  private MGATextBox textEntityName;
  private Label label1;
  private MGAButton buttonSearchEntity;
  private Label label2;
  private MGASimpleComboBox comboOfficeLocation;
  private Label label3;
  private Label label4;
  private Label label5;
  private Label label6;
  private Label label7;
  private Label label8;
  private Label label9;
  private Label label10;
  private Label label11;
  private Label label12;
  private Label label13;
  private Label label14;
  private MGAButton buttonCancel;
  private Panel panel1;
  private LinkLabel linkChangeAR;
  private LinkLabel linkChangeAP;
  private LinkLabel linkChangeUnAccounted;
  private LinkLabel linkChangeExchange;
  private MGAButton buttonSave;
  private MGAButton buttonAddEditPayment;
  private System.ComponentModel.Container components;

  public formAccountLinking() => this.InitializeComponent();

  protected override void Dispose(bool disposing)
  {
    if (disposing && this.components != null)
      this.components.Dispose();
    base.Dispose(disposing);
  }

  private void InitializeComponent()
  {
    Appearance appearance1 = new Appearance();
    Appearance appearance2 = new Appearance();
    ResourceManager resourceManager = new ResourceManager(typeof (formAccountLinking));
    Appearance appearance3 = new Appearance();
    Appearance appearance4 = new Appearance();
    Appearance appearance5 = new Appearance();
    this.textEntityName = new MGATextBox();
    this.label1 = new Label();
    this.buttonSearchEntity = new MGAButton();
    this.label2 = new Label();
    this.comboOfficeLocation = new MGASimpleComboBox();
    this.label3 = new Label();
    this.label4 = new Label();
    this.label5 = new Label();
    this.label6 = new Label();
    this.label7 = new Label();
    this.label8 = new Label();
    this.label9 = new Label();
    this.label10 = new Label();
    this.label11 = new Label();
    this.label12 = new Label();
    this.label13 = new Label();
    this.label14 = new Label();
    this.linkChangeAR = new LinkLabel();
    this.linkChangeAP = new LinkLabel();
    this.linkChangeUnAccounted = new LinkLabel();
    this.linkChangeExchange = new LinkLabel();
    this.buttonCancel = new MGAButton();
    this.buttonSave = new MGAButton();
    this.panel1 = new Panel();
    this.buttonAddEditPayment = new MGAButton();
    ((ISupportInitialize) this.textEntityName).BeginInit();
    ((ISupportInitialize) this.buttonSearchEntity).BeginInit();
    ((ISupportInitialize) this.comboOfficeLocation).BeginInit();
    ((ISupportInitialize) this.buttonCancel).BeginInit();
    ((ISupportInitialize) this.buttonSave).BeginInit();
    this.panel1.SuspendLayout();
    ((ISupportInitialize) this.buttonAddEditPayment).BeginInit();
    this.SuspendLayout();
    ((AppearanceBase) appearance1).BackColor = Color.White;
    ((AppearanceBase) appearance1).BorderColor = Color.FromArgb((int) sbyte.MaxValue, 157, 185);
    ((AppearanceBase) appearance1).ForeColor = Color.Black;
    ((TextEditorControlBase) this.textEntityName).Appearance = (AppearanceBase) appearance1;
    ((Control) this.textEntityName).Location = new Point(16 /*0x10*/, 24);
    this.textEntityName.MGAStyle = MGAStyles.Blue;
    ((Control) this.textEntityName).Name = "textEntityName";
    ((Control) this.textEntityName).Size = new Size(344, 20);
    ((Control) this.textEntityName).TabIndex = 0;
    this.label1.AutoSize = true;
    this.label1.Location = new Point(16 /*0x10*/, 8);
    this.label1.Name = "label1";
    this.label1.Size = new Size(67, 16 /*0x10*/);
    this.label1.TabIndex = 1;
    this.label1.Text = "Entity Name:";
    ((AppearanceBase) appearance2).BackColor = Color.FromArgb(248, 248, 248);
    ((AppearanceBase) appearance2).BackColor2 = Color.FromArgb(250, 250, 250);
    ((AppearanceBase) appearance2).BackGradientStyle = (GradientStyle) 2;
    ((AppearanceBase) appearance2).BorderColor = Color.DarkGray;
    ((AppearanceBase) appearance2).Image = resourceManager.GetObject("appearance2.Image");
    ((AppearanceBase) appearance2).ImageHAlign = (HAlign) 2;
    ((AppearanceBase) appearance2).ImageVAlign = (VAlign) 2;
    ((ControlBase) this.buttonSearchEntity).Appearance = (AppearanceBase) appearance2;
    ((Control) this.buttonSearchEntity).Location = new Point(360, 24);
    ((Control) this.buttonSearchEntity).Name = "buttonSearchEntity";
    ((Control) this.buttonSearchEntity).Size = new Size(20, 20);
    ((Control) this.buttonSearchEntity).TabIndex = 2;
    this.label2.AutoSize = true;
    this.label2.Location = new Point(16 /*0x10*/, 56);
    this.label2.Name = "label2";
    this.label2.Size = new Size(84, 16 /*0x10*/);
    this.label2.TabIndex = 4;
    this.label2.Text = "GL Company ID:";
    this.comboOfficeLocation.BorderStyle = (UIElementBorderStyle) 4;
    this.comboOfficeLocation.CharacterCasing = CharacterCasing.Normal;
    ((UltraDropDownBase) this.comboOfficeLocation).DisplayMember = "";
    this.comboOfficeLocation.DropDownStyle = (UltraComboStyle) 1;
    ((Control) this.comboOfficeLocation).Location = new Point(16 /*0x10*/, 72);
    this.comboOfficeLocation.MGAStyle = MGAStyles.Blue;
    ((Control) this.comboOfficeLocation).Name = "comboOfficeLocation";
    ((Control) this.comboOfficeLocation).Size = new Size(360, 20);
    ((Control) this.comboOfficeLocation).TabIndex = 5;
    ((UltraDropDownBase) this.comboOfficeLocation).ValueMember = "";
    this.label3.AutoSize = true;
    this.label3.Font = new Font("Tahoma", 8f, FontStyle.Bold);
    this.label3.Location = new Point(16 /*0x10*/, 120);
    this.label3.Name = "label3";
    this.label3.Size = new Size(121, 16 /*0x10*/);
    this.label3.TabIndex = 7;
    this.label3.Text = "Accounts Receivable:";
    this.label4.AutoSize = true;
    this.label4.Font = new Font("Tahoma", 8f, FontStyle.Bold);
    this.label4.Location = new Point(16 /*0x10*/, 264);
    this.label4.Name = "label4";
    this.label4.Size = new Size(109, 16 /*0x10*/);
    this.label4.TabIndex = 8;
    this.label4.Text = "Exchange Account:";
    this.label5.AutoSize = true;
    this.label5.Font = new Font("Tahoma", 8f, FontStyle.Bold);
    this.label5.Location = new Point(16 /*0x10*/, 216);
    this.label5.Name = "label5";
    this.label5.Size = new Size(204, 16 /*0x10*/);
    this.label5.TabIndex = 9;
    this.label5.Text = "Un-Accounted/ Surplus Remittance:";
    this.label6.AutoSize = true;
    this.label6.Font = new Font("Tahoma", 8f, FontStyle.Bold);
    this.label6.Location = new Point(16 /*0x10*/, 168);
    this.label6.Name = "label6";
    this.label6.Size = new Size(105, 16 /*0x10*/);
    this.label6.TabIndex = 10;
    this.label6.Text = "Accounts Payable:";
    this.label7.AutoSize = true;
    this.label7.ForeColor = Color.DimGray;
    this.label7.Location = new Point(16 /*0x10*/, 136);
    this.label7.Name = "label7";
    this.label7.Size = new Size(63 /*0x3F*/, 16 /*0x10*/);
    this.label7.TabIndex = 11;
    this.label7.Text = "[GLACCTID]";
    this.label8.ForeColor = Color.DimGray;
    this.label8.Location = new Point(96 /*0x60*/, 136);
    this.label8.Name = "label8";
    this.label8.Size = new Size(232, 16 /*0x10*/);
    this.label8.TabIndex = 12;
    this.label8.Text = "[ACCOUNT FULLNAME]";
    this.label9.ForeColor = Color.DimGray;
    this.label9.Location = new Point(96 /*0x60*/, 184);
    this.label9.Name = "label9";
    this.label9.Size = new Size(232, 16 /*0x10*/);
    this.label9.TabIndex = 14;
    this.label9.Text = "[ACCOUNT FULLNAME]";
    this.label10.AutoSize = true;
    this.label10.ForeColor = Color.DimGray;
    this.label10.Location = new Point(16 /*0x10*/, 184);
    this.label10.Name = "label10";
    this.label10.Size = new Size(63 /*0x3F*/, 16 /*0x10*/);
    this.label10.TabIndex = 13;
    this.label10.Text = "[GLACCTID]";
    this.label10.Click += new EventHandler(this.label10_Click);
    this.label11.ForeColor = Color.DimGray;
    this.label11.Location = new Point(96 /*0x60*/, 232);
    this.label11.Name = "label11";
    this.label11.Size = new Size(232, 16 /*0x10*/);
    this.label11.TabIndex = 16 /*0x10*/;
    this.label11.Text = "[ACCOUNT FULLNAME]";
    this.label12.AutoSize = true;
    this.label12.ForeColor = Color.DimGray;
    this.label12.Location = new Point(16 /*0x10*/, 232);
    this.label12.Name = "label12";
    this.label12.Size = new Size(63 /*0x3F*/, 16 /*0x10*/);
    this.label12.TabIndex = 15;
    this.label12.Text = "[GLACCTID]";
    this.label13.ForeColor = Color.DimGray;
    this.label13.Location = new Point(96 /*0x60*/, 280);
    this.label13.Name = "label13";
    this.label13.Size = new Size(232, 16 /*0x10*/);
    this.label13.TabIndex = 18;
    this.label13.Text = "[ACCOUNT FULLNAME]";
    this.label14.AutoSize = true;
    this.label14.ForeColor = Color.DimGray;
    this.label14.Location = new Point(16 /*0x10*/, 280);
    this.label14.Name = "label14";
    this.label14.Size = new Size(63 /*0x3F*/, 16 /*0x10*/);
    this.label14.TabIndex = 17;
    this.label14.Text = "[GLACCTID]";
    this.linkChangeAR.AutoSize = true;
    this.linkChangeAR.Location = new Point(336, 120);
    this.linkChangeAR.Name = "linkChangeAR";
    this.linkChangeAR.Size = new Size(41, 16 /*0x10*/);
    this.linkChangeAR.TabIndex = 19;
    this.linkChangeAR.TabStop = true;
    this.linkChangeAR.Text = "Change";
    this.linkChangeAR.TextAlign = ContentAlignment.TopRight;
    this.linkChangeAP.AutoSize = true;
    this.linkChangeAP.Location = new Point(336, 168);
    this.linkChangeAP.Name = "linkChangeAP";
    this.linkChangeAP.Size = new Size(41, 16 /*0x10*/);
    this.linkChangeAP.TabIndex = 20;
    this.linkChangeAP.TabStop = true;
    this.linkChangeAP.Text = "Change";
    this.linkChangeAP.TextAlign = ContentAlignment.TopRight;
    this.linkChangeUnAccounted.AutoSize = true;
    this.linkChangeUnAccounted.Location = new Point(336, 216);
    this.linkChangeUnAccounted.Name = "linkChangeUnAccounted";
    this.linkChangeUnAccounted.Size = new Size(41, 16 /*0x10*/);
    this.linkChangeUnAccounted.TabIndex = 21;
    this.linkChangeUnAccounted.TabStop = true;
    this.linkChangeUnAccounted.Text = "Change";
    this.linkChangeUnAccounted.TextAlign = ContentAlignment.TopRight;
    this.linkChangeExchange.AutoSize = true;
    this.linkChangeExchange.Location = new Point(336, 264);
    this.linkChangeExchange.Name = "linkChangeExchange";
    this.linkChangeExchange.Size = new Size(41, 16 /*0x10*/);
    this.linkChangeExchange.TabIndex = 22;
    this.linkChangeExchange.TabStop = true;
    this.linkChangeExchange.Text = "Change";
    this.linkChangeExchange.TextAlign = ContentAlignment.TopRight;
    ((AppearanceBase) appearance3).BackColor = Color.FromArgb(248, 248, 248);
    ((AppearanceBase) appearance3).BackColor2 = Color.FromArgb(250, 250, 250);
    ((AppearanceBase) appearance3).BackGradientStyle = (GradientStyle) 2;
    ((AppearanceBase) appearance3).BorderColor = Color.DarkGray;
    ((AppearanceBase) appearance3).ImageHAlign = (HAlign) 2;
    ((AppearanceBase) appearance3).ImageVAlign = (VAlign) 2;
    ((ControlBase) this.buttonCancel).Appearance = (AppearanceBase) appearance3;
    ((UltraButtonBase) this.buttonCancel).DialogResult = DialogResult.Cancel;
    ((Control) this.buttonCancel).Location = new Point(280, 8);
    ((Control) this.buttonCancel).Name = "buttonCancel";
    ((Control) this.buttonCancel).Size = new Size(96 /*0x60*/, 24);
    ((Control) this.buttonCancel).TabIndex = 23;
    ((Control) this.buttonCancel).Text = "Cancel";
    ((Control) this.buttonCancel).Click += new EventHandler(this.buttonCancel_Click);
    ((AppearanceBase) appearance4).BackColor = Color.FromArgb(248, 248, 248);
    ((AppearanceBase) appearance4).BackColor2 = Color.FromArgb(250, 250, 250);
    ((AppearanceBase) appearance4).BackGradientStyle = (GradientStyle) 2;
    ((AppearanceBase) appearance4).BorderColor = Color.DarkGray;
    ((AppearanceBase) appearance4).ImageHAlign = (HAlign) 2;
    ((AppearanceBase) appearance4).ImageVAlign = (VAlign) 2;
    ((ControlBase) this.buttonSave).Appearance = (AppearanceBase) appearance4;
    ((Control) this.buttonSave).Location = new Point(176 /*0xB0*/, 8);
    ((Control) this.buttonSave).Name = "buttonSave";
    ((Control) this.buttonSave).Size = new Size(96 /*0x60*/, 24);
    ((Control) this.buttonSave).TabIndex = 24;
    ((Control) this.buttonSave).Text = "Save Changes";
    this.panel1.BackColor = Color.FromArgb((int) sbyte.MaxValue, 157, 185);
    this.panel1.Controls.Add((Control) this.buttonAddEditPayment);
    this.panel1.Controls.Add((Control) this.buttonSave);
    this.panel1.Controls.Add((Control) this.buttonCancel);
    this.panel1.Dock = DockStyle.Bottom;
    this.panel1.Location = new Point(0, 320);
    this.panel1.Name = "panel1";
    this.panel1.Size = new Size(384, 40);
    this.panel1.TabIndex = 25;
    ((AppearanceBase) appearance5).BackColor = Color.FromArgb(248, 248, 248);
    ((AppearanceBase) appearance5).BackColor2 = Color.FromArgb(250, 250, 250);
    ((AppearanceBase) appearance5).BackGradientStyle = (GradientStyle) 2;
    ((AppearanceBase) appearance5).BorderColor = Color.DarkGray;
    ((AppearanceBase) appearance5).ImageHAlign = (HAlign) 2;
    ((AppearanceBase) appearance5).ImageVAlign = (VAlign) 2;
    ((ControlBase) this.buttonAddEditPayment).Appearance = (AppearanceBase) appearance5;
    ((Control) this.buttonAddEditPayment).Location = new Point(8, 8);
    ((Control) this.buttonAddEditPayment).Name = "buttonAddEditPayment";
    ((Control) this.buttonAddEditPayment).Size = new Size(152, 24);
    ((Control) this.buttonAddEditPayment).TabIndex = 25;
    ((Control) this.buttonAddEditPayment).Text = "Add/Edit Payment Methods";
    this.AcceptButton = (IButtonControl) this.buttonSave;
    this.AutoScaleBaseSize = new Size(5, 13);
    this.BackColor = Color.White;
    this.CancelButton = (IButtonControl) this.buttonCancel;
    this.ClientSize = new Size(384, 360);
    this.ControlBox = false;
    this.Controls.Add((Control) this.panel1);
    this.Controls.Add((Control) this.linkChangeExchange);
    this.Controls.Add((Control) this.linkChangeUnAccounted);
    this.Controls.Add((Control) this.linkChangeAP);
    this.Controls.Add((Control) this.linkChangeAR);
    this.Controls.Add((Control) this.label13);
    this.Controls.Add((Control) this.label14);
    this.Controls.Add((Control) this.label11);
    this.Controls.Add((Control) this.label12);
    this.Controls.Add((Control) this.label9);
    this.Controls.Add((Control) this.label10);
    this.Controls.Add((Control) this.label8);
    this.Controls.Add((Control) this.label7);
    this.Controls.Add((Control) this.label6);
    this.Controls.Add((Control) this.label5);
    this.Controls.Add((Control) this.label4);
    this.Controls.Add((Control) this.label3);
    this.Controls.Add((Control) this.comboOfficeLocation);
    this.Controls.Add((Control) this.label2);
    this.Controls.Add((Control) this.buttonSearchEntity);
    this.Controls.Add((Control) this.textEntityName);
    this.Controls.Add((Control) this.label1);
    this.Font = new Font("Tahoma", 8f);
    this.ForeColor = Color.Black;
    this.FormBorderStyle = FormBorderStyle.FixedDialog;
    this.Name = nameof (formAccountLinking);
    this.ShowInTaskbar = false;
    this.StartPosition = FormStartPosition.CenterScreen;
    this.Text = "Entity Account Linking";
    ((ISupportInitialize) this.textEntityName).EndInit();
    ((ISupportInitialize) this.buttonSearchEntity).EndInit();
    ((ISupportInitialize) this.comboOfficeLocation).EndInit();
    ((ISupportInitialize) this.buttonCancel).EndInit();
    ((ISupportInitialize) this.buttonSave).EndInit();
    this.panel1.ResumeLayout(false);
    ((ISupportInitialize) this.buttonAddEditPayment).EndInit();
    this.ResumeLayout(false);
  }

  private void label10_Click(object sender, EventArgs e)
  {
  }

  private void buttonCancel_Click(object sender, EventArgs e)
  {
    this.DialogResult = DialogResult.Cancel;
    this.Close();
  }
}
