// Decompiled with JetBrains decompiler
// Type: MGASystems.IMS.Accounting.Reports.rptCustomerRemittance
// Assembly: MgaSystems.IMS.Accounting.Reports, Version=2.0.0.0, Culture=neutral, PublicKeyToken=e175cb7c4ce15bbd
// MVID: 04B285D2-9F1D-4009-8AE0-5683AB5AFB4E
// Assembly location: D:\augusta\fortegra\IMS Project\MgaSystems.IMS.Accounting.Reports.dll

using GrapeCity.ActiveReports;
using GrapeCity.ActiveReports.Data;
using GrapeCity.ActiveReports.Document.Section;
using GrapeCity.ActiveReports.SectionReportModel;
using System.ComponentModel;
using System.Drawing;

#nullable disable
namespace MGASystems.IMS.Accounting.Reports;

public class rptCustomerRemittance : SectionReport
{
  private Detail Detail;
  private Label lblOaddress;
  private Label lblOname;
  private Label lblOacctnum;
  private Label lblOcontact;
  private Label lblOphone;
  private Label lblOcphone;
  private Label lblBaddress;
  private Label lblBname;
  private Label lblBcontact;
  private Label lblBphone;
  private Label lblBContactPhone;
  private Label lblBacct;
  private Label lblBbankname;
  private Label lblBabarouting;
  private Label lblBAddress2;
  private Label lblIbeneficiary;
  private Label lblIbankmemo;
  private TextBox txtIbeneficiary;
  private TextBox txtIbankmemo;
  private TextBox txtBBankName;
  private TextBox txtBAccountNum;
  private TextBox txtBAbaNum;
  private TextBox txtBPhone;
  private TextBox txtBContact;
  private TextBox txtBAddress2;
  private TextBox txtBContactPhone;
  private TextBox txtBAddress;
  private TextBox txtOphone;
  private TextBox txtOcontact;
  private TextBox txtOcontactphone;
  private TextBox txtOaccount;
  private TextBox txtOaddress;
  private Label Label2;
  private Line Line2;
  private Label Label3;
  private Line Line3;
  private Label Label4;
  private Line Line4;
  private ReportHeader ReportHeader;
  private Label lblTitle;
  private Label lblDate;
  private TextBox txtBankAddress;
  private TextBox txtBankName;
  private TextBox txtDate;
  private Label Label1;
  private TextBox txtAmount;
  private Line Line1;
  private ReportFooter ReportFooter;
  private Label lblSignature;
  private Label lblAddress;
  private Label lblPhone;
  private Label lblbtmDate;
  private TextBox txtPhone;
  private TextBox txtbtmDate;

  public rptCustomerRemittance() => this.InitializeComponent();

  private void InitializeComponent()
  {
    ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (rptCustomerRemittance));
    this.Detail = new Detail();
    this.ReportHeader = new ReportHeader();
    this.ReportFooter = new ReportFooter();
    this.lblTitle = new Label();
    this.lblDate = new Label();
    this.txtBankAddress = new TextBox();
    this.txtBankName = new TextBox();
    this.txtDate = new TextBox();
    this.Label1 = new Label();
    this.txtAmount = new TextBox();
    this.Line1 = new Line();
    this.lblOaddress = new Label();
    this.lblOname = new Label();
    this.lblOacctnum = new Label();
    this.lblOcontact = new Label();
    this.lblOphone = new Label();
    this.lblOcphone = new Label();
    this.lblBaddress = new Label();
    this.lblBname = new Label();
    this.lblBcontact = new Label();
    this.lblBphone = new Label();
    this.lblBContactPhone = new Label();
    this.lblBacct = new Label();
    this.lblBbankname = new Label();
    this.lblBabarouting = new Label();
    this.lblBAddress2 = new Label();
    this.lblIbeneficiary = new Label();
    this.lblIbankmemo = new Label();
    this.txtIbeneficiary = new TextBox();
    this.txtIbankmemo = new TextBox();
    this.txtBBankName = new TextBox();
    this.txtBAccountNum = new TextBox();
    this.txtBAbaNum = new TextBox();
    this.txtBPhone = new TextBox();
    this.txtBContact = new TextBox();
    this.txtBAddress2 = new TextBox();
    this.txtBContactPhone = new TextBox();
    this.txtBAddress = new TextBox();
    this.txtOphone = new TextBox();
    this.txtOcontact = new TextBox();
    this.txtOcontactphone = new TextBox();
    this.txtOaccount = new TextBox();
    this.txtOaddress = new TextBox();
    this.Label2 = new Label();
    this.Line2 = new Line();
    this.Label3 = new Label();
    this.Line3 = new Line();
    this.Label4 = new Label();
    this.Line4 = new Line();
    this.lblSignature = new Label();
    this.lblAddress = new Label();
    this.lblPhone = new Label();
    this.lblbtmDate = new Label();
    this.txtPhone = new TextBox();
    this.txtbtmDate = new TextBox();
    ((ISupportInitialize) this.lblTitle).BeginInit();
    ((ISupportInitialize) this.lblDate).BeginInit();
    ((ISupportInitialize) this.txtBankAddress).BeginInit();
    ((ISupportInitialize) this.txtBankName).BeginInit();
    ((ISupportInitialize) this.txtDate).BeginInit();
    ((ISupportInitialize) this.Label1).BeginInit();
    ((ISupportInitialize) this.txtAmount).BeginInit();
    ((ISupportInitialize) this.lblOaddress).BeginInit();
    ((ISupportInitialize) this.lblOname).BeginInit();
    ((ISupportInitialize) this.lblOacctnum).BeginInit();
    ((ISupportInitialize) this.lblOcontact).BeginInit();
    ((ISupportInitialize) this.lblOphone).BeginInit();
    ((ISupportInitialize) this.lblOcphone).BeginInit();
    ((ISupportInitialize) this.lblBaddress).BeginInit();
    ((ISupportInitialize) this.lblBname).BeginInit();
    ((ISupportInitialize) this.lblBcontact).BeginInit();
    ((ISupportInitialize) this.lblBphone).BeginInit();
    ((ISupportInitialize) this.lblBContactPhone).BeginInit();
    ((ISupportInitialize) this.lblBacct).BeginInit();
    ((ISupportInitialize) this.lblBbankname).BeginInit();
    ((ISupportInitialize) this.lblBabarouting).BeginInit();
    ((ISupportInitialize) this.lblBAddress2).BeginInit();
    ((ISupportInitialize) this.lblIbeneficiary).BeginInit();
    ((ISupportInitialize) this.lblIbankmemo).BeginInit();
    ((ISupportInitialize) this.txtIbeneficiary).BeginInit();
    ((ISupportInitialize) this.txtIbankmemo).BeginInit();
    ((ISupportInitialize) this.txtBBankName).BeginInit();
    ((ISupportInitialize) this.txtBAccountNum).BeginInit();
    ((ISupportInitialize) this.txtBAbaNum).BeginInit();
    ((ISupportInitialize) this.txtBPhone).BeginInit();
    ((ISupportInitialize) this.txtBContact).BeginInit();
    ((ISupportInitialize) this.txtBAddress2).BeginInit();
    ((ISupportInitialize) this.txtBContactPhone).BeginInit();
    ((ISupportInitialize) this.txtBAddress).BeginInit();
    ((ISupportInitialize) this.txtOphone).BeginInit();
    ((ISupportInitialize) this.txtOcontact).BeginInit();
    ((ISupportInitialize) this.txtOcontactphone).BeginInit();
    ((ISupportInitialize) this.txtOaccount).BeginInit();
    ((ISupportInitialize) this.txtOaddress).BeginInit();
    ((ISupportInitialize) this.Label2).BeginInit();
    ((ISupportInitialize) this.Label3).BeginInit();
    ((ISupportInitialize) this.Label4).BeginInit();
    ((ISupportInitialize) this.lblSignature).BeginInit();
    ((ISupportInitialize) this.lblAddress).BeginInit();
    ((ISupportInitialize) this.lblPhone).BeginInit();
    ((ISupportInitialize) this.lblbtmDate).BeginInit();
    ((ISupportInitialize) this.txtPhone).BeginInit();
    ((ISupportInitialize) this.txtbtmDate).BeginInit();
    this.Detail.ColumnSpacing = 0.0f;
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.Detail).Controls.AddRange(new ARControl[38]
    {
      (ARControl) this.lblOaddress,
      (ARControl) this.lblOname,
      (ARControl) this.lblOacctnum,
      (ARControl) this.lblOcontact,
      (ARControl) this.lblOphone,
      (ARControl) this.lblOcphone,
      (ARControl) this.lblBaddress,
      (ARControl) this.lblBname,
      (ARControl) this.lblBcontact,
      (ARControl) this.lblBphone,
      (ARControl) this.lblBContactPhone,
      (ARControl) this.lblBacct,
      (ARControl) this.lblBbankname,
      (ARControl) this.lblBabarouting,
      (ARControl) this.lblBAddress2,
      (ARControl) this.lblIbeneficiary,
      (ARControl) this.lblIbankmemo,
      (ARControl) this.txtIbeneficiary,
      (ARControl) this.txtIbankmemo,
      (ARControl) this.txtBBankName,
      (ARControl) this.txtBAccountNum,
      (ARControl) this.txtBAbaNum,
      (ARControl) this.txtBPhone,
      (ARControl) this.txtBContact,
      (ARControl) this.txtBAddress2,
      (ARControl) this.txtBContactPhone,
      (ARControl) this.txtBAddress,
      (ARControl) this.txtOphone,
      (ARControl) this.txtOcontact,
      (ARControl) this.txtOcontactphone,
      (ARControl) this.txtOaccount,
      (ARControl) this.txtOaddress,
      (ARControl) this.Label2,
      (ARControl) this.Line2,
      (ARControl) this.Label3,
      (ARControl) this.Line3,
      (ARControl) this.Label4,
      (ARControl) this.Line4
    });
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.Detail).Height = 7.040972f;
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.Detail).Name = "Detail";
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.ReportHeader).Controls.AddRange(new ARControl[8]
    {
      (ARControl) this.lblTitle,
      (ARControl) this.lblDate,
      (ARControl) this.txtBankAddress,
      (ARControl) this.txtBankName,
      (ARControl) this.txtDate,
      (ARControl) this.Label1,
      (ARControl) this.txtAmount,
      (ARControl) this.Line1
    });
    this.ReportHeader.Height = 0.7916667f;
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.ReportHeader).Name = "ReportHeader";
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.ReportFooter).Controls.AddRange(new ARControl[6]
    {
      (ARControl) this.lblSignature,
      (ARControl) this.lblAddress,
      (ARControl) this.lblPhone,
      (ARControl) this.lblbtmDate,
      (ARControl) this.txtPhone,
      (ARControl) this.txtbtmDate
    });
    this.ReportFooter.Height = 0.75f;
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.ReportFooter).Name = "ReportFooter";
    ((ARControl) this.lblTitle).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblTitle).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblTitle).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblTitle).Border.TopStyle = (BorderLineStyle) 0;
    this.lblTitle.Font = new Font("Arial", 15.75f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.lblTitle.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblTitle.HyperLink = (string) null;
    Label lblTitle = this.lblTitle;
    object obj1 = componentResourceManager.GetObject("lblTitle.Location");
    PointF pointF1 = obj1 != null ? (PointF) obj1 : new PointF();
    ((ARControl) lblTitle).Location = pointF1;
    ((ARControl) this.lblTitle).Name = "lblTitle";
    ((ARControl) this.lblTitle).Size = new SizeF(63f / 16f, 0.25f);
    this.lblTitle.Text = "Customer Remittance Request";
    ((ARControl) this.lblDate).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblDate).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblDate).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblDate).Border.TopStyle = (BorderLineStyle) 0;
    this.lblDate.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblDate.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblDate.HyperLink = (string) null;
    Label lblDate = this.lblDate;
    object obj2 = componentResourceManager.GetObject("lblDate.Location");
    PointF pointF2 = obj2 != null ? (PointF) obj2 : new PointF();
    ((ARControl) lblDate).Location = pointF2;
    ((ARControl) this.lblDate).Name = "lblDate";
    ((ARControl) this.lblDate).Size = new SizeF(15f / 16f, 3f / 16f);
    this.lblDate.Text = "Date:";
    ((ARControl) this.txtBankAddress).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBankAddress).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBankAddress).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBankAddress).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBankAddress).DataField = "BANKADDRESS";
    this.txtBankAddress.DistinctField = (string) null;
    this.txtBankAddress.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.txtBankAddress.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtBankAddress = this.txtBankAddress;
    object obj3 = componentResourceManager.GetObject("txtBankAddress.Location");
    PointF pointF3 = obj3 != null ? (PointF) obj3 : new PointF();
    ((ARControl) txtBankAddress).Location = pointF3;
    ((ARControl) this.txtBankAddress).Name = "txtBankAddress";
    this.txtBankAddress.OutputFormat = (string) null;
    ((ARControl) this.txtBankAddress).Size = new SizeF(75f / 16f, 3f / 16f);
    this.txtBankAddress.Text = "[bank address]";
    ((ARControl) this.txtBankName).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBankName).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBankName).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBankName).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBankName).DataField = "BankName";
    this.txtBankName.DistinctField = (string) null;
    this.txtBankName.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.txtBankName.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtBankName = this.txtBankName;
    object obj4 = componentResourceManager.GetObject("txtBankName.Location");
    PointF pointF4 = obj4 != null ? (PointF) obj4 : new PointF();
    ((ARControl) txtBankName).Location = pointF4;
    ((ARControl) this.txtBankName).Name = "txtBankName";
    this.txtBankName.OutputFormat = (string) null;
    ((ARControl) this.txtBankName).Size = new SizeF(75f / 16f, 3f / 16f);
    this.txtBankName.Text = "[bank name]";
    this.txtBankName.VerticalAlignment = (VerticalTextAlignment) 2;
    this.txtDate.Alignment = (TextAlignment) 2;
    ((ARControl) this.txtDate).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtDate).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtDate).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtDate).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtDate).DataField = "CHECKDATE";
    this.txtDate.DistinctField = (string) null;
    this.txtDate.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.txtDate.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtDate = this.txtDate;
    object obj5 = componentResourceManager.GetObject("txtDate.Location");
    PointF pointF5 = obj5 != null ? (PointF) obj5 : new PointF();
    ((ARControl) txtDate).Location = pointF5;
    ((ARControl) this.txtDate).Name = "txtDate";
    this.txtDate.OutputFormat = "M/d/yyyy";
    ((ARControl) this.txtDate).Size = new SizeF(13f / 16f, 3f / 16f);
    ((ARControl) this.Label1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label1).Border.TopStyle = (BorderLineStyle) 0;
    this.Label1.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold);
    this.Label1.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label1.HyperLink = (string) null;
    Label label1 = this.Label1;
    object obj6 = componentResourceManager.GetObject("Label1.Location");
    PointF pointF6 = obj6 != null ? (PointF) obj6 : new PointF();
    ((ARControl) label1).Location = pointF6;
    ((ARControl) this.Label1).Name = "Label1";
    ((ARControl) this.Label1).Size = new SizeF(11f / 16f, 3f / 16f);
    this.Label1.Text = "Amount:";
    this.txtAmount.Alignment = (TextAlignment) 2;
    ((ARControl) this.txtAmount).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmount).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmount).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmount).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmount).DataField = "CheckAmount";
    this.txtAmount.DistinctField = (string) null;
    this.txtAmount.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold);
    this.txtAmount.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtAmount = this.txtAmount;
    object obj7 = componentResourceManager.GetObject("txtAmount.Location");
    PointF pointF7 = obj7 != null ? (PointF) obj7 : new PointF();
    ((ARControl) txtAmount).Location = pointF7;
    ((ARControl) this.txtAmount).Name = "txtAmount";
    this.txtAmount.OutputFormat = "$#,##0.00;($#,##0.00)";
    ((ARControl) this.txtAmount).Size = new SizeF(1.125f, 3f / 16f);
    this.Line1.Border.BottomStyle = (BorderLineStyle) 0;
    this.Line1.Border.LeftStyle = (BorderLineStyle) 0;
    this.Line1.Border.RightStyle = (BorderLineStyle) 0;
    this.Line1.Border.TopStyle = (BorderLineStyle) 0;
    this.Line1.LineWeight = 1f;
    ((ARControl) this.Line1).Name = "Line1";
    this.Line1.X1 = 0.0f;
    this.Line1.X2 = 111f / 16f;
    this.Line1.Y1 = 0.25f;
    this.Line1.Y2 = 0.25f;
    ((ARControl) this.lblOaddress).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOaddress).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOaddress).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOaddress).Border.TopStyle = (BorderLineStyle) 0;
    this.lblOaddress.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblOaddress.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblOaddress.HyperLink = (string) null;
    Label lblOaddress = this.lblOaddress;
    object obj8 = componentResourceManager.GetObject("lblOaddress.Location");
    PointF pointF8 = obj8 != null ? (PointF) obj8 : new PointF();
    ((ARControl) lblOaddress).Location = pointF8;
    ((ARControl) this.lblOaddress).Name = "lblOaddress";
    ((ARControl) this.lblOaddress).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblOaddress.Text = "Address:";
    ((ARControl) this.lblOname).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOname).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOname).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOname).Border.TopStyle = (BorderLineStyle) 0;
    this.lblOname.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblOname.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblOname.HyperLink = (string) null;
    Label lblOname = this.lblOname;
    object obj9 = componentResourceManager.GetObject("lblOname.Location");
    PointF pointF9 = obj9 != null ? (PointF) obj9 : new PointF();
    ((ARControl) lblOname).Location = pointF9;
    ((ARControl) this.lblOname).Name = "lblOname";
    ((ARControl) this.lblOname).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblOname.Text = "Name:";
    ((ARControl) this.lblOacctnum).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOacctnum).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOacctnum).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOacctnum).Border.TopStyle = (BorderLineStyle) 0;
    this.lblOacctnum.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblOacctnum.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblOacctnum.HyperLink = (string) null;
    Label lblOacctnum = this.lblOacctnum;
    object obj10 = componentResourceManager.GetObject("lblOacctnum.Location");
    PointF pointF10 = obj10 != null ? (PointF) obj10 : new PointF();
    ((ARControl) lblOacctnum).Location = pointF10;
    ((ARControl) this.lblOacctnum).Name = "lblOacctnum";
    ((ARControl) this.lblOacctnum).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblOacctnum.Text = "Account #:";
    ((ARControl) this.lblOcontact).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOcontact).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOcontact).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOcontact).Border.TopStyle = (BorderLineStyle) 0;
    this.lblOcontact.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblOcontact.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblOcontact.HyperLink = (string) null;
    Label lblOcontact = this.lblOcontact;
    object obj11 = componentResourceManager.GetObject("lblOcontact.Location");
    PointF pointF11 = obj11 != null ? (PointF) obj11 : new PointF();
    ((ARControl) lblOcontact).Location = pointF11;
    ((ARControl) this.lblOcontact).Name = "lblOcontact";
    ((ARControl) this.lblOcontact).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblOcontact.Text = "Contact:";
    ((ARControl) this.lblOphone).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOphone).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOphone).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOphone).Border.TopStyle = (BorderLineStyle) 0;
    this.lblOphone.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblOphone.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblOphone.HyperLink = (string) null;
    Label lblOphone = this.lblOphone;
    object obj12 = componentResourceManager.GetObject("lblOphone.Location");
    PointF pointF12 = obj12 != null ? (PointF) obj12 : new PointF();
    ((ARControl) lblOphone).Location = pointF12;
    ((ARControl) this.lblOphone).Name = "lblOphone";
    ((ARControl) this.lblOphone).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblOphone.Text = "Phone #:";
    ((ARControl) this.lblOcphone).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOcphone).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOcphone).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblOcphone).Border.TopStyle = (BorderLineStyle) 0;
    this.lblOcphone.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblOcphone.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblOcphone.HyperLink = (string) null;
    Label lblOcphone = this.lblOcphone;
    object obj13 = componentResourceManager.GetObject("lblOcphone.Location");
    PointF pointF13 = obj13 != null ? (PointF) obj13 : new PointF();
    ((ARControl) lblOcphone).Location = pointF13;
    ((ARControl) this.lblOcphone).Name = "lblOcphone";
    ((ARControl) this.lblOcphone).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblOcphone.Text = "Contact Phone:";
    ((ARControl) this.lblBaddress).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBaddress).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBaddress).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBaddress).Border.TopStyle = (BorderLineStyle) 0;
    this.lblBaddress.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblBaddress.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblBaddress.HyperLink = (string) null;
    Label lblBaddress = this.lblBaddress;
    object obj14 = componentResourceManager.GetObject("lblBaddress.Location");
    PointF pointF14 = obj14 != null ? (PointF) obj14 : new PointF();
    ((ARControl) lblBaddress).Location = pointF14;
    ((ARControl) this.lblBaddress).Name = "lblBaddress";
    ((ARControl) this.lblBaddress).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblBaddress.Text = "Address:";
    ((ARControl) this.lblBname).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBname).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBname).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBname).Border.TopStyle = (BorderLineStyle) 0;
    this.lblBname.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblBname.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblBname.HyperLink = (string) null;
    Label lblBname = this.lblBname;
    object obj15 = componentResourceManager.GetObject("lblBname.Location");
    PointF pointF15 = obj15 != null ? (PointF) obj15 : new PointF();
    ((ARControl) lblBname).Location = pointF15;
    ((ARControl) this.lblBname).Name = "lblBname";
    ((ARControl) this.lblBname).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblBname.Text = "Name";
    ((ARControl) this.lblBcontact).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBcontact).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBcontact).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBcontact).Border.TopStyle = (BorderLineStyle) 0;
    this.lblBcontact.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblBcontact.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblBcontact.HyperLink = (string) null;
    Label lblBcontact = this.lblBcontact;
    object obj16 = componentResourceManager.GetObject("lblBcontact.Location");
    PointF pointF16 = obj16 != null ? (PointF) obj16 : new PointF();
    ((ARControl) lblBcontact).Location = pointF16;
    ((ARControl) this.lblBcontact).Name = "lblBcontact";
    ((ARControl) this.lblBcontact).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblBcontact.Text = "Contact:";
    ((ARControl) this.lblBphone).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBphone).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBphone).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBphone).Border.TopStyle = (BorderLineStyle) 0;
    this.lblBphone.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblBphone.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblBphone.HyperLink = (string) null;
    Label lblBphone = this.lblBphone;
    object obj17 = componentResourceManager.GetObject("lblBphone.Location");
    PointF pointF17 = obj17 != null ? (PointF) obj17 : new PointF();
    ((ARControl) lblBphone).Location = pointF17;
    ((ARControl) this.lblBphone).Name = "lblBphone";
    ((ARControl) this.lblBphone).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblBphone.Text = "Phone #:";
    ((ARControl) this.lblBContactPhone).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBContactPhone).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBContactPhone).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBContactPhone).Border.TopStyle = (BorderLineStyle) 0;
    this.lblBContactPhone.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblBContactPhone.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblBContactPhone.HyperLink = (string) null;
    Label lblBcontactPhone = this.lblBContactPhone;
    object obj18 = componentResourceManager.GetObject("lblBContactPhone.Location");
    PointF pointF18 = obj18 != null ? (PointF) obj18 : new PointF();
    ((ARControl) lblBcontactPhone).Location = pointF18;
    ((ARControl) this.lblBContactPhone).Name = "lblBContactPhone";
    ((ARControl) this.lblBContactPhone).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblBContactPhone.Text = "Contact Phone:";
    ((ARControl) this.lblBacct).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBacct).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBacct).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBacct).Border.TopStyle = (BorderLineStyle) 0;
    this.lblBacct.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblBacct.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblBacct.HyperLink = (string) null;
    Label lblBacct = this.lblBacct;
    object obj19 = componentResourceManager.GetObject("lblBacct.Location");
    PointF pointF19 = obj19 != null ? (PointF) obj19 : new PointF();
    ((ARControl) lblBacct).Location = pointF19;
    ((ARControl) this.lblBacct).Name = "lblBacct";
    ((ARControl) this.lblBacct).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblBacct.Text = "Account #:";
    ((ARControl) this.lblBbankname).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBbankname).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBbankname).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBbankname).Border.TopStyle = (BorderLineStyle) 0;
    this.lblBbankname.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblBbankname.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblBbankname.HyperLink = (string) null;
    Label lblBbankname = this.lblBbankname;
    object obj20 = componentResourceManager.GetObject("lblBbankname.Location");
    PointF pointF20 = obj20 != null ? (PointF) obj20 : new PointF();
    ((ARControl) lblBbankname).Location = pointF20;
    ((ARControl) this.lblBbankname).Name = "lblBbankname";
    ((ARControl) this.lblBbankname).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblBbankname.Text = "Bank Name:";
    ((ARControl) this.lblBabarouting).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBabarouting).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBabarouting).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBabarouting).Border.TopStyle = (BorderLineStyle) 0;
    this.lblBabarouting.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblBabarouting.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblBabarouting.HyperLink = (string) null;
    Label lblBabarouting = this.lblBabarouting;
    object obj21 = componentResourceManager.GetObject("lblBabarouting.Location");
    PointF pointF21 = obj21 != null ? (PointF) obj21 : new PointF();
    ((ARControl) lblBabarouting).Location = pointF21;
    ((ARControl) this.lblBabarouting).Name = "lblBabarouting";
    ((ARControl) this.lblBabarouting).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblBabarouting.Text = "ABA Routing #:";
    ((ARControl) this.lblBAddress2).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBAddress2).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBAddress2).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBAddress2).Border.TopStyle = (BorderLineStyle) 0;
    this.lblBAddress2.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblBAddress2.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblBAddress2.HyperLink = (string) null;
    Label lblBaddress2 = this.lblBAddress2;
    object obj22 = componentResourceManager.GetObject("lblBAddress2.Location");
    PointF pointF22 = obj22 != null ? (PointF) obj22 : new PointF();
    ((ARControl) lblBaddress2).Location = pointF22;
    ((ARControl) this.lblBAddress2).Name = "lblBAddress2";
    ((ARControl) this.lblBAddress2).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblBAddress2.Text = "Address:";
    ((ARControl) this.lblIbeneficiary).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblIbeneficiary).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblIbeneficiary).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblIbeneficiary).Border.TopStyle = (BorderLineStyle) 0;
    this.lblIbeneficiary.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblIbeneficiary.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblIbeneficiary.HyperLink = (string) null;
    Label lblIbeneficiary = this.lblIbeneficiary;
    object obj23 = componentResourceManager.GetObject("lblIbeneficiary.Location");
    PointF pointF23 = obj23 != null ? (PointF) obj23 : new PointF();
    ((ARControl) lblIbeneficiary).Location = pointF23;
    ((ARControl) this.lblIbeneficiary).Name = "lblIbeneficiary";
    ((ARControl) this.lblIbeneficiary).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblIbeneficiary.Text = "Beneficiary Memo:";
    ((ARControl) this.lblIbankmemo).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblIbankmemo).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblIbankmemo).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblIbankmemo).Border.TopStyle = (BorderLineStyle) 0;
    this.lblIbankmemo.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblIbankmemo.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblIbankmemo.HyperLink = (string) null;
    Label lblIbankmemo = this.lblIbankmemo;
    object obj24 = componentResourceManager.GetObject("lblIbankmemo.Location");
    PointF pointF24 = obj24 != null ? (PointF) obj24 : new PointF();
    ((ARControl) lblIbankmemo).Location = pointF24;
    ((ARControl) this.lblIbankmemo).Name = "lblIbankmemo";
    ((ARControl) this.lblIbankmemo).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblIbankmemo.Text = "Bank Memo:";
    ((ARControl) this.txtIbeneficiary).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtIbeneficiary).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtIbeneficiary).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtIbeneficiary).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtIbeneficiary).DataField = "PayeeMemo";
    this.txtIbeneficiary.DistinctField = (string) null;
    this.txtIbeneficiary.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtIbeneficiary.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtIbeneficiary = this.txtIbeneficiary;
    object obj25 = componentResourceManager.GetObject("txtIbeneficiary.Location");
    PointF pointF25 = obj25 != null ? (PointF) obj25 : new PointF();
    ((ARControl) txtIbeneficiary).Location = pointF25;
    ((ARControl) this.txtIbeneficiary).Name = "txtIbeneficiary";
    this.txtIbeneficiary.OutputFormat = (string) null;
    ((ARControl) this.txtIbeneficiary).Size = new SizeF(81f / 16f, 3f / 16f);
    ((ARControl) this.txtIbankmemo).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtIbankmemo).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtIbankmemo).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtIbankmemo).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtIbankmemo).DataField = "ToBankMemo";
    this.txtIbankmemo.DistinctField = (string) null;
    this.txtIbankmemo.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtIbankmemo.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtIbankmemo = this.txtIbankmemo;
    object obj26 = componentResourceManager.GetObject("txtIbankmemo.Location");
    PointF pointF26 = obj26 != null ? (PointF) obj26 : new PointF();
    ((ARControl) txtIbankmemo).Location = pointF26;
    ((ARControl) this.txtIbankmemo).Name = "txtIbankmemo";
    this.txtIbankmemo.OutputFormat = (string) null;
    ((ARControl) this.txtIbankmemo).Size = new SizeF(81f / 16f, 3f / 16f);
    ((ARControl) this.txtBBankName).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBBankName).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBBankName).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBBankName).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBBankName).DataField = "ToBankName";
    this.txtBBankName.DistinctField = (string) null;
    this.txtBBankName.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtBBankName.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtBbankName = this.txtBBankName;
    object obj27 = componentResourceManager.GetObject("txtBBankName.Location");
    PointF pointF27 = obj27 != null ? (PointF) obj27 : new PointF();
    ((ARControl) txtBbankName).Location = pointF27;
    ((ARControl) this.txtBBankName).Name = "txtBBankName";
    this.txtBBankName.OutputFormat = (string) null;
    ((ARControl) this.txtBBankName).Size = new SizeF(81f / 16f, 3f / 16f);
    ((ARControl) this.txtBAccountNum).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAccountNum).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAccountNum).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAccountNum).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAccountNum).DataField = "PayeeBankAcctNum";
    this.txtBAccountNum.DistinctField = (string) null;
    this.txtBAccountNum.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtBAccountNum.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtBaccountNum = this.txtBAccountNum;
    object obj28 = componentResourceManager.GetObject("txtBAccountNum.Location");
    PointF pointF28 = obj28 != null ? (PointF) obj28 : new PointF();
    ((ARControl) txtBaccountNum).Location = pointF28;
    ((ARControl) this.txtBAccountNum).Name = "txtBAccountNum";
    this.txtBAccountNum.OutputFormat = (string) null;
    ((ARControl) this.txtBAccountNum).Size = new SizeF(81f / 16f, 3f / 16f);
    ((ARControl) this.txtBAbaNum).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAbaNum).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAbaNum).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAbaNum).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAbaNum).DataField = "ToBankABARouteNum";
    this.txtBAbaNum.DistinctField = (string) null;
    this.txtBAbaNum.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtBAbaNum.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtBabaNum = this.txtBAbaNum;
    object obj29 = componentResourceManager.GetObject("txtBAbaNum.Location");
    PointF pointF29 = obj29 != null ? (PointF) obj29 : new PointF();
    ((ARControl) txtBabaNum).Location = pointF29;
    ((ARControl) this.txtBAbaNum).Name = "txtBAbaNum";
    this.txtBAbaNum.OutputFormat = (string) null;
    ((ARControl) this.txtBAbaNum).Size = new SizeF(81f / 16f, 3f / 16f);
    ((ARControl) this.txtBPhone).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBPhone).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBPhone).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBPhone).Border.TopStyle = (BorderLineStyle) 0;
    this.txtBPhone.DistinctField = (string) null;
    this.txtBPhone.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtBPhone.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtBphone = this.txtBPhone;
    object obj30 = componentResourceManager.GetObject("txtBPhone.Location");
    PointF pointF30 = obj30 != null ? (PointF) obj30 : new PointF();
    ((ARControl) txtBphone).Location = pointF30;
    ((ARControl) this.txtBPhone).Name = "txtBPhone";
    this.txtBPhone.OutputFormat = (string) null;
    ((ARControl) this.txtBPhone).Size = new SizeF(81f / 16f, 3f / 16f);
    ((ARControl) this.txtBContact).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBContact).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBContact).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBContact).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBContact).DataField = "PayeeContact";
    this.txtBContact.DistinctField = (string) null;
    this.txtBContact.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtBContact.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtBcontact = this.txtBContact;
    object obj31 = componentResourceManager.GetObject("txtBContact.Location");
    PointF pointF31 = obj31 != null ? (PointF) obj31 : new PointF();
    ((ARControl) txtBcontact).Location = pointF31;
    ((ARControl) this.txtBContact).Name = "txtBContact";
    this.txtBContact.OutputFormat = (string) null;
    ((ARControl) this.txtBContact).Size = new SizeF(81f / 16f, 3f / 16f);
    ((ARControl) this.txtBAddress2).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAddress2).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAddress2).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAddress2).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAddress2).DataField = "TOBANKADDRESS";
    this.txtBAddress2.DistinctField = (string) null;
    this.txtBAddress2.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtBAddress2.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtBaddress2 = this.txtBAddress2;
    object obj32 = componentResourceManager.GetObject("txtBAddress2.Location");
    PointF pointF32 = obj32 != null ? (PointF) obj32 : new PointF();
    ((ARControl) txtBaddress2).Location = pointF32;
    ((ARControl) this.txtBAddress2).Name = "txtBAddress2";
    this.txtBAddress2.OutputFormat = (string) null;
    ((ARControl) this.txtBAddress2).Size = new SizeF(81f / 16f, 3f / 16f);
    ((ARControl) this.txtBContactPhone).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBContactPhone).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBContactPhone).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBContactPhone).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBContactPhone).DataField = "PayeeContactPhone";
    this.txtBContactPhone.DistinctField = (string) null;
    this.txtBContactPhone.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtBContactPhone.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtBcontactPhone = this.txtBContactPhone;
    object obj33 = componentResourceManager.GetObject("txtBContactPhone.Location");
    PointF pointF33 = obj33 != null ? (PointF) obj33 : new PointF();
    ((ARControl) txtBcontactPhone).Location = pointF33;
    ((ARControl) this.txtBContactPhone).Name = "txtBContactPhone";
    this.txtBContactPhone.OutputFormat = (string) null;
    ((ARControl) this.txtBContactPhone).Size = new SizeF(81f / 16f, 3f / 16f);
    ((ARControl) this.txtBAddress).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAddress).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAddress).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAddress).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtBAddress).DataField = "PayeeAddress";
    this.txtBAddress.DistinctField = (string) null;
    this.txtBAddress.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtBAddress.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtBaddress = this.txtBAddress;
    object obj34 = componentResourceManager.GetObject("txtBAddress.Location");
    PointF pointF34 = obj34 != null ? (PointF) obj34 : new PointF();
    ((ARControl) txtBaddress).Location = pointF34;
    ((ARControl) this.txtBAddress).Name = "txtBAddress";
    this.txtBAddress.OutputFormat = (string) null;
    ((ARControl) this.txtBAddress).Size = new SizeF(81f / 16f, 15f / 16f);
    ((ARControl) this.txtOphone).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOphone).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOphone).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOphone).Border.TopStyle = (BorderLineStyle) 0;
    this.txtOphone.DistinctField = (string) null;
    this.txtOphone.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtOphone.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtOphone = this.txtOphone;
    object obj35 = componentResourceManager.GetObject("txtOphone.Location");
    PointF pointF35 = obj35 != null ? (PointF) obj35 : new PointF();
    ((ARControl) txtOphone).Location = pointF35;
    ((ARControl) this.txtOphone).Name = "txtOphone";
    this.txtOphone.OutputFormat = (string) null;
    ((ARControl) this.txtOphone).Size = new SizeF(81f / 16f, 3f / 16f);
    ((ARControl) this.txtOcontact).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOcontact).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOcontact).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOcontact).Border.TopStyle = (BorderLineStyle) 0;
    this.txtOcontact.DistinctField = (string) null;
    this.txtOcontact.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtOcontact.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtOcontact = this.txtOcontact;
    object obj36 = componentResourceManager.GetObject("txtOcontact.Location");
    PointF pointF36 = obj36 != null ? (PointF) obj36 : new PointF();
    ((ARControl) txtOcontact).Location = pointF36;
    ((ARControl) this.txtOcontact).Name = "txtOcontact";
    this.txtOcontact.OutputFormat = (string) null;
    ((ARControl) this.txtOcontact).Size = new SizeF(81f / 16f, 3f / 16f);
    ((ARControl) this.txtOcontactphone).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOcontactphone).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOcontactphone).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOcontactphone).Border.TopStyle = (BorderLineStyle) 0;
    this.txtOcontactphone.DistinctField = (string) null;
    this.txtOcontactphone.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtOcontactphone.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtOcontactphone = this.txtOcontactphone;
    object obj37 = componentResourceManager.GetObject("txtOcontactphone.Location");
    PointF pointF37 = obj37 != null ? (PointF) obj37 : new PointF();
    ((ARControl) txtOcontactphone).Location = pointF37;
    ((ARControl) this.txtOcontactphone).Name = "txtOcontactphone";
    this.txtOcontactphone.OutputFormat = (string) null;
    ((ARControl) this.txtOcontactphone).Size = new SizeF(81f / 16f, 3f / 16f);
    ((ARControl) this.txtOaccount).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOaccount).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOaccount).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOaccount).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOaccount).DataField = "BANKACCTNUM";
    this.txtOaccount.DistinctField = (string) null;
    this.txtOaccount.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtOaccount.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtOaccount = this.txtOaccount;
    object obj38 = componentResourceManager.GetObject("txtOaccount.Location");
    PointF pointF38 = obj38 != null ? (PointF) obj38 : new PointF();
    ((ARControl) txtOaccount).Location = pointF38;
    ((ARControl) this.txtOaccount).Name = "txtOaccount";
    this.txtOaccount.OutputFormat = (string) null;
    ((ARControl) this.txtOaccount).Size = new SizeF(81f / 16f, 3f / 16f);
    ((ARControl) this.txtOaddress).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOaddress).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOaddress).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOaddress).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtOaddress).DataField = "ORIGINATOR";
    this.txtOaddress.DistinctField = (string) null;
    this.txtOaddress.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtOaddress.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtOaddress = this.txtOaddress;
    object obj39 = componentResourceManager.GetObject("txtOaddress.Location");
    PointF pointF39 = obj39 != null ? (PointF) obj39 : new PointF();
    ((ARControl) txtOaddress).Location = pointF39;
    ((ARControl) this.txtOaddress).Name = "txtOaddress";
    this.txtOaddress.OutputFormat = (string) null;
    ((ARControl) this.txtOaddress).Size = new SizeF(81f / 16f, 15f / 16f);
    ((ARControl) this.Label2).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label2).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label2).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label2).Border.TopStyle = (BorderLineStyle) 0;
    this.Label2.Font = new Font("Arial", 11.25f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Label2.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label2.HyperLink = (string) null;
    Label label2 = this.Label2;
    object obj40 = componentResourceManager.GetObject("Label2.Location");
    PointF pointF40 = obj40 != null ? (PointF) obj40 : new PointF();
    ((ARControl) label2).Location = pointF40;
    ((ARControl) this.Label2).Name = "Label2";
    ((ARControl) this.Label2).Size = new SizeF(1.625f, 3f / 16f);
    this.Label2.Text = "Originator";
    this.Line2.Border.BottomStyle = (BorderLineStyle) 0;
    this.Line2.Border.LeftStyle = (BorderLineStyle) 0;
    this.Line2.Border.RightStyle = (BorderLineStyle) 0;
    this.Line2.Border.TopStyle = (BorderLineStyle) 0;
    this.Line2.LineWeight = 1f;
    ((ARControl) this.Line2).Name = "Line2";
    this.Line2.X1 = 0.0f;
    this.Line2.X2 = 7f;
    this.Line2.Y1 = 0.25f;
    this.Line2.Y2 = 0.25f;
    ((ARControl) this.Label3).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label3).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label3).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label3).Border.TopStyle = (BorderLineStyle) 0;
    this.Label3.Font = new Font("Arial", 11.25f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Label3.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label3.HyperLink = (string) null;
    Label label3 = this.Label3;
    object obj41 = componentResourceManager.GetObject("Label3.Location");
    PointF pointF41 = obj41 != null ? (PointF) obj41 : new PointF();
    ((ARControl) label3).Location = pointF41;
    ((ARControl) this.Label3).Name = "Label3";
    ((ARControl) this.Label3).Size = new SizeF(1.625f, 3f / 16f);
    this.Label3.Text = "Beneficiary";
    this.Line3.Border.BottomStyle = (BorderLineStyle) 0;
    this.Line3.Border.LeftStyle = (BorderLineStyle) 0;
    this.Line3.Border.RightStyle = (BorderLineStyle) 0;
    this.Line3.Border.TopStyle = (BorderLineStyle) 0;
    this.Line3.LineWeight = 1f;
    ((ARControl) this.Line3).Name = "Line3";
    this.Line3.X1 = 0.0f;
    this.Line3.X2 = 7f;
    this.Line3.Y1 = 2.541667f;
    this.Line3.Y2 = 2.541667f;
    ((ARControl) this.Label4).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label4).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label4).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label4).Border.TopStyle = (BorderLineStyle) 0;
    this.Label4.Font = new Font("Arial", 11.25f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Label4.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label4.HyperLink = (string) null;
    Label label4 = this.Label4;
    object obj42 = componentResourceManager.GetObject("Label4.Location");
    PointF pointF42 = obj42 != null ? (PointF) obj42 : new PointF();
    ((ARControl) label4).Location = pointF42;
    ((ARControl) this.Label4).Name = "Label4";
    ((ARControl) this.Label4).Size = new SizeF(1.625f, 3f / 16f);
    this.Label4.Text = "Instructions";
    this.Line4.Border.BottomStyle = (BorderLineStyle) 0;
    this.Line4.Border.LeftStyle = (BorderLineStyle) 0;
    this.Line4.Border.RightStyle = (BorderLineStyle) 0;
    this.Line4.Border.TopStyle = (BorderLineStyle) 0;
    this.Line4.LineWeight = 1f;
    ((ARControl) this.Line4).Name = "Line4";
    this.Line4.X1 = 0.0f;
    this.Line4.X2 = 7f;
    this.Line4.Y1 = 89f / 16f;
    this.Line4.Y2 = 89f / 16f;
    ((ARControl) this.lblSignature).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblSignature).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblSignature).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblSignature).Border.TopStyle = (BorderLineStyle) 0;
    this.lblSignature.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblSignature.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblSignature.HyperLink = (string) null;
    Label lblSignature = this.lblSignature;
    object obj43 = componentResourceManager.GetObject("lblSignature.Location");
    PointF pointF43 = obj43 != null ? (PointF) obj43 : new PointF();
    ((ARControl) lblSignature).Location = pointF43;
    ((ARControl) this.lblSignature).Name = "lblSignature";
    ((ARControl) this.lblSignature).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblSignature.Text = "Signature:";
    ((ARControl) this.lblAddress).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblAddress).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblAddress).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblAddress).Border.TopStyle = (BorderLineStyle) 0;
    this.lblAddress.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblAddress.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblAddress.HyperLink = (string) null;
    Label lblAddress = this.lblAddress;
    object obj44 = componentResourceManager.GetObject("lblAddress.Location");
    PointF pointF44 = obj44 != null ? (PointF) obj44 : new PointF();
    ((ARControl) lblAddress).Location = pointF44;
    ((ARControl) this.lblAddress).Name = "lblAddress";
    ((ARControl) this.lblAddress).Size = new SizeF(31f / 16f, 3f / 16f);
    this.lblAddress.Text = "Address:";
    ((ARControl) this.lblPhone).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblPhone).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblPhone).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblPhone).Border.TopStyle = (BorderLineStyle) 0;
    this.lblPhone.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblPhone.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblPhone.HyperLink = (string) null;
    Label lblPhone = this.lblPhone;
    object obj45 = componentResourceManager.GetObject("lblPhone.Location");
    PointF pointF45 = obj45 != null ? (PointF) obj45 : new PointF();
    ((ARControl) lblPhone).Location = pointF45;
    ((ARControl) this.lblPhone).Name = "lblPhone";
    ((ARControl) this.lblPhone).Size = new SizeF(0.625f, 3f / 16f);
    this.lblPhone.Text = "Phone:";
    ((ARControl) this.lblbtmDate).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblbtmDate).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblbtmDate).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblbtmDate).Border.TopStyle = (BorderLineStyle) 0;
    this.lblbtmDate.Font = new Font("Arial", 9.75f, System.Drawing.FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblbtmDate.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblbtmDate.HyperLink = (string) null;
    Label lblbtmDate = this.lblbtmDate;
    object obj46 = componentResourceManager.GetObject("lblbtmDate.Location");
    PointF pointF46 = obj46 != null ? (PointF) obj46 : new PointF();
    ((ARControl) lblbtmDate).Location = pointF46;
    ((ARControl) this.lblbtmDate).Name = "lblbtmDate";
    ((ARControl) this.lblbtmDate).Size = new SizeF(0.625f, 3f / 16f);
    this.lblbtmDate.Text = "Date:";
    this.txtPhone.Alignment = (TextAlignment) 2;
    ((ARControl) this.txtPhone).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtPhone).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtPhone).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtPhone).Border.TopStyle = (BorderLineStyle) 0;
    this.txtPhone.DistinctField = (string) null;
    this.txtPhone.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtPhone.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtPhone = this.txtPhone;
    object obj47 = componentResourceManager.GetObject("txtPhone.Location");
    PointF pointF47 = obj47 != null ? (PointF) obj47 : new PointF();
    ((ARControl) txtPhone).Location = pointF47;
    ((ARControl) this.txtPhone).Name = "txtPhone";
    this.txtPhone.OutputFormat = (string) null;
    ((ARControl) this.txtPhone).Size = new SizeF(25f / 16f, 3f / 16f);
    this.txtPhone.Text = "(000) 000-0000";
    this.txtbtmDate.Alignment = (TextAlignment) 2;
    ((ARControl) this.txtbtmDate).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtbtmDate).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtbtmDate).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtbtmDate).Border.TopStyle = (BorderLineStyle) 0;
    this.txtbtmDate.DistinctField = (string) null;
    this.txtbtmDate.Font = new Font("Arial", 10f, System.Drawing.FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtbtmDate.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtbtmDate = this.txtbtmDate;
    object obj48 = componentResourceManager.GetObject("txtbtmDate.Location");
    PointF pointF48 = obj48 != null ? (PointF) obj48 : new PointF();
    ((ARControl) txtbtmDate).Location = pointF48;
    ((ARControl) this.txtbtmDate).Name = "txtbtmDate";
    this.txtbtmDate.OutputFormat = "MM/dd/yyyy";
    ((ARControl) this.txtbtmDate).Size = new SizeF(25f / 16f, 3f / 16f);
    this.DataSource = (object) new SqlDBDataSource("data source=MGASYSTEMS;initial catalog=IMS;persist security info=False;user id=mgasystems", "", 30);
    this.PageSettings.PaperHeight = 11f;
    this.PageSettings.PaperWidth = 8.5f;
    this.PrintWidth = 7f;
    this.Sections.Add((GrapeCity.ActiveReports.SectionReportModel.Section) this.ReportHeader);
    this.Sections.Add((GrapeCity.ActiveReports.SectionReportModel.Section) this.Detail);
    this.Sections.Add((GrapeCity.ActiveReports.SectionReportModel.Section) this.ReportFooter);
    ((ISupportInitialize) this.lblTitle).EndInit();
    ((ISupportInitialize) this.lblDate).EndInit();
    ((ISupportInitialize) this.txtBankAddress).EndInit();
    ((ISupportInitialize) this.txtBankName).EndInit();
    ((ISupportInitialize) this.txtDate).EndInit();
    ((ISupportInitialize) this.Label1).EndInit();
    ((ISupportInitialize) this.txtAmount).EndInit();
    ((ISupportInitialize) this.lblOaddress).EndInit();
    ((ISupportInitialize) this.lblOname).EndInit();
    ((ISupportInitialize) this.lblOacctnum).EndInit();
    ((ISupportInitialize) this.lblOcontact).EndInit();
    ((ISupportInitialize) this.lblOphone).EndInit();
    ((ISupportInitialize) this.lblOcphone).EndInit();
    ((ISupportInitialize) this.lblBaddress).EndInit();
    ((ISupportInitialize) this.lblBname).EndInit();
    ((ISupportInitialize) this.lblBcontact).EndInit();
    ((ISupportInitialize) this.lblBphone).EndInit();
    ((ISupportInitialize) this.lblBContactPhone).EndInit();
    ((ISupportInitialize) this.lblBacct).EndInit();
    ((ISupportInitialize) this.lblBbankname).EndInit();
    ((ISupportInitialize) this.lblBabarouting).EndInit();
    ((ISupportInitialize) this.lblBAddress2).EndInit();
    ((ISupportInitialize) this.lblIbeneficiary).EndInit();
    ((ISupportInitialize) this.lblIbankmemo).EndInit();
    ((ISupportInitialize) this.txtIbeneficiary).EndInit();
    ((ISupportInitialize) this.txtIbankmemo).EndInit();
    ((ISupportInitialize) this.txtBBankName).EndInit();
    ((ISupportInitialize) this.txtBAccountNum).EndInit();
    ((ISupportInitialize) this.txtBAbaNum).EndInit();
    ((ISupportInitialize) this.txtBPhone).EndInit();
    ((ISupportInitialize) this.txtBContact).EndInit();
    ((ISupportInitialize) this.txtBAddress2).EndInit();
    ((ISupportInitialize) this.txtBContactPhone).EndInit();
    ((ISupportInitialize) this.txtBAddress).EndInit();
    ((ISupportInitialize) this.txtOphone).EndInit();
    ((ISupportInitialize) this.txtOcontact).EndInit();
    ((ISupportInitialize) this.txtOcontactphone).EndInit();
    ((ISupportInitialize) this.txtOaccount).EndInit();
    ((ISupportInitialize) this.txtOaddress).EndInit();
    ((ISupportInitialize) this.Label2).EndInit();
    ((ISupportInitialize) this.Label3).EndInit();
    ((ISupportInitialize) this.Label4).EndInit();
    ((ISupportInitialize) this.lblSignature).EndInit();
    ((ISupportInitialize) this.lblAddress).EndInit();
    ((ISupportInitialize) this.lblPhone).EndInit();
    ((ISupportInitialize) this.lblbtmDate).EndInit();
    ((ISupportInitialize) this.txtPhone).EndInit();
    ((ISupportInitialize) this.txtbtmDate).EndInit();
  }
}
