// Decompiled with JetBrains decompiler
// Type: MGASystems.IMS.Accounting.Banking.Check_Standard
// Assembly: MgaSystems.IMS.Accounting.Banking, Version=2.0.0.0, Culture=neutral, PublicKeyToken=e175cb7c4ce15bbd
// MVID: ED5B99DC-3DD2-44AB-BA36-49A11A94937D
// Assembly location: D:\augusta\fortegra\IMS Project\MgaSystems.IMS.Accounting.Banking.dll

using GrapeCity.ActiveReports;
using GrapeCity.ActiveReports.Document.Section;
using GrapeCity.ActiveReports.SectionReportModel;
using System;
using System.ComponentModel;
using System.Drawing;

#nullable disable
namespace MGASystems.IMS.Accounting.Banking;

public class Check_Standard : SectionReport
{
  private Detail Detail;
  private Label Label14;
  private TextBox txtCheckDate2;
  private Label Label7;
  private TextBox txtCheckDate;
  private Label Label1;
  private Label Label2;
  private TextBox txtPayee;
  private Label Label6;
  private TextBox txtMemo;
  private TextBox txtSignature;
  private TextBox txtAmountEnglish;
  private Label Label5;
  private Label Label4;
  private Line Line1;
  private Label Label3;
  private Shape Shape1;
  private Line Line2;
  private Line Line3;
  private Line Line4;
  private Line Line7;
  private TextBox txtCheckNumber;
  private TextBox txtAmountCurrency;
  private TextBox txtE13BCheckNumber;
  private Label Label8;
  private Label Label9;
  private TextBox txtPayee2;
  private Line Line8;
  private Label Label13;
  private Shape Shape2;
  private Line Line12;
  private TextBox txtCheckNumber2;
  private TextBox txtAmountCurrency2;
  private Label lblBankName;
  private Label lblBankAddress;
  private Label Label15;
  private Label Label16;
  private Label lblFractionalTransitNum;
  private SubReport SubReport1;
  private Label transactNum;
  private Label Label17;
  private Label Label18;
  private Label Label19;
  private Line Line14;
  private TextBox txtE13BRoutingNumber;
  private TextBox txtE13BAccountNumber;
  private TextBox txtE13BAmount;

  public Check_Standard() => this.InitializeComponent();

  private void InitializeComponent()
  {
    ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (Check_Standard));
    this.Detail = new Detail();
    this.Label14 = new Label();
    this.txtCheckDate2 = new TextBox();
    this.Label7 = new Label();
    this.txtCheckDate = new TextBox();
    this.Label1 = new Label();
    this.Label2 = new Label();
    this.txtPayee = new TextBox();
    this.Label6 = new Label();
    this.txtMemo = new TextBox();
    this.txtSignature = new TextBox();
    this.txtAmountEnglish = new TextBox();
    this.Label5 = new Label();
    this.Label4 = new Label();
    this.Line1 = new Line();
    this.Label3 = new Label();
    this.Shape1 = new Shape();
    this.Line2 = new Line();
    this.Line3 = new Line();
    this.Line4 = new Line();
    this.Line7 = new Line();
    this.txtCheckNumber = new TextBox();
    this.txtAmountCurrency = new TextBox();
    this.txtE13BCheckNumber = new TextBox();
    this.Label8 = new Label();
    this.Label9 = new Label();
    this.txtPayee2 = new TextBox();
    this.Line8 = new Line();
    this.Label13 = new Label();
    this.Shape2 = new Shape();
    this.Line12 = new Line();
    this.txtCheckNumber2 = new TextBox();
    this.txtAmountCurrency2 = new TextBox();
    this.lblBankName = new Label();
    this.lblBankAddress = new Label();
    this.Label15 = new Label();
    this.Label16 = new Label();
    this.lblFractionalTransitNum = new Label();
    this.SubReport1 = new SubReport();
    this.transactNum = new Label();
    this.Label17 = new Label();
    this.Label18 = new Label();
    this.Label19 = new Label();
    this.Line14 = new Line();
    this.txtE13BRoutingNumber = new TextBox();
    this.txtE13BAccountNumber = new TextBox();
    this.txtE13BAmount = new TextBox();
    ((ISupportInitialize) this.Label14).BeginInit();
    ((ISupportInitialize) this.txtCheckDate2).BeginInit();
    ((ISupportInitialize) this.Label7).BeginInit();
    ((ISupportInitialize) this.txtCheckDate).BeginInit();
    ((ISupportInitialize) this.Label1).BeginInit();
    ((ISupportInitialize) this.Label2).BeginInit();
    ((ISupportInitialize) this.txtPayee).BeginInit();
    ((ISupportInitialize) this.Label6).BeginInit();
    ((ISupportInitialize) this.txtMemo).BeginInit();
    ((ISupportInitialize) this.txtSignature).BeginInit();
    ((ISupportInitialize) this.txtAmountEnglish).BeginInit();
    ((ISupportInitialize) this.Label5).BeginInit();
    ((ISupportInitialize) this.Label4).BeginInit();
    ((ISupportInitialize) this.Label3).BeginInit();
    ((ISupportInitialize) this.txtCheckNumber).BeginInit();
    ((ISupportInitialize) this.txtAmountCurrency).BeginInit();
    ((ISupportInitialize) this.txtE13BCheckNumber).BeginInit();
    ((ISupportInitialize) this.Label8).BeginInit();
    ((ISupportInitialize) this.Label9).BeginInit();
    ((ISupportInitialize) this.txtPayee2).BeginInit();
    ((ISupportInitialize) this.Label13).BeginInit();
    ((ISupportInitialize) this.txtCheckNumber2).BeginInit();
    ((ISupportInitialize) this.txtAmountCurrency2).BeginInit();
    ((ISupportInitialize) this.lblBankName).BeginInit();
    ((ISupportInitialize) this.lblBankAddress).BeginInit();
    ((ISupportInitialize) this.Label15).BeginInit();
    ((ISupportInitialize) this.Label16).BeginInit();
    ((ISupportInitialize) this.lblFractionalTransitNum).BeginInit();
    ((ISupportInitialize) this.transactNum).BeginInit();
    ((ISupportInitialize) this.Label17).BeginInit();
    ((ISupportInitialize) this.Label18).BeginInit();
    ((ISupportInitialize) this.Label19).BeginInit();
    ((ISupportInitialize) this.txtE13BRoutingNumber).BeginInit();
    ((ISupportInitialize) this.txtE13BAccountNumber).BeginInit();
    ((ISupportInitialize) this.txtE13BAmount).BeginInit();
    this.Detail.ColumnSpacing = 0.0f;
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.Detail).Controls.AddRange(new ARControl[46]
    {
      (ARControl) this.Label14,
      (ARControl) this.txtCheckDate2,
      (ARControl) this.Label7,
      (ARControl) this.txtCheckDate,
      (ARControl) this.Label1,
      (ARControl) this.Label2,
      (ARControl) this.txtPayee,
      (ARControl) this.Label6,
      (ARControl) this.txtMemo,
      (ARControl) this.txtSignature,
      (ARControl) this.txtAmountEnglish,
      (ARControl) this.Label5,
      (ARControl) this.Label4,
      (ARControl) this.Line1,
      (ARControl) this.Label3,
      (ARControl) this.Shape1,
      (ARControl) this.Line2,
      (ARControl) this.Line3,
      (ARControl) this.Line4,
      (ARControl) this.Line7,
      (ARControl) this.txtCheckNumber,
      (ARControl) this.txtAmountCurrency,
      (ARControl) this.txtE13BCheckNumber,
      (ARControl) this.Label8,
      (ARControl) this.Label9,
      (ARControl) this.txtPayee2,
      (ARControl) this.Line8,
      (ARControl) this.Label13,
      (ARControl) this.Shape2,
      (ARControl) this.Line12,
      (ARControl) this.txtCheckNumber2,
      (ARControl) this.txtAmountCurrency2,
      (ARControl) this.lblBankName,
      (ARControl) this.lblBankAddress,
      (ARControl) this.Label15,
      (ARControl) this.Label16,
      (ARControl) this.lblFractionalTransitNum,
      (ARControl) this.SubReport1,
      (ARControl) this.transactNum,
      (ARControl) this.Label17,
      (ARControl) this.Label18,
      (ARControl) this.Label19,
      (ARControl) this.Line14,
      (ARControl) this.txtE13BRoutingNumber,
      (ARControl) this.txtE13BAccountNumber,
      (ARControl) this.txtE13BAmount
    });
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.Detail).Height = 10.89444f;
    this.Detail.KeepTogether = true;
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.Detail).Name = "Detail";
    ((ARControl) this.Label14).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label14).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label14).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label14).Border.TopStyle = (BorderLineStyle) 0;
    this.Label14.Font = new Font("Arial", 8f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Label14.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label14.HyperLink = (string) null;
    Label label14 = this.Label14;
    object obj1 = componentResourceManager.GetObject("Label14.Location");
    PointF pointF1 = obj1 != null ? (PointF) obj1 : new PointF();
    ((ARControl) label14).Location = pointF1;
    ((ARControl) this.Label14).Name = "Label14";
    ((ARControl) this.Label14).Size = new SizeF(7f / 16f, 3f / 16f);
    this.Label14.Text = "DATE";
    this.txtCheckDate2.Alignment = (TextAlignment) 1;
    ((ARControl) this.txtCheckDate2).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckDate2).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckDate2).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckDate2).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckDate2).DataField = "CheckDate";
    this.txtCheckDate2.DistinctField = (string) null;
    this.txtCheckDate2.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtCheckDate2.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtCheckDate2 = this.txtCheckDate2;
    object obj2 = componentResourceManager.GetObject("txtCheckDate2.Location");
    PointF pointF2 = obj2 != null ? (PointF) obj2 : new PointF();
    ((ARControl) txtCheckDate2).Location = pointF2;
    ((ARControl) this.txtCheckDate2).Name = "txtCheckDate2";
    this.txtCheckDate2.OutputFormat = "MM/dd/yyyy";
    ((ARControl) this.txtCheckDate2).Size = new SizeF(1.125f, 3f / 16f);
    this.txtCheckDate2.VerticalAlignment = (VerticalTextAlignment) 2;
    ((ARControl) this.Label7).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label7).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label7).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label7).Border.TopStyle = (BorderLineStyle) 0;
    this.Label7.Font = new Font("Arial", 8f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Label7.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label7.HyperLink = (string) null;
    Label label7 = this.Label7;
    object obj3 = componentResourceManager.GetObject("Label7.Location");
    PointF pointF3 = obj3 != null ? (PointF) obj3 : new PointF();
    ((ARControl) label7).Location = pointF3;
    ((ARControl) this.Label7).Name = "Label7";
    ((ARControl) this.Label7).Size = new SizeF(7f / 16f, 3f / 16f);
    this.Label7.Text = "DATE";
    this.Label7.VerticalAlignment = (VerticalTextAlignment) 2;
    this.txtCheckDate.Alignment = (TextAlignment) 1;
    ((ARControl) this.txtCheckDate).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckDate).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckDate).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckDate).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckDate).DataField = "CheckDate";
    this.txtCheckDate.DistinctField = (string) null;
    this.txtCheckDate.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtCheckDate.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtCheckDate = this.txtCheckDate;
    object obj4 = componentResourceManager.GetObject("txtCheckDate.Location");
    PointF pointF4 = obj4 != null ? (PointF) obj4 : new PointF();
    ((ARControl) txtCheckDate).Location = pointF4;
    ((ARControl) this.txtCheckDate).Name = "txtCheckDate";
    this.txtCheckDate.OutputFormat = "MM/dd/yyyy";
    ((ARControl) this.txtCheckDate).Size = new SizeF(1.25f, 3f / 16f);
    this.txtCheckDate.VerticalAlignment = (VerticalTextAlignment) 2;
    ((ARControl) this.Label1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label1).Border.TopStyle = (BorderLineStyle) 0;
    this.Label1.Font = new Font("Arial", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Label1.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label1.HyperLink = (string) null;
    Label label1 = this.Label1;
    object obj5 = componentResourceManager.GetObject("Label1.Location");
    PointF pointF5 = obj5 != null ? (PointF) obj5 : new PointF();
    ((ARControl) label1).Location = pointF5;
    ((ARControl) this.Label1).Name = "Label1";
    ((ARControl) this.Label1).Size = new SizeF(0.125f, 3f / 16f);
    this.Label1.Text = "P";
    ((ARControl) this.Label2).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label2).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label2).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label2).Border.TopStyle = (BorderLineStyle) 0;
    this.Label2.Font = new Font("Arial", 7f);
    this.Label2.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label2.HyperLink = (string) null;
    Label label2 = this.Label2;
    object obj6 = componentResourceManager.GetObject("Label2.Location");
    PointF pointF6 = obj6 != null ? (PointF) obj6 : new PointF();
    ((ARControl) label2).Location = pointF6;
    ((ARControl) this.Label2).Name = "Label2";
    ((ARControl) this.Label2).Size = new SizeF(1.375f, 0.125f);
    this.Label2.Text = "AY TO THE ORDER OF";
    ((ARControl) this.txtPayee).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtPayee).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtPayee).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtPayee).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtPayee).DataField = "Payee";
    this.txtPayee.DistinctField = (string) null;
    this.txtPayee.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtPayee.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtPayee = this.txtPayee;
    object obj7 = componentResourceManager.GetObject("txtPayee.Location");
    PointF pointF7 = obj7 != null ? (PointF) obj7 : new PointF();
    ((ARControl) txtPayee).Location = pointF7;
    ((ARControl) this.txtPayee).Name = "txtPayee";
    this.txtPayee.OutputFormat = (string) null;
    ((ARControl) this.txtPayee).Size = new SizeF(3.9875f, 3f / 16f);
    this.txtPayee.VerticalAlignment = (VerticalTextAlignment) 1;
    this.txtPayee.WordWrap = false;
    ((ARControl) this.Label6).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label6).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label6).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label6).Border.TopStyle = (BorderLineStyle) 0;
    this.Label6.Font = new Font("Arial", 6f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.Label6.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label6.HyperLink = (string) null;
    Label label6 = this.Label6;
    object obj8 = componentResourceManager.GetObject("Label6.Location");
    PointF pointF8 = obj8 != null ? (PointF) obj8 : new PointF();
    ((ARControl) label6).Location = pointF8;
    ((ARControl) this.Label6).Name = "Label6";
    ((ARControl) this.Label6).Size = new SizeF(0.625f, 0.125f);
    this.Label6.Text = "FOR";
    ((ARControl) this.txtMemo).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtMemo).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtMemo).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtMemo).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtMemo).DataField = "CHECKMEMO";
    this.txtMemo.DistinctField = (string) null;
    this.txtMemo.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtMemo.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtMemo = this.txtMemo;
    object obj9 = componentResourceManager.GetObject("txtMemo.Location");
    PointF pointF9 = obj9 != null ? (PointF) obj9 : new PointF();
    ((ARControl) txtMemo).Location = pointF9;
    ((ARControl) this.txtMemo).Name = "txtMemo";
    this.txtMemo.OutputFormat = (string) null;
    ((ARControl) this.txtMemo).Size = new SizeF(3f, 0.25f);
    this.txtMemo.VerticalAlignment = (VerticalTextAlignment) 2;
    this.txtSignature.Alignment = (TextAlignment) 1;
    ((ARControl) this.txtSignature).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtSignature).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtSignature).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtSignature).Border.TopStyle = (BorderLineStyle) 0;
    this.txtSignature.DistinctField = (string) null;
    this.txtSignature.Font = new Font("Arial", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.txtSignature.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtSignature = this.txtSignature;
    object obj10 = componentResourceManager.GetObject("txtSignature.Location");
    PointF pointF10 = obj10 != null ? (PointF) obj10 : new PointF();
    ((ARControl) txtSignature).Location = pointF10;
    ((ARControl) this.txtSignature).Name = "txtSignature";
    this.txtSignature.OutputFormat = (string) null;
    ((ARControl) this.txtSignature).Size = new SizeF(2.993056f, 7f / 16f);
    this.txtSignature.VerticalAlignment = (VerticalTextAlignment) 2;
    ((ARControl) this.txtAmountEnglish).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmountEnglish).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmountEnglish).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmountEnglish).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmountEnglish).DataField = "Amountenglish";
    this.txtAmountEnglish.DistinctField = (string) null;
    this.txtAmountEnglish.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtAmountEnglish.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtAmountEnglish = this.txtAmountEnglish;
    object obj11 = componentResourceManager.GetObject("txtAmountEnglish.Location");
    PointF pointF11 = obj11 != null ? (PointF) obj11 : new PointF();
    ((ARControl) txtAmountEnglish).Location = pointF11;
    this.txtAmountEnglish.MultiLine = false;
    ((ARControl) this.txtAmountEnglish).Name = "txtAmountEnglish";
    this.txtAmountEnglish.OutputFormat = (string) null;
    ((ARControl) this.txtAmountEnglish).Size = new SizeF(7.443056f, 3f / 16f);
    this.txtAmountEnglish.Text = "Thiry-Five Thousand and 20 dollars and 70/100";
    this.txtAmountEnglish.WordWrap = false;
    this.Label5.Alignment = (TextAlignment) 2;
    ((ARControl) this.Label5).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label5).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label5).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label5).Border.TopStyle = (BorderLineStyle) 0;
    this.Label5.Font = new Font("Arial", 6f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.Label5.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label5.HyperLink = (string) null;
    Label label5 = this.Label5;
    object obj12 = componentResourceManager.GetObject("Label5.Location");
    PointF pointF12 = obj12 != null ? (PointF) obj12 : new PointF();
    ((ARControl) label5).Location = pointF12;
    ((ARControl) this.Label5).Name = "Label5";
    ((ARControl) this.Label5).Size = new SizeF(1.611111f, 3f / 16f);
    this.Label5.Text = "AUTHORIZED SIGNATURE";
    this.Label4.Alignment = (TextAlignment) 2;
    ((ARControl) this.Label4).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label4).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label4).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label4).Border.TopStyle = (BorderLineStyle) 0;
    this.Label4.Font = new Font("Arial", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Label4.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label4.HyperLink = (string) null;
    Label label4 = this.Label4;
    object obj13 = componentResourceManager.GetObject("Label4.Location");
    PointF pointF13 = obj13 != null ? (PointF) obj13 : new PointF();
    ((ARControl) label4).Location = pointF13;
    ((ARControl) this.Label4).Name = "Label4";
    ((ARControl) this.Label4).Size = new SizeF(9f / 16f, 3f / 16f);
    this.Label4.Text = "Dollars";
    ((ARControl) this.Label4).Visible = false;
    this.Line1.Border.BottomStyle = (BorderLineStyle) 0;
    this.Line1.Border.LeftStyle = (BorderLineStyle) 0;
    this.Line1.Border.RightStyle = (BorderLineStyle) 0;
    this.Line1.Border.TopStyle = (BorderLineStyle) 0;
    this.Line1.LineWeight = 1f;
    ((ARControl) this.Line1).Name = "Line1";
    this.Line1.X1 = 1.3625f;
    this.Line1.X2 = 6.175f;
    this.Line1.Y1 = 1.4365f;
    this.Line1.Y2 = 365f * (float) Math.PI / 798f;
    ((ARControl) this.Label3).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label3).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label3).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label3).Border.TopStyle = (BorderLineStyle) 0;
    this.Label3.Font = new Font("Arial", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Label3.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label3.HyperLink = (string) null;
    Label label3 = this.Label3;
    object obj14 = componentResourceManager.GetObject("Label3.Location");
    PointF pointF14 = obj14 != null ? (PointF) obj14 : new PointF();
    ((ARControl) label3).Location = pointF14;
    ((ARControl) this.Label3).Name = "Label3";
    ((ARControl) this.Label3).Size = new SizeF(3f / 16f, 3f / 16f);
    this.Label3.Text = "$";
    ((ARControl) this.Shape1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Shape1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Shape1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Shape1).Border.TopStyle = (BorderLineStyle) 0;
    Shape shape1 = this.Shape1;
    object obj15 = componentResourceManager.GetObject("Shape1.Location");
    PointF pointF15 = obj15 != null ? (PointF) obj15 : new PointF();
    ((ARControl) shape1).Location = pointF15;
    ((ARControl) this.Shape1).Name = "Shape1";
    ((ARControl) this.Shape1).Size = new SizeF(2.125f, 0.25f);
    this.Line2.Border.BottomStyle = (BorderLineStyle) 0;
    this.Line2.Border.LeftStyle = (BorderLineStyle) 0;
    this.Line2.Border.RightStyle = (BorderLineStyle) 0;
    this.Line2.Border.TopStyle = (BorderLineStyle) 0;
    this.Line2.LineWeight = 1f;
    ((ARControl) this.Line2).Name = "Line2";
    this.Line2.X1 = 7.381945f;
    this.Line2.X2 = 0.1944444f;
    this.Line2.Y1 = 1.75f;
    this.Line2.Y2 = 1.75f;
    this.Line3.Border.BottomStyle = (BorderLineStyle) 0;
    this.Line3.Border.LeftStyle = (BorderLineStyle) 0;
    this.Line3.Border.RightStyle = (BorderLineStyle) 0;
    this.Line3.Border.TopStyle = (BorderLineStyle) 0;
    this.Line3.LineWeight = 1f;
    ((ARControl) this.Line3).Name = "Line3";
    this.Line3.X1 = 4.694445f;
    this.Line3.X2 = 123f / 16f;
    this.Line3.Y1 = 2.875f;
    this.Line3.Y2 = 2.875f;
    this.Line4.Border.BottomStyle = (BorderLineStyle) 0;
    this.Line4.Border.LeftStyle = (BorderLineStyle) 0;
    this.Line4.Border.RightStyle = (BorderLineStyle) 0;
    this.Line4.Border.TopStyle = (BorderLineStyle) 0;
    this.Line4.LineWeight = 1f;
    ((ARControl) this.Line4).Name = "Line4";
    this.Line4.X1 = 57f / 16f;
    this.Line4.X2 = 0.5f;
    this.Line4.Y1 = 47f / 16f;
    this.Line4.Y2 = 47f / 16f;
    this.Line7.Border.BottomStyle = (BorderLineStyle) 0;
    this.Line7.Border.LeftStyle = (BorderLineStyle) 0;
    this.Line7.Border.RightStyle = (BorderLineStyle) 0;
    this.Line7.Border.TopStyle = (BorderLineStyle) 0;
    this.Line7.LineWeight = 1f;
    ((ARControl) this.Line7).Name = "Line7";
    this.Line7.X1 = 103f / 16f;
    this.Line7.X2 = 123f / 16f;
    this.Line7.Y1 = 1f;
    this.Line7.Y2 = 1f;
    this.txtCheckNumber.Alignment = (TextAlignment) 2;
    ((ARControl) this.txtCheckNumber).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckNumber).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckNumber).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckNumber).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckNumber).DataField = "CheckNum";
    this.txtCheckNumber.DistinctField = (string) null;
    this.txtCheckNumber.Font = new Font("Arial", 11f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.txtCheckNumber.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtCheckNumber = this.txtCheckNumber;
    object obj16 = componentResourceManager.GetObject("txtCheckNumber.Location");
    PointF pointF16 = obj16 != null ? (PointF) obj16 : new PointF();
    ((ARControl) txtCheckNumber).Location = pointF16;
    ((ARControl) this.txtCheckNumber).Name = "txtCheckNumber";
    this.txtCheckNumber.OutputFormat = (string) null;
    ((ARControl) this.txtCheckNumber).Size = new SizeF(29f / 16f, 0.25f);
    this.txtAmountCurrency.Alignment = (TextAlignment) 2;
    ((ARControl) this.txtAmountCurrency).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmountCurrency).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmountCurrency).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmountCurrency).Border.TopStyle = (BorderLineStyle) 0;
    this.txtAmountCurrency.DistinctField = (string) null;
    this.txtAmountCurrency.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtAmountCurrency.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtAmountCurrency = this.txtAmountCurrency;
    object obj17 = componentResourceManager.GetObject("txtAmountCurrency.Location");
    PointF pointF17 = obj17 != null ? (PointF) obj17 : new PointF();
    ((ARControl) txtAmountCurrency).Location = pointF17;
    ((ARControl) this.txtAmountCurrency).Name = "txtAmountCurrency";
    this.txtAmountCurrency.OutputFormat = (string) null;
    ((ARControl) this.txtAmountCurrency).Size = new SizeF(2f, 3f / 16f);
    this.txtE13BCheckNumber.Alignment = (TextAlignment) 2;
    ((ARControl) this.txtE13BCheckNumber).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtE13BCheckNumber).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtE13BCheckNumber).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtE13BCheckNumber).Border.TopStyle = (BorderLineStyle) 0;
    this.txtE13BCheckNumber.DistinctField = (string) null;
    this.txtE13BCheckNumber.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtE13BCheckNumber.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtE13BcheckNumber = this.txtE13BCheckNumber;
    object obj18 = componentResourceManager.GetObject("txtE13BCheckNumber.Location");
    PointF pointF18 = obj18 != null ? (PointF) obj18 : new PointF();
    ((ARControl) txtE13BcheckNumber).Location = pointF18;
    ((ARControl) this.txtE13BCheckNumber).Name = "txtE13BCheckNumber";
    this.txtE13BCheckNumber.OutputFormat = (string) null;
    ((ARControl) this.txtE13BCheckNumber).Size = new SizeF(37f / 16f, 0.25f);
    this.txtE13BCheckNumber.Text = "TextBox1";
    this.txtE13BCheckNumber.VerticalAlignment = (VerticalTextAlignment) 1;
    ((ARControl) this.Label8).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label8).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label8).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label8).Border.TopStyle = (BorderLineStyle) 0;
    this.Label8.Font = new Font("Arial", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Label8.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label8.HyperLink = (string) null;
    Label label8 = this.Label8;
    object obj19 = componentResourceManager.GetObject("Label8.Location");
    PointF pointF19 = obj19 != null ? (PointF) obj19 : new PointF();
    ((ARControl) label8).Location = pointF19;
    ((ARControl) this.Label8).Name = "Label8";
    ((ARControl) this.Label8).Size = new SizeF(0.125f, 3f / 16f);
    this.Label8.Text = "P";
    ((ARControl) this.Label9).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label9).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label9).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label9).Border.TopStyle = (BorderLineStyle) 0;
    this.Label9.Font = new Font("Arial", 7f);
    this.Label9.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label9.HyperLink = (string) null;
    Label label9 = this.Label9;
    object obj20 = componentResourceManager.GetObject("Label9.Location");
    PointF pointF20 = obj20 != null ? (PointF) obj20 : new PointF();
    ((ARControl) label9).Location = pointF20;
    ((ARControl) this.Label9).Name = "Label9";
    ((ARControl) this.Label9).Size = new SizeF(1.375f, 0.125f);
    this.Label9.Text = "AY TO THE ORDER OF";
    ((ARControl) this.txtPayee2).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtPayee2).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtPayee2).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtPayee2).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtPayee2).DataField = "Payee";
    this.txtPayee2.DistinctField = (string) null;
    this.txtPayee2.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtPayee2.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtPayee2 = this.txtPayee2;
    object obj21 = componentResourceManager.GetObject("txtPayee2.Location");
    PointF pointF21 = obj21 != null ? (PointF) obj21 : new PointF();
    ((ARControl) txtPayee2).Location = pointF21;
    ((ARControl) this.txtPayee2).Name = "txtPayee2";
    this.txtPayee2.OutputFormat = (string) null;
    ((ARControl) this.txtPayee2).Size = new SizeF(63f / 16f, 3f / 16f);
    this.txtPayee2.VerticalAlignment = (VerticalTextAlignment) 1;
    this.Line8.Border.BottomStyle = (BorderLineStyle) 0;
    this.Line8.Border.LeftStyle = (BorderLineStyle) 0;
    this.Line8.Border.RightStyle = (BorderLineStyle) 0;
    this.Line8.Border.TopStyle = (BorderLineStyle) 0;
    this.Line8.LineWeight = 1f;
    ((ARControl) this.Line8).Name = "Line8";
    this.Line8.X1 = 1.3f;
    this.Line8.X2 = 6.1125f;
    this.Line8.Y1 = 8.249f;
    this.Line8.Y2 = 8.249445f;
    ((ARControl) this.Label13).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label13).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label13).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label13).Border.TopStyle = (BorderLineStyle) 0;
    this.Label13.Font = new Font("Arial", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Label13.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label13.HyperLink = (string) null;
    Label label13 = this.Label13;
    object obj22 = componentResourceManager.GetObject("Label13.Location");
    PointF pointF22 = obj22 != null ? (PointF) obj22 : new PointF();
    ((ARControl) label13).Location = pointF22;
    ((ARControl) this.Label13).Name = "Label13";
    ((ARControl) this.Label13).Size = new SizeF(3f / 16f, 3f / 16f);
    this.Label13.Text = "$";
    ((ARControl) this.Shape2).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Shape2).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Shape2).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Shape2).Border.TopStyle = (BorderLineStyle) 0;
    Shape shape2 = this.Shape2;
    object obj23 = componentResourceManager.GetObject("Shape2.Location");
    PointF pointF23 = obj23 != null ? (PointF) obj23 : new PointF();
    ((ARControl) shape2).Location = pointF23;
    ((ARControl) this.Shape2).Name = "Shape2";
    ((ARControl) this.Shape2).Size = new SizeF(2.125f, 0.25f);
    this.Line12.Border.BottomStyle = (BorderLineStyle) 0;
    this.Line12.Border.LeftStyle = (BorderLineStyle) 0;
    this.Line12.Border.RightStyle = (BorderLineStyle) 0;
    this.Line12.Border.TopStyle = (BorderLineStyle) 0;
    this.Line12.LineWeight = 1f;
    ((ARControl) this.Line12).Name = "Line12";
    this.Line12.X1 = 6.375f;
    this.Line12.X2 = 7.625f;
    this.Line12.Y1 = 125f / 16f;
    this.Line12.Y2 = 125f / 16f;
    this.txtCheckNumber2.Alignment = (TextAlignment) 2;
    ((ARControl) this.txtCheckNumber2).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckNumber2).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckNumber2).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckNumber2).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtCheckNumber2).DataField = "CheckNum";
    this.txtCheckNumber2.DistinctField = (string) null;
    this.txtCheckNumber2.Font = new Font("Arial", 11f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.txtCheckNumber2.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtCheckNumber2 = this.txtCheckNumber2;
    object obj24 = componentResourceManager.GetObject("txtCheckNumber2.Location");
    PointF pointF24 = obj24 != null ? (PointF) obj24 : new PointF();
    ((ARControl) txtCheckNumber2).Location = pointF24;
    ((ARControl) this.txtCheckNumber2).Name = "txtCheckNumber2";
    this.txtCheckNumber2.OutputFormat = (string) null;
    ((ARControl) this.txtCheckNumber2).Size = new SizeF(29f / 16f, 0.25f);
    this.txtCheckNumber2.VerticalAlignment = (VerticalTextAlignment) 1;
    this.txtAmountCurrency2.Alignment = (TextAlignment) 2;
    ((ARControl) this.txtAmountCurrency2).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmountCurrency2).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmountCurrency2).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtAmountCurrency2).Border.TopStyle = (BorderLineStyle) 0;
    this.txtAmountCurrency2.DistinctField = (string) null;
    this.txtAmountCurrency2.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtAmountCurrency2.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtAmountCurrency2 = this.txtAmountCurrency2;
    object obj25 = componentResourceManager.GetObject("txtAmountCurrency2.Location");
    PointF pointF25 = obj25 != null ? (PointF) obj25 : new PointF();
    ((ARControl) txtAmountCurrency2).Location = pointF25;
    ((ARControl) this.txtAmountCurrency2).Name = "txtAmountCurrency2";
    this.txtAmountCurrency2.OutputFormat = (string) null;
    ((ARControl) this.txtAmountCurrency2).Size = new SizeF(2f, 3f / 16f);
    ((ARControl) this.lblBankName).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBankName).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBankName).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBankName).Border.TopStyle = (BorderLineStyle) 0;
    this.lblBankName.Font = new Font("Arial", 8f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.lblBankName.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblBankName.HyperLink = (string) null;
    Label lblBankName = this.lblBankName;
    object obj26 = componentResourceManager.GetObject("lblBankName.Location");
    PointF pointF26 = obj26 != null ? (PointF) obj26 : new PointF();
    ((ARControl) lblBankName).Location = pointF26;
    ((ARControl) this.lblBankName).Name = "lblBankName";
    ((ARControl) this.lblBankName).Size = new SizeF(4.625f, 0.125f);
    this.lblBankName.Text = "";
    ((ARControl) this.lblBankAddress).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBankAddress).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBankAddress).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblBankAddress).Border.TopStyle = (BorderLineStyle) 0;
    this.lblBankAddress.Font = new Font("Arial", 8f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.lblBankAddress.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblBankAddress.HyperLink = (string) null;
    Label lblBankAddress = this.lblBankAddress;
    object obj27 = componentResourceManager.GetObject("lblBankAddress.Location");
    PointF pointF27 = obj27 != null ? (PointF) obj27 : new PointF();
    ((ARControl) lblBankAddress).Location = pointF27;
    ((ARControl) this.lblBankAddress).Name = "lblBankAddress";
    ((ARControl) this.lblBankAddress).Size = new SizeF(3.25f, 0.75f);
    this.lblBankAddress.Text = "";
    ((ARControl) this.Label15).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label15).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label15).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label15).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label15).DataField = "MGANAME";
    this.Label15.Font = new Font("Arial", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Label15.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label15.HyperLink = (string) null;
    Label label15 = this.Label15;
    object obj28 = componentResourceManager.GetObject("Label15.Location");
    PointF pointF28 = obj28 != null ? (PointF) obj28 : new PointF();
    ((ARControl) label15).Location = pointF28;
    ((ARControl) this.Label15).Name = "Label15";
    ((ARControl) this.Label15).Size = new SizeF(3.75f, 0.25f);
    this.Label15.Text = "";
    ((ARControl) this.Label16).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label16).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label16).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label16).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label16).DataField = "MGAADDRESS";
    this.Label16.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.Label16.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label16.HyperLink = (string) null;
    Label label16 = this.Label16;
    object obj29 = componentResourceManager.GetObject("Label16.Location");
    PointF pointF29 = obj29 != null ? (PointF) obj29 : new PointF();
    ((ARControl) label16).Location = pointF29;
    ((ARControl) this.Label16).Name = "Label16";
    ((ARControl) this.Label16).Size = new SizeF(3.125f, 0.7f);
    this.Label16.Text = "";
    this.lblFractionalTransitNum.Alignment = (TextAlignment) 1;
    ((ARControl) this.lblFractionalTransitNum).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblFractionalTransitNum).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblFractionalTransitNum).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblFractionalTransitNum).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblFractionalTransitNum).DataField = "TRANSITNUM";
    this.lblFractionalTransitNum.Font = new Font("Arial", 7f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.lblFractionalTransitNum.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblFractionalTransitNum.HyperLink = (string) null;
    Label fractionalTransitNum = this.lblFractionalTransitNum;
    object obj30 = componentResourceManager.GetObject("lblFractionalTransitNum.Location");
    PointF pointF30 = obj30 != null ? (PointF) obj30 : new PointF();
    ((ARControl) fractionalTransitNum).Location = pointF30;
    ((ARControl) this.lblFractionalTransitNum).Name = "lblFractionalTransitNum";
    ((ARControl) this.lblFractionalTransitNum).Size = new SizeF(19f / 16f, 3f / 16f);
    this.lblFractionalTransitNum.Text = "";
    this.lblFractionalTransitNum.VerticalAlignment = (VerticalTextAlignment) 1;
    ((ARControl) this.SubReport1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.SubReport1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.SubReport1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.SubReport1).Border.TopStyle = (BorderLineStyle) 0;
    this.SubReport1.CanGrow = false;
    this.SubReport1.CanShrink = false;
    this.SubReport1.CloseBorder = false;
    this.SubReport1.DataField = "transactnum";
    SubReport subReport1 = this.SubReport1;
    object obj31 = componentResourceManager.GetObject("SubReport1.Location");
    PointF pointF31 = obj31 != null ? (PointF) obj31 : new PointF();
    ((ARControl) subReport1).Location = pointF31;
    ((ARControl) this.SubReport1).Name = "SubReport1";
    this.SubReport1.Report = (SectionReport) null;
    ((ARControl) this.SubReport1).Size = new SizeF(125f / 16f, 3.375f);
    ((ARControl) this.transactNum).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.transactNum).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.transactNum).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.transactNum).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.transactNum).DataField = "transactnum";
    this.transactNum.Font = new Font("Arial", 10f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.transactNum.ForeColor = Color.FromArgb(0, 0, 0);
    this.transactNum.HyperLink = (string) null;
    Label transactNum = this.transactNum;
    object obj32 = componentResourceManager.GetObject("transactNum.Location");
    PointF pointF32 = obj32 != null ? (PointF) obj32 : new PointF();
    ((ARControl) transactNum).Location = pointF32;
    ((ARControl) this.transactNum).Name = "transactNum";
    ((ARControl) this.transactNum).Size = new SizeF(9f / 16f, 0.0f);
    this.transactNum.Text = "";
    ((ARControl) this.transactNum).Visible = false;
    ((ARControl) this.Label17).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label17).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label17).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label17).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label17).DataField = "MGANAME";
    this.Label17.Font = new Font("Arial", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Label17.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label17.HyperLink = (string) null;
    Label label17 = this.Label17;
    object obj33 = componentResourceManager.GetObject("Label17.Location");
    PointF pointF33 = obj33 != null ? (PointF) obj33 : new PointF();
    ((ARControl) label17).Location = pointF33;
    ((ARControl) this.Label17).Name = "Label17";
    ((ARControl) this.Label17).Size = new SizeF(3.75f, 0.25f);
    this.Label17.Text = "";
    ((ARControl) this.Label18).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label18).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label18).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label18).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label18).DataField = "MGAADDRESS";
    this.Label18.Font = new Font("Arial", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.Label18.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label18.HyperLink = (string) null;
    Label label18 = this.Label18;
    object obj34 = componentResourceManager.GetObject("Label18.Location");
    PointF pointF34 = obj34 != null ? (PointF) obj34 : new PointF();
    ((ARControl) label18).Location = pointF34;
    ((ARControl) this.Label18).Name = "Label18";
    ((ARControl) this.Label18).Size = new SizeF(3.125f, 0.7f);
    this.Label18.Text = "";
    this.Label19.Alignment = (TextAlignment) 1;
    ((ARControl) this.Label19).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label19).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label19).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label19).Border.TopStyle = (BorderLineStyle) 0;
    this.Label19.Font = new Font("Arial", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Label19.ForeColor = Color.Gray;
    this.Label19.HyperLink = (string) null;
    Label label19 = this.Label19;
    object obj35 = componentResourceManager.GetObject("Label19.Location");
    PointF pointF35 = obj35 != null ? (PointF) obj35 : new PointF();
    ((ARControl) label19).Location = pointF35;
    ((ARControl) this.Label19).Name = "Label19";
    ((ARControl) this.Label19).Size = new SizeF(121f / 16f, 5f / 16f);
    this.Label19.Text = "Non-Transferable. This Is Not A Check.";
    this.Label19.VerticalAlignment = (VerticalTextAlignment) 1;
    this.Line14.Border.BottomStyle = (BorderLineStyle) 0;
    this.Line14.Border.LeftStyle = (BorderLineStyle) 0;
    this.Line14.Border.RightStyle = (BorderLineStyle) 0;
    this.Line14.Border.TopStyle = (BorderLineStyle) 0;
    this.Line14.LineColor = Color.FromArgb(105, 105, 105);
    this.Line14.LineStyle = (LineStyle) 2;
    this.Line14.LineWeight = 1f;
    ((ARControl) this.Line14).Name = "Line14";
    this.Line14.X1 = 123f / 16f;
    this.Line14.X2 = 0.125f;
    this.Line14.Y1 = 57f / 16f;
    this.Line14.Y2 = 57f / 16f;
    ((ARControl) this.txtE13BRoutingNumber).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtE13BRoutingNumber).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtE13BRoutingNumber).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtE13BRoutingNumber).Border.TopStyle = (BorderLineStyle) 0;
    this.txtE13BRoutingNumber.DistinctField = (string) null;
    this.txtE13BRoutingNumber.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtE13BRoutingNumber.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox e13BroutingNumber = this.txtE13BRoutingNumber;
    object obj36 = componentResourceManager.GetObject("txtE13BRoutingNumber.Location");
    PointF pointF36 = obj36 != null ? (PointF) obj36 : new PointF();
    ((ARControl) e13BroutingNumber).Location = pointF36;
    ((ARControl) this.txtE13BRoutingNumber).Name = "txtE13BRoutingNumber";
    this.txtE13BRoutingNumber.OutputFormat = (string) null;
    ((ARControl) this.txtE13BRoutingNumber).Size = new SizeF(1.625f, 0.25f);
    this.txtE13BRoutingNumber.Text = "TextBox1";
    this.txtE13BRoutingNumber.VerticalAlignment = (VerticalTextAlignment) 1;
    ((ARControl) this.txtE13BAccountNumber).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtE13BAccountNumber).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtE13BAccountNumber).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtE13BAccountNumber).Border.TopStyle = (BorderLineStyle) 0;
    this.txtE13BAccountNumber.DistinctField = (string) null;
    this.txtE13BAccountNumber.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtE13BAccountNumber.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox e13BaccountNumber = this.txtE13BAccountNumber;
    object obj37 = componentResourceManager.GetObject("txtE13BAccountNumber.Location");
    PointF pointF37 = obj37 != null ? (PointF) obj37 : new PointF();
    ((ARControl) e13BaccountNumber).Location = pointF37;
    ((ARControl) this.txtE13BAccountNumber).Name = "txtE13BAccountNumber";
    this.txtE13BAccountNumber.OutputFormat = (string) null;
    ((ARControl) this.txtE13BAccountNumber).Size = new SizeF(27f / 16f, 0.25f);
    this.txtE13BAccountNumber.Text = "TextBox1";
    this.txtE13BAccountNumber.VerticalAlignment = (VerticalTextAlignment) 1;
    this.txtE13BAmount.Alignment = (TextAlignment) 2;
    ((ARControl) this.txtE13BAmount).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtE13BAmount).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtE13BAmount).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtE13BAmount).Border.TopStyle = (BorderLineStyle) 0;
    this.txtE13BAmount.DistinctField = (string) null;
    this.txtE13BAmount.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.txtE13BAmount.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtE13Bamount = this.txtE13BAmount;
    object obj38 = componentResourceManager.GetObject("txtE13BAmount.Location");
    PointF pointF38 = obj38 != null ? (PointF) obj38 : new PointF();
    ((ARControl) txtE13Bamount).Location = pointF38;
    ((ARControl) this.txtE13BAmount).Name = "txtE13BAmount";
    this.txtE13BAmount.OutputFormat = (string) null;
    ((ARControl) this.txtE13BAmount).Size = new SizeF(1.375f, 0.25f);
    this.txtE13BAmount.Text = "TextBox1";
    this.txtE13BAmount.VerticalAlignment = (VerticalTextAlignment) 1;
    ((ARControl) this.txtE13BAmount).Visible = false;
    this.PageSettings.DefaultPaperSize = false;
    this.PageSettings.Gutter = 0.1f;
    this.PageSettings.Margins.Bottom = 0.1f;
    this.PageSettings.Margins.Left = 0.1f;
    this.PageSettings.Margins.Right = 0.1f;
    this.PageSettings.Margins.Top = 0.1f;
    this.PageSettings.PaperHeight = 11f;
    this.PageSettings.PaperName = "";
    this.PageSettings.PaperWidth = 8.5f;
    this.PrintWidth = 8.145833f;
    this.Sections.Add((GrapeCity.ActiveReports.SectionReportModel.Section) this.Detail);
    ((ISupportInitialize) this.Label14).EndInit();
    ((ISupportInitialize) this.txtCheckDate2).EndInit();
    ((ISupportInitialize) this.Label7).EndInit();
    ((ISupportInitialize) this.txtCheckDate).EndInit();
    ((ISupportInitialize) this.Label1).EndInit();
    ((ISupportInitialize) this.Label2).EndInit();
    ((ISupportInitialize) this.txtPayee).EndInit();
    ((ISupportInitialize) this.Label6).EndInit();
    ((ISupportInitialize) this.txtMemo).EndInit();
    ((ISupportInitialize) this.txtSignature).EndInit();
    ((ISupportInitialize) this.txtAmountEnglish).EndInit();
    ((ISupportInitialize) this.Label5).EndInit();
    ((ISupportInitialize) this.Label4).EndInit();
    ((ISupportInitialize) this.Label3).EndInit();
    ((ISupportInitialize) this.txtCheckNumber).EndInit();
    ((ISupportInitialize) this.txtAmountCurrency).EndInit();
    ((ISupportInitialize) this.txtE13BCheckNumber).EndInit();
    ((ISupportInitialize) this.Label8).EndInit();
    ((ISupportInitialize) this.Label9).EndInit();
    ((ISupportInitialize) this.txtPayee2).EndInit();
    ((ISupportInitialize) this.Label13).EndInit();
    ((ISupportInitialize) this.txtCheckNumber2).EndInit();
    ((ISupportInitialize) this.txtAmountCurrency2).EndInit();
    ((ISupportInitialize) this.lblBankName).EndInit();
    ((ISupportInitialize) this.lblBankAddress).EndInit();
    ((ISupportInitialize) this.Label15).EndInit();
    ((ISupportInitialize) this.Label16).EndInit();
    ((ISupportInitialize) this.lblFractionalTransitNum).EndInit();
    ((ISupportInitialize) this.transactNum).EndInit();
    ((ISupportInitialize) this.Label17).EndInit();
    ((ISupportInitialize) this.Label18).EndInit();
    ((ISupportInitialize) this.Label19).EndInit();
    ((ISupportInitialize) this.txtE13BRoutingNumber).EndInit();
    ((ISupportInitialize) this.txtE13BAccountNumber).EndInit();
    ((ISupportInitialize) this.txtE13BAmount).EndInit();
  }
}
