// Decompiled with JetBrains decompiler
// Type: MGASystems.IMS.Reporting.rptUnderwritingLocation
// Assembly: MgaSystems.IMS.Reporting, Version=2.0.0.0, Culture=neutral, PublicKeyToken=e175cb7c4ce15bbd
// MVID: D0217E27-C87B-4FD0-8041-819EA70A118B
// Assembly location: D:\augusta\fortegra\IMS Project\MgaSystems.IMS.Reporting.dll

using GrapeCity.ActiveReports;
using GrapeCity.ActiveReports.Document.Section;
using GrapeCity.ActiveReports.SectionReportModel;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Runtime.CompilerServices;

#nullable disable
namespace MGASystems.IMS.Reporting;

public class rptUnderwritingLocation : SectionReport
{
  private Label Label17;
  private TextBox TextBox5;
  private TextBox txtSaleAmount;
  private TextBox LocationElevators1;
  private TextBox MercLroArea1;
  private TextBox TextBox46;
  private TextBox LocationSqFootage1;
  private TextBox NumberOfStories1;
  private TextBox NumberOfUnits1;
  private TextBox Occupancy1;
  private TextBox LocationHeatingYear1;
  private TextBox LocationRoofingYear1;
  private TextBox LocationWiringYear1;
  private TextBox LocationPlumbingYear1;
  private TextBox LocationConstructionType1;
  private CheckBox CheckBox3;
  private Label Label35;
  private Label Label33;
  private Label Label32;
  private Label Label31;
  private Label Label30;
  private Label Label29;
  private Label Label28;
  private Label Label27;
  private Label Label26;
  private Label Label25;
  private Label Label24;
  private Label Label23;
  private Label Label22;
  private Label Label21;
  private Label Label20;
  private Label Label19;
  private Label Label18;
  private CheckBox CheckBox1;
  private CheckBox CheckBox2;
  private Label lblSplitter;

  public rptUnderwritingLocation(DataView dvLocations, bool showSplitter)
  {
    this.InitializeComponent();
    this.DataSource = (object) dvLocations;
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.gfSplitter).Visible = showSplitter;
  }

  private void InitializeComponent()
  {
    ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (rptUnderwritingLocation));
    this.Detail = new Detail();
    this.ghSplitter = new GroupHeader();
    this.gfSplitter = new GroupFooter();
    this.ghLocation = new GroupHeader();
    this.gfLocation = new GroupFooter();
    this.Label17 = new Label();
    this.TextBox5 = new TextBox();
    this.txtSaleAmount = new TextBox();
    this.LocationElevators1 = new TextBox();
    this.MercLroArea1 = new TextBox();
    this.TextBox46 = new TextBox();
    this.LocationSqFootage1 = new TextBox();
    this.NumberOfStories1 = new TextBox();
    this.NumberOfUnits1 = new TextBox();
    this.Occupancy1 = new TextBox();
    this.LocationHeatingYear1 = new TextBox();
    this.LocationRoofingYear1 = new TextBox();
    this.LocationWiringYear1 = new TextBox();
    this.LocationPlumbingYear1 = new TextBox();
    this.LocationConstructionType1 = new TextBox();
    this.CheckBox3 = new CheckBox();
    this.Label35 = new Label();
    this.Label33 = new Label();
    this.Label32 = new Label();
    this.Label31 = new Label();
    this.Label30 = new Label();
    this.Label29 = new Label();
    this.Label28 = new Label();
    this.Label27 = new Label();
    this.Label26 = new Label();
    this.Label25 = new Label();
    this.Label24 = new Label();
    this.Label23 = new Label();
    this.Label22 = new Label();
    this.Label21 = new Label();
    this.Label20 = new Label();
    this.Label19 = new Label();
    this.Label18 = new Label();
    this.CheckBox1 = new CheckBox();
    this.CheckBox2 = new CheckBox();
    this.lblSplitter = new Label();
    ((ISupportInitialize) this.Label17).BeginInit();
    ((ISupportInitialize) this.TextBox5).BeginInit();
    ((ISupportInitialize) this.txtSaleAmount).BeginInit();
    ((ISupportInitialize) this.LocationElevators1).BeginInit();
    ((ISupportInitialize) this.MercLroArea1).BeginInit();
    ((ISupportInitialize) this.TextBox46).BeginInit();
    ((ISupportInitialize) this.LocationSqFootage1).BeginInit();
    ((ISupportInitialize) this.NumberOfStories1).BeginInit();
    ((ISupportInitialize) this.NumberOfUnits1).BeginInit();
    ((ISupportInitialize) this.Occupancy1).BeginInit();
    ((ISupportInitialize) this.LocationHeatingYear1).BeginInit();
    ((ISupportInitialize) this.LocationRoofingYear1).BeginInit();
    ((ISupportInitialize) this.LocationWiringYear1).BeginInit();
    ((ISupportInitialize) this.LocationPlumbingYear1).BeginInit();
    ((ISupportInitialize) this.LocationConstructionType1).BeginInit();
    ((ISupportInitialize) this.CheckBox3).BeginInit();
    ((ISupportInitialize) this.Label35).BeginInit();
    ((ISupportInitialize) this.Label33).BeginInit();
    ((ISupportInitialize) this.Label32).BeginInit();
    ((ISupportInitialize) this.Label31).BeginInit();
    ((ISupportInitialize) this.Label30).BeginInit();
    ((ISupportInitialize) this.Label29).BeginInit();
    ((ISupportInitialize) this.Label28).BeginInit();
    ((ISupportInitialize) this.Label27).BeginInit();
    ((ISupportInitialize) this.Label26).BeginInit();
    ((ISupportInitialize) this.Label25).BeginInit();
    ((ISupportInitialize) this.Label24).BeginInit();
    ((ISupportInitialize) this.Label23).BeginInit();
    ((ISupportInitialize) this.Label22).BeginInit();
    ((ISupportInitialize) this.Label21).BeginInit();
    ((ISupportInitialize) this.Label20).BeginInit();
    ((ISupportInitialize) this.Label19).BeginInit();
    ((ISupportInitialize) this.Label18).BeginInit();
    ((ISupportInitialize) this.CheckBox1).BeginInit();
    ((ISupportInitialize) this.CheckBox2).BeginInit();
    ((ISupportInitialize) this.lblSplitter).BeginInit();
    this.Detail.ColumnSpacing = 0.0f;
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.Detail).Controls.AddRange(new ARControl[33]
    {
      (ARControl) this.txtSaleAmount,
      (ARControl) this.LocationElevators1,
      (ARControl) this.MercLroArea1,
      (ARControl) this.TextBox46,
      (ARControl) this.LocationSqFootage1,
      (ARControl) this.NumberOfStories1,
      (ARControl) this.NumberOfUnits1,
      (ARControl) this.Occupancy1,
      (ARControl) this.LocationHeatingYear1,
      (ARControl) this.LocationRoofingYear1,
      (ARControl) this.LocationWiringYear1,
      (ARControl) this.LocationPlumbingYear1,
      (ARControl) this.LocationConstructionType1,
      (ARControl) this.CheckBox3,
      (ARControl) this.Label35,
      (ARControl) this.Label33,
      (ARControl) this.Label32,
      (ARControl) this.Label31,
      (ARControl) this.Label30,
      (ARControl) this.Label29,
      (ARControl) this.Label28,
      (ARControl) this.Label27,
      (ARControl) this.Label26,
      (ARControl) this.Label25,
      (ARControl) this.Label24,
      (ARControl) this.Label23,
      (ARControl) this.Label22,
      (ARControl) this.Label21,
      (ARControl) this.Label20,
      (ARControl) this.Label19,
      (ARControl) this.Label18,
      (ARControl) this.CheckBox1,
      (ARControl) this.CheckBox2
    });
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.Detail).Height = 1.5f;
    this.Detail.KeepTogether = true;
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.Detail).Name = "Detail";
    this.ghSplitter.Height = 0.0f;
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.ghSplitter).Name = "ghSplitter";
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.gfSplitter).Controls.AddRange(new ARControl[1]
    {
      (ARControl) this.lblSplitter
    });
    this.gfSplitter.Height = 0.1034722f;
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.gfSplitter).Name = "gfSplitter";
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.ghLocation).Controls.AddRange(new ARControl[2]
    {
      (ARControl) this.Label17,
      (ARControl) this.TextBox5
    });
    this.ghLocation.DataField = "LocationAddress";
    this.ghLocation.Height = 0.25f;
    this.ghLocation.KeepTogether = true;
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.ghLocation).Name = "ghLocation";
    this.gfLocation.Height = 0.0f;
    ((GrapeCity.ActiveReports.SectionReportModel.Section) this.gfLocation).Name = "gfLocation";
    ((ARControl) this.Label17).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label17).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label17).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label17).Border.TopStyle = (BorderLineStyle) 0;
    this.Label17.Font = new Font("Arial", 8f);
    this.Label17.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label17.HyperLink = (string) null;
    Label label17 = this.Label17;
    object obj1 = componentResourceManager.GetObject("Label17.Location");
    PointF pointF1 = obj1 != null ? (PointF) obj1 : new PointF();
    ((ARControl) label17).Location = pointF1;
    ((ARControl) this.Label17).Name = "Label17";
    ((ARControl) this.Label17).Size = new SizeF(1.75f, 3f / 16f);
    this.Label17.Text = "LOCATION:";
    ((ARControl) this.TextBox5).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.TextBox5).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.TextBox5).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.TextBox5).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.TextBox5).DataField = "LocationAddress";
    this.TextBox5.DistinctField = (string) null;
    this.TextBox5.Font = new Font("Arial", 8f);
    this.TextBox5.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox textBox5 = this.TextBox5;
    object obj2 = componentResourceManager.GetObject("TextBox5.Location");
    PointF pointF2 = obj2 != null ? (PointF) obj2 : new PointF();
    ((ARControl) textBox5).Location = pointF2;
    ((ARControl) this.TextBox5).Name = "TextBox5";
    this.TextBox5.OutputFormat = (string) null;
    ((ARControl) this.TextBox5).Size = new SizeF(6f, 3f / 16f);
    ((ARControl) this.txtSaleAmount).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtSaleAmount).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtSaleAmount).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtSaleAmount).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.txtSaleAmount).DataField = "SaleAmount";
    this.txtSaleAmount.DistinctField = (string) null;
    this.txtSaleAmount.Font = new Font("Arial", 8f);
    this.txtSaleAmount.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox txtSaleAmount = this.txtSaleAmount;
    object obj3 = componentResourceManager.GetObject("txtSaleAmount.Location");
    PointF pointF3 = obj3 != null ? (PointF) obj3 : new PointF();
    ((ARControl) txtSaleAmount).Location = pointF3;
    ((ARControl) this.txtSaleAmount).Name = "txtSaleAmount";
    this.txtSaleAmount.OutputFormat = "$#,##0.00;($#,##0.00)";
    ((ARControl) this.txtSaleAmount).Size = new SizeF(31f / 16f, 3f / 16f);
    this.txtSaleAmount.Text = " ";
    ((ARControl) this.LocationElevators1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationElevators1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationElevators1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationElevators1).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationElevators1).DataField = "LocationElevators";
    this.LocationElevators1.DistinctField = (string) null;
    this.LocationElevators1.Font = new Font("Arial", 8f);
    this.LocationElevators1.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox locationElevators1 = this.LocationElevators1;
    object obj4 = componentResourceManager.GetObject("LocationElevators1.Location");
    PointF pointF4 = obj4 != null ? (PointF) obj4 : new PointF();
    ((ARControl) locationElevators1).Location = pointF4;
    ((ARControl) this.LocationElevators1).Name = "LocationElevators1";
    this.LocationElevators1.OutputFormat = (string) null;
    ((ARControl) this.LocationElevators1).Size = new SizeF(5f / 16f, 3f / 16f);
    this.LocationElevators1.Text = " ";
    ((ARControl) this.MercLroArea1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.MercLroArea1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.MercLroArea1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.MercLroArea1).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.MercLroArea1).DataField = "MercLroArea";
    this.MercLroArea1.DistinctField = (string) null;
    this.MercLroArea1.Font = new Font("Arial", 8f);
    this.MercLroArea1.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox mercLroArea1 = this.MercLroArea1;
    object obj5 = componentResourceManager.GetObject("MercLroArea1.Location");
    PointF pointF5 = obj5 != null ? (PointF) obj5 : new PointF();
    ((ARControl) mercLroArea1).Location = pointF5;
    ((ARControl) this.MercLroArea1).Name = "MercLroArea1";
    this.MercLroArea1.OutputFormat = (string) null;
    ((ARControl) this.MercLroArea1).Size = new SizeF(0.75f, 3f / 16f);
    this.MercLroArea1.Text = " ";
    ((ARControl) this.TextBox46).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.TextBox46).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.TextBox46).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.TextBox46).Border.TopStyle = (BorderLineStyle) 0;
    this.TextBox46.DistinctField = "NumberOfMercs";
    this.TextBox46.Font = new Font("Arial", 8f);
    this.TextBox46.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox textBox46 = this.TextBox46;
    object obj6 = componentResourceManager.GetObject("TextBox46.Location");
    PointF pointF6 = obj6 != null ? (PointF) obj6 : new PointF();
    ((ARControl) textBox46).Location = pointF6;
    ((ARControl) this.TextBox46).Name = "TextBox46";
    this.TextBox46.OutputFormat = (string) null;
    ((ARControl) this.TextBox46).Size = new SizeF(2.75f, 3f / 16f);
    this.TextBox46.Text = " ";
    ((ARControl) this.LocationSqFootage1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationSqFootage1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationSqFootage1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationSqFootage1).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationSqFootage1).DataField = "LocationSqFootage";
    this.LocationSqFootage1.DistinctField = (string) null;
    this.LocationSqFootage1.Font = new Font("Arial", 8f);
    this.LocationSqFootage1.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox locationSqFootage1 = this.LocationSqFootage1;
    object obj7 = componentResourceManager.GetObject("LocationSqFootage1.Location");
    PointF pointF7 = obj7 != null ? (PointF) obj7 : new PointF();
    ((ARControl) locationSqFootage1).Location = pointF7;
    ((ARControl) this.LocationSqFootage1).Name = "LocationSqFootage1";
    this.LocationSqFootage1.OutputFormat = (string) null;
    ((ARControl) this.LocationSqFootage1).Size = new SizeF(7f / 16f, 3f / 16f);
    this.LocationSqFootage1.Text = " ";
    ((ARControl) this.NumberOfStories1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.NumberOfStories1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.NumberOfStories1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.NumberOfStories1).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.NumberOfStories1).DataField = "NumberOfStories";
    this.NumberOfStories1.DistinctField = (string) null;
    this.NumberOfStories1.Font = new Font("Arial", 8f);
    this.NumberOfStories1.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox numberOfStories1 = this.NumberOfStories1;
    object obj8 = componentResourceManager.GetObject("NumberOfStories1.Location");
    PointF pointF8 = obj8 != null ? (PointF) obj8 : new PointF();
    ((ARControl) numberOfStories1).Location = pointF8;
    ((ARControl) this.NumberOfStories1).Name = "NumberOfStories1";
    this.NumberOfStories1.OutputFormat = (string) null;
    ((ARControl) this.NumberOfStories1).Size = new SizeF(1.75f, 3f / 16f);
    this.NumberOfStories1.Text = " ";
    ((ARControl) this.NumberOfUnits1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.NumberOfUnits1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.NumberOfUnits1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.NumberOfUnits1).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.NumberOfUnits1).DataField = "NumberOfUnits";
    this.NumberOfUnits1.DistinctField = (string) null;
    this.NumberOfUnits1.Font = new Font("Arial", 8f);
    this.NumberOfUnits1.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox numberOfUnits1 = this.NumberOfUnits1;
    object obj9 = componentResourceManager.GetObject("NumberOfUnits1.Location");
    PointF pointF9 = obj9 != null ? (PointF) obj9 : new PointF();
    ((ARControl) numberOfUnits1).Location = pointF9;
    ((ARControl) this.NumberOfUnits1).Name = "NumberOfUnits1";
    this.NumberOfUnits1.OutputFormat = (string) null;
    ((ARControl) this.NumberOfUnits1).Size = new SizeF(0.625f, 3f / 16f);
    this.NumberOfUnits1.Text = " ";
    ((ARControl) this.Occupancy1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Occupancy1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Occupancy1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Occupancy1).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.Occupancy1).DataField = "Occupancy";
    this.Occupancy1.DistinctField = (string) null;
    this.Occupancy1.Font = new Font("Arial", 8f);
    this.Occupancy1.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox occupancy1 = this.Occupancy1;
    object obj10 = componentResourceManager.GetObject("Occupancy1.Location");
    PointF pointF10 = obj10 != null ? (PointF) obj10 : new PointF();
    ((ARControl) occupancy1).Location = pointF10;
    ((ARControl) this.Occupancy1).Name = "Occupancy1";
    this.Occupancy1.OutputFormat = (string) null;
    ((ARControl) this.Occupancy1).Size = new SizeF(6f, 3f / 16f);
    this.Occupancy1.Text = " ";
    ((ARControl) this.LocationHeatingYear1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationHeatingYear1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationHeatingYear1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationHeatingYear1).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationHeatingYear1).DataField = "LocationHeatingYear";
    this.LocationHeatingYear1.DistinctField = (string) null;
    this.LocationHeatingYear1.Font = new Font("Arial", 8f);
    this.LocationHeatingYear1.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox locationHeatingYear1 = this.LocationHeatingYear1;
    object obj11 = componentResourceManager.GetObject("LocationHeatingYear1.Location");
    PointF pointF11 = obj11 != null ? (PointF) obj11 : new PointF();
    ((ARControl) locationHeatingYear1).Location = pointF11;
    ((ARControl) this.LocationHeatingYear1).Name = "LocationHeatingYear1";
    this.LocationHeatingYear1.OutputFormat = (string) null;
    ((ARControl) this.LocationHeatingYear1).Size = new SizeF(5f / 16f, 3f / 16f);
    this.LocationHeatingYear1.Text = " ";
    ((ARControl) this.LocationRoofingYear1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationRoofingYear1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationRoofingYear1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationRoofingYear1).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationRoofingYear1).DataField = "LocationRoofingYear";
    this.LocationRoofingYear1.DistinctField = (string) null;
    this.LocationRoofingYear1.Font = new Font("Arial", 8f);
    this.LocationRoofingYear1.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox locationRoofingYear1 = this.LocationRoofingYear1;
    object obj12 = componentResourceManager.GetObject("LocationRoofingYear1.Location");
    PointF pointF12 = obj12 != null ? (PointF) obj12 : new PointF();
    ((ARControl) locationRoofingYear1).Location = pointF12;
    ((ARControl) this.LocationRoofingYear1).Name = "LocationRoofingYear1";
    this.LocationRoofingYear1.OutputFormat = (string) null;
    ((ARControl) this.LocationRoofingYear1).Size = new SizeF(5f / 16f, 3f / 16f);
    ((ARControl) this.LocationWiringYear1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationWiringYear1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationWiringYear1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationWiringYear1).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationWiringYear1).DataField = "LocationWiringYear";
    this.LocationWiringYear1.DistinctField = (string) null;
    this.LocationWiringYear1.Font = new Font("Arial", 8f);
    this.LocationWiringYear1.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox locationWiringYear1 = this.LocationWiringYear1;
    object obj13 = componentResourceManager.GetObject("LocationWiringYear1.Location");
    PointF pointF13 = obj13 != null ? (PointF) obj13 : new PointF();
    ((ARControl) locationWiringYear1).Location = pointF13;
    ((ARControl) this.LocationWiringYear1).Name = "LocationWiringYear1";
    this.LocationWiringYear1.OutputFormat = (string) null;
    ((ARControl) this.LocationWiringYear1).Size = new SizeF(5f / 16f, 3f / 16f);
    this.LocationWiringYear1.Text = " ";
    ((ARControl) this.LocationPlumbingYear1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationPlumbingYear1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationPlumbingYear1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationPlumbingYear1).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationPlumbingYear1).DataField = "LocationPlumbingYear";
    this.LocationPlumbingYear1.DistinctField = (string) null;
    this.LocationPlumbingYear1.Font = new Font("Arial", 8f);
    this.LocationPlumbingYear1.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox locationPlumbingYear1 = this.LocationPlumbingYear1;
    object obj14 = componentResourceManager.GetObject("LocationPlumbingYear1.Location");
    PointF pointF14 = obj14 != null ? (PointF) obj14 : new PointF();
    ((ARControl) locationPlumbingYear1).Location = pointF14;
    ((ARControl) this.LocationPlumbingYear1).Name = "LocationPlumbingYear1";
    this.LocationPlumbingYear1.OutputFormat = (string) null;
    ((ARControl) this.LocationPlumbingYear1).Size = new SizeF(5f / 16f, 3f / 16f);
    ((ARControl) this.LocationConstructionType1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationConstructionType1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationConstructionType1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationConstructionType1).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.LocationConstructionType1).DataField = "LocationConstructionType";
    this.LocationConstructionType1.DistinctField = (string) null;
    this.LocationConstructionType1.Font = new Font("Arial", 8f);
    this.LocationConstructionType1.ForeColor = Color.FromArgb(0, 0, 0);
    TextBox constructionType1 = this.LocationConstructionType1;
    object obj15 = componentResourceManager.GetObject("LocationConstructionType1.Location");
    PointF pointF15 = obj15 != null ? (PointF) obj15 : new PointF();
    ((ARControl) constructionType1).Location = pointF15;
    ((ARControl) this.LocationConstructionType1).Name = "LocationConstructionType1";
    this.LocationConstructionType1.OutputFormat = (string) null;
    ((ARControl) this.LocationConstructionType1).Size = new SizeF(1.75f, 3f / 16f);
    this.LocationConstructionType1.Text = " ";
    ((ARControl) this.CheckBox3).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.CheckBox3).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.CheckBox3).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.CheckBox3).Border.TopStyle = (BorderLineStyle) 0;
    ((ARControl) this.CheckBox3).DataField = "HasSales";
    this.CheckBox3.Font = new Font("Arial", 8f);
    this.CheckBox3.ForeColor = Color.FromArgb(0, 0, 0);
    CheckBox checkBox3 = this.CheckBox3;
    object obj16 = componentResourceManager.GetObject("CheckBox3.Location");
    PointF pointF16 = obj16 != null ? (PointF) obj16 : new PointF();
    ((ARControl) checkBox3).Location = pointF16;
    ((ARControl) this.CheckBox3).Name = "CheckBox3";
    ((ARControl) this.CheckBox3).Size = new SizeF(0.75f, 3f / 16f);
    this.CheckBox3.Text = "SALES";
    this.Label35.Alignment = (TextAlignment) 2;
    ((ARControl) this.Label35).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label35).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label35).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label35).Border.TopStyle = (BorderLineStyle) 0;
    this.Label35.Font = new Font("Arial", 8f, FontStyle.Bold);
    this.Label35.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label35.HyperLink = (string) null;
    Label label35 = this.Label35;
    object obj17 = componentResourceManager.GetObject("Label35.Location");
    PointF pointF17 = obj17 != null ? (PointF) obj17 : new PointF();
    ((ARControl) label35).Location = pointF17;
    ((ARControl) this.Label35).Name = "Label35";
    ((ARControl) this.Label35).Size = new SizeF(7f / 16f, 3f / 16f);
    this.Label35.Text = "sq. ft.";
    ((ARControl) this.Label33).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label33).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label33).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label33).Border.TopStyle = (BorderLineStyle) 0;
    this.Label33.Font = new Font("Arial", 8f, FontStyle.Bold);
    this.Label33.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label33.HyperLink = (string) null;
    Label label33 = this.Label33;
    object obj18 = componentResourceManager.GetObject("Label33.Location");
    PointF pointF18 = obj18 != null ? (PointF) obj18 : new PointF();
    ((ARControl) label33).Location = pointF18;
    ((ARControl) this.Label33).Name = "Label33";
    ((ARControl) this.Label33).Size = new SizeF(7f / 16f, 3f / 16f);
    this.Label33.Text = "sq. ft.";
    ((ARControl) this.Label32).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label32).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label32).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label32).Border.TopStyle = (BorderLineStyle) 0;
    this.Label32.Font = new Font("Arial", 8f);
    this.Label32.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label32.HyperLink = (string) null;
    Label label32 = this.Label32;
    object obj19 = componentResourceManager.GetObject("Label32.Location");
    PointF pointF19 = obj19 != null ? (PointF) obj19 : new PointF();
    ((ARControl) label32).Location = pointF19;
    ((ARControl) this.Label32).Name = "Label32";
    ((ARControl) this.Label32).Size = new SizeF(1.5f, 3f / 16f);
    this.Label32.Text = "MERC/LRO AREA:";
    ((ARControl) this.Label31).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label31).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label31).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label31).Border.TopStyle = (BorderLineStyle) 0;
    this.Label31.Font = new Font("Arial", 8f);
    this.Label31.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label31.HyperLink = (string) null;
    Label label31 = this.Label31;
    object obj20 = componentResourceManager.GetObject("Label31.Location");
    PointF pointF20 = obj20 != null ? (PointF) obj20 : new PointF();
    ((ARControl) label31).Location = pointF20;
    ((ARControl) this.Label31).Name = "Label31";
    ((ARControl) this.Label31).Size = new SizeF(1.5f, 3f / 16f);
    this.Label31.Text = "NUMBER OF MERCS:";
    ((ARControl) this.Label30).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label30).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label30).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label30).Border.TopStyle = (BorderLineStyle) 0;
    this.Label30.Font = new Font("Arial", 8f);
    this.Label30.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label30.HyperLink = (string) null;
    Label label30 = this.Label30;
    object obj21 = componentResourceManager.GetObject("Label30.Location");
    PointF pointF21 = obj21 != null ? (PointF) obj21 : new PointF();
    ((ARControl) label30).Location = pointF21;
    ((ARControl) this.Label30).Name = "Label30";
    ((ARControl) this.Label30).Size = new SizeF(13f / 16f, 3f / 16f);
    this.Label30.Text = "# OF ELEV:";
    ((ARControl) this.Label29).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label29).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label29).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label29).Border.TopStyle = (BorderLineStyle) 0;
    this.Label29.Font = new Font("Arial", 8f);
    this.Label29.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label29.HyperLink = (string) null;
    Label label29 = this.Label29;
    object obj22 = componentResourceManager.GetObject("Label29.Location");
    PointF pointF22 = obj22 != null ? (PointF) obj22 : new PointF();
    ((ARControl) label29).Location = pointF22;
    ((ARControl) this.Label29).Name = "Label29";
    ((ARControl) this.Label29).Size = new SizeF(1.75f, 3f / 16f);
    this.Label29.Text = "NUMBER OF STORIES:";
    ((ARControl) this.Label28).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label28).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label28).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label28).Border.TopStyle = (BorderLineStyle) 0;
    this.Label28.Font = new Font("Arial", 8f);
    this.Label28.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label28.HyperLink = (string) null;
    Label label28 = this.Label28;
    object obj23 = componentResourceManager.GetObject("Label28.Location");
    PointF pointF23 = obj23 != null ? (PointF) obj23 : new PointF();
    ((ARControl) label28).Location = pointF23;
    ((ARControl) this.Label28).Name = "Label28";
    ((ARControl) this.Label28).Size = new SizeF(1.75f, 3f / 16f);
    this.Label28.Text = "TOTAL BUILDING AREA:";
    ((ARControl) this.Label27).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label27).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label27).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label27).Border.TopStyle = (BorderLineStyle) 0;
    this.Label27.Font = new Font("Arial", 8f);
    this.Label27.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label27.HyperLink = (string) null;
    Label label27 = this.Label27;
    object obj24 = componentResourceManager.GetObject("Label27.Location");
    PointF pointF24 = obj24 != null ? (PointF) obj24 : new PointF();
    ((ARControl) label27).Location = pointF24;
    ((ARControl) this.Label27).Name = "Label27";
    ((ARControl) this.Label27).Size = new SizeF(1.75f, 3f / 16f);
    this.Label27.Text = "NUMBER OF UNITS:";
    ((ARControl) this.Label26).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label26).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label26).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label26).Border.TopStyle = (BorderLineStyle) 0;
    this.Label26.Font = new Font("Arial", 8f);
    this.Label26.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label26.HyperLink = (string) null;
    Label label26 = this.Label26;
    object obj25 = componentResourceManager.GetObject("Label26.Location");
    PointF pointF25 = obj25 != null ? (PointF) obj25 : new PointF();
    ((ARControl) label26).Location = pointF25;
    ((ARControl) this.Label26).Name = "Label26";
    ((ARControl) this.Label26).Size = new SizeF(1.75f, 3f / 16f);
    this.Label26.Text = "OCCUPANCY:";
    ((ARControl) this.Label25).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label25).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label25).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label25).Border.TopStyle = (BorderLineStyle) 0;
    this.Label25.Font = new Font("Arial", 8f);
    this.Label25.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label25.HyperLink = (string) null;
    Label label25 = this.Label25;
    object obj26 = componentResourceManager.GetObject("Label25.Location");
    PointF pointF26 = obj26 != null ? (PointF) obj26 : new PointF();
    ((ARControl) label25).Location = pointF26;
    ((ARControl) this.Label25).Name = "Label25";
    ((ARControl) this.Label25).Size = new SizeF(7f / 16f, 3f / 16f);
    this.Label25.Text = "- HEAT";
    ((ARControl) this.Label24).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label24).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label24).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label24).Border.TopStyle = (BorderLineStyle) 0;
    this.Label24.Font = new Font("Arial", 8f);
    this.Label24.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label24.HyperLink = (string) null;
    Label label24 = this.Label24;
    object obj27 = componentResourceManager.GetObject("Label24.Location");
    PointF pointF27 = obj27 != null ? (PointF) obj27 : new PointF();
    ((ARControl) label24).Location = pointF27;
    ((ARControl) this.Label24).Name = "Label24";
    ((ARControl) this.Label24).Size = new SizeF(0.75f, 3f / 16f);
    this.Label24.Text = "- ELECTRIC";
    ((ARControl) this.Label23).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label23).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label23).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label23).Border.TopStyle = (BorderLineStyle) 0;
    this.Label23.Font = new Font("Arial", 8f);
    this.Label23.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label23.HyperLink = (string) null;
    Label label23 = this.Label23;
    object obj28 = componentResourceManager.GetObject("Label23.Location");
    PointF pointF28 = obj28 != null ? (PointF) obj28 : new PointF();
    ((ARControl) label23).Location = pointF28;
    ((ARControl) this.Label23).Name = "Label23";
    ((ARControl) this.Label23).Size = new SizeF(9f / 16f, 3f / 16f);
    this.Label23.Text = "- OTHER";
    ((ARControl) this.Label22).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label22).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label22).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label22).Border.TopStyle = (BorderLineStyle) 0;
    this.Label22.Font = new Font("Arial", 8f);
    this.Label22.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label22.HyperLink = (string) null;
    Label label22 = this.Label22;
    object obj29 = componentResourceManager.GetObject("Label22.Location");
    PointF pointF29 = obj29 != null ? (PointF) obj29 : new PointF();
    ((ARControl) label22).Location = pointF29;
    ((ARControl) this.Label22).Name = "Label22";
    ((ARControl) this.Label22).Size = new SizeF(7f / 16f, 3f / 16f);
    this.Label22.Text = "- ROOF";
    ((ARControl) this.Label21).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label21).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label21).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label21).Border.TopStyle = (BorderLineStyle) 0;
    this.Label21.Font = new Font("Arial", 8f);
    this.Label21.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label21.HyperLink = (string) null;
    Label label21 = this.Label21;
    object obj30 = componentResourceManager.GetObject("Label21.Location");
    PointF pointF30 = obj30 != null ? (PointF) obj30 : new PointF();
    ((ARControl) label21).Location = pointF30;
    ((ARControl) this.Label21).Name = "Label21";
    ((ARControl) this.Label21).Size = new SizeF(0.75f, 3f / 16f);
    this.Label21.Text = "- PLUMBING";
    ((ARControl) this.Label20).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label20).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label20).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label20).Border.TopStyle = (BorderLineStyle) 0;
    this.Label20.Font = new Font("Arial", 8f);
    this.Label20.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label20.HyperLink = (string) null;
    Label label20 = this.Label20;
    object obj31 = componentResourceManager.GetObject("Label20.Location");
    PointF pointF31 = obj31 != null ? (PointF) obj31 : new PointF();
    ((ARControl) label20).Location = pointF31;
    ((ARControl) this.Label20).Name = "Label20";
    ((ARControl) this.Label20).Size = new SizeF(27f / 16f, 3f / 16f);
    this.Label20.Text = "BLDG SPRINKLERED:";
    ((ARControl) this.Label19).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label19).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label19).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label19).Border.TopStyle = (BorderLineStyle) 0;
    this.Label19.Font = new Font("Arial", 8f);
    this.Label19.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label19.HyperLink = (string) null;
    Label label19 = this.Label19;
    object obj32 = componentResourceManager.GetObject("Label19.Location");
    PointF pointF32 = obj32 != null ? (PointF) obj32 : new PointF();
    ((ARControl) label19).Location = pointF32;
    ((ARControl) this.Label19).Name = "Label19";
    ((ARControl) this.Label19).Size = new SizeF(1.75f, 3f / 16f);
    this.Label19.Text = "UPDATES:";
    ((ARControl) this.Label18).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label18).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label18).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.Label18).Border.TopStyle = (BorderLineStyle) 0;
    this.Label18.Font = new Font("Arial", 8f);
    this.Label18.ForeColor = Color.FromArgb(0, 0, 0);
    this.Label18.HyperLink = (string) null;
    Label label18 = this.Label18;
    object obj33 = componentResourceManager.GetObject("Label18.Location");
    PointF pointF33 = obj33 != null ? (PointF) obj33 : new PointF();
    ((ARControl) label18).Location = pointF33;
    ((ARControl) this.Label18).Name = "Label18";
    ((ARControl) this.Label18).Size = new SizeF(1.75f, 3f / 16f);
    this.Label18.Text = "CONSTRUCTION:";
    ((ARControl) this.CheckBox1).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.CheckBox1).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.CheckBox1).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.CheckBox1).Border.TopStyle = (BorderLineStyle) 0;
    this.CheckBox1.Font = new Font("Arial", 8f);
    this.CheckBox1.ForeColor = Color.FromArgb(0, 0, 0);
    CheckBox checkBox1 = this.CheckBox1;
    object obj34 = componentResourceManager.GetObject("CheckBox1.Location");
    PointF pointF34 = obj34 != null ? (PointF) obj34 : new PointF();
    ((ARControl) checkBox1).Location = pointF34;
    ((ARControl) this.CheckBox1).Name = "CheckBox1";
    ((ARControl) this.CheckBox1).Size = new SizeF(9f / 16f, 3f / 16f);
    this.CheckBox1.Text = "YES";
    ((ARControl) this.CheckBox2).Border.BottomStyle = (BorderLineStyle) 0;
    ((ARControl) this.CheckBox2).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.CheckBox2).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.CheckBox2).Border.TopStyle = (BorderLineStyle) 0;
    this.CheckBox2.Font = new Font("Arial", 8f);
    this.CheckBox2.ForeColor = Color.FromArgb(0, 0, 0);
    CheckBox checkBox2 = this.CheckBox2;
    object obj35 = componentResourceManager.GetObject("CheckBox2.Location");
    PointF pointF35 = obj35 != null ? (PointF) obj35 : new PointF();
    ((ARControl) checkBox2).Location = pointF35;
    ((ARControl) this.CheckBox2).Name = "CheckBox2";
    ((ARControl) this.CheckBox2).Size = new SizeF(9f / 16f, 3f / 16f);
    this.CheckBox2.Text = "NO";
    ((ARControl) this.lblSplitter).Border.BottomStyle = (BorderLineStyle) 12;
    ((ARControl) this.lblSplitter).Border.LeftStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblSplitter).Border.RightStyle = (BorderLineStyle) 0;
    ((ARControl) this.lblSplitter).Border.TopStyle = (BorderLineStyle) 0;
    this.lblSplitter.Font = new Font("Arial", 10f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.lblSplitter.ForeColor = Color.FromArgb(0, 0, 0);
    this.lblSplitter.HyperLink = (string) null;
    Label lblSplitter = this.lblSplitter;
    object obj36 = componentResourceManager.GetObject("lblSplitter.Location");
    PointF pointF36 = obj36 != null ? (PointF) obj36 : new PointF();
    ((ARControl) lblSplitter).Location = pointF36;
    ((ARControl) this.lblSplitter).Name = "lblSplitter";
    ((ARControl) this.lblSplitter).Size = new SizeF(129f / 16f, 1f / 16f);
    this.lblSplitter.Text = "";
    this.PageSettings.Margins.Bottom = 0.3f;
    this.PageSettings.Margins.Left = 0.3f;
    this.PageSettings.Margins.Right = 0.3f;
    this.PageSettings.Margins.Top = 0.3f;
    this.PageSettings.PaperHeight = 11f;
    this.PageSettings.PaperWidth = 8.5f;
    this.PrintWidth = 7.9f;
    this.Sections.Add((GrapeCity.ActiveReports.SectionReportModel.Section) this.ghSplitter);
    this.Sections.Add((GrapeCity.ActiveReports.SectionReportModel.Section) this.ghLocation);
    this.Sections.Add((GrapeCity.ActiveReports.SectionReportModel.Section) this.Detail);
    this.Sections.Add((GrapeCity.ActiveReports.SectionReportModel.Section) this.gfLocation);
    this.Sections.Add((GrapeCity.ActiveReports.SectionReportModel.Section) this.gfSplitter);
    ((ISupportInitialize) this.Label17).EndInit();
    ((ISupportInitialize) this.TextBox5).EndInit();
    ((ISupportInitialize) this.txtSaleAmount).EndInit();
    ((ISupportInitialize) this.LocationElevators1).EndInit();
    ((ISupportInitialize) this.MercLroArea1).EndInit();
    ((ISupportInitialize) this.TextBox46).EndInit();
    ((ISupportInitialize) this.LocationSqFootage1).EndInit();
    ((ISupportInitialize) this.NumberOfStories1).EndInit();
    ((ISupportInitialize) this.NumberOfUnits1).EndInit();
    ((ISupportInitialize) this.Occupancy1).EndInit();
    ((ISupportInitialize) this.LocationHeatingYear1).EndInit();
    ((ISupportInitialize) this.LocationRoofingYear1).EndInit();
    ((ISupportInitialize) this.LocationWiringYear1).EndInit();
    ((ISupportInitialize) this.LocationPlumbingYear1).EndInit();
    ((ISupportInitialize) this.LocationConstructionType1).EndInit();
    ((ISupportInitialize) this.CheckBox3).EndInit();
    ((ISupportInitialize) this.Label35).EndInit();
    ((ISupportInitialize) this.Label33).EndInit();
    ((ISupportInitialize) this.Label32).EndInit();
    ((ISupportInitialize) this.Label31).EndInit();
    ((ISupportInitialize) this.Label30).EndInit();
    ((ISupportInitialize) this.Label29).EndInit();
    ((ISupportInitialize) this.Label28).EndInit();
    ((ISupportInitialize) this.Label27).EndInit();
    ((ISupportInitialize) this.Label26).EndInit();
    ((ISupportInitialize) this.Label25).EndInit();
    ((ISupportInitialize) this.Label24).EndInit();
    ((ISupportInitialize) this.Label23).EndInit();
    ((ISupportInitialize) this.Label22).EndInit();
    ((ISupportInitialize) this.Label21).EndInit();
    ((ISupportInitialize) this.Label20).EndInit();
    ((ISupportInitialize) this.Label19).EndInit();
    ((ISupportInitialize) this.Label18).EndInit();
    ((ISupportInitialize) this.CheckBox1).EndInit();
    ((ISupportInitialize) this.CheckBox2).EndInit();
    ((ISupportInitialize) this.lblSplitter).EndInit();
  }

  [field: AccessedThroughProperty("ghSplitter")]
  private virtual GroupHeader ghSplitter { get; [MethodImpl(MethodImplOptions.Synchronized)] set; }

  [field: AccessedThroughProperty("ghLocation")]
  private virtual GroupHeader ghLocation { get; [MethodImpl(MethodImplOptions.Synchronized)] set; }

  [field: AccessedThroughProperty("Detail")]
  private virtual Detail Detail { get; [MethodImpl(MethodImplOptions.Synchronized)] set; }

  [field: AccessedThroughProperty("gfLocation")]
  private virtual GroupFooter gfLocation { get; [MethodImpl(MethodImplOptions.Synchronized)] set; }

  [field: AccessedThroughProperty("gfSplitter")]
  private virtual GroupFooter gfSplitter { get; [MethodImpl(MethodImplOptions.Synchronized)] set; }
}
