// Decompiled with JetBrains decompiler
// Type: MGASystems.IMS.Accounting.GeneralLedger.EntityView.FormEntityActivityView
// Assembly: MgaSystems.IMS.Accounting.GeneralLedger, Version=2.0.0.0, Culture=neutral, PublicKeyToken=e175cb7c4ce15bbd
// MVID: DC511D5D-5AA9-4B52-8578-E2A0BCB046C3
// Assembly location: D:\augusta\fortegra\IMS Project\MgaSystems.IMS.Claims\lib\MgaSystems.IMS.Accounting.GeneralLedger.dll

using Infragistics.Win;
using Infragistics.Win.Misc;
using Infragistics.Win.UltraWinEditors;
using Infragistics.Win.UltraWinGrid;
using Infragistics.Win.UltraWinScrollBar;
using Infragistics.Win.UltraWinToolbars;
using MGASystems.Common;
using MGASystems.IMS.Accounting.GeneralLedger.Properties;
using MGASystems.Tools;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace MGASystems.IMS.Accounting.GeneralLedger.EntityView;

public class FormEntityActivityView : FormBase
{
  private IContainer components;
  private UltraGrid gridEntityView;
  private Label label1;
  private Label label2;
  private Label label3;
  private Label label4;
  private Label label5;
  private ActiveEntitySearch activeEntitySearch1;
  private MGADateTimePicker mgaDateTimePicker1;
  private MGASimpleComboBox comboOfficeLocation;
  private MGATextBox textControlNumber;
  private MGATextBox mgaTextBox1;
  private MGATextBox mgaTextBox2;
  private MGADateTimePicker mgaDateTimePicker2;
  private Label label6;
  private Label label7;
  private MGASimpleComboBox mgaSimpleComboBox1;
  private Label label8;
  private MGAButton mgaButton1;
  private MGAButton mgaButton2;
  private UltraToolbarsManager ultraToolbarsManager1;
  private UltraPanel FormEntityActivityView_Fill_Panel;
  private UltraToolbarsDockArea _FormEntityActivityView_Toolbars_Dock_Area_Left;
  private UltraToolbarsDockArea _FormEntityActivityView_Toolbars_Dock_Area_Right;
  private UltraToolbarsDockArea _FormEntityActivityView_Toolbars_Dock_Area_Bottom;
  private UltraToolbarsDockArea _FormEntityActivityView_Toolbars_Dock_Area_Top;
  private Panel panel1;
  private dsEntityView dsEntityView1;

  public FormEntityActivityView() => this.InitializeComponent();

  protected override void Dispose(bool disposing)
  {
    if (disposing && this.components != null)
      this.components.Dispose();
    base.Dispose(disposing);
  }

  private void InitializeComponent()
  {
    this.components = (IContainer) new System.ComponentModel.Container();
    Appearance appearance1 = new Appearance();
    UltraGridBand ultraGridBand = new UltraGridBand("EntityView", -1);
    UltraGridColumn ultraGridColumn1 = new UltraGridColumn("TransactNum");
    UltraGridColumn ultraGridColumn2 = new UltraGridColumn("PostDate");
    UltraGridColumn ultraGridColumn3 = new UltraGridColumn("Payee_Remiter");
    UltraGridColumn ultraGridColumn4 = new UltraGridColumn("Control Number");
    UltraGridColumn ultraGridColumn5 = new UltraGridColumn("Policy Number");
    UltraGridColumn ultraGridColumn6 = new UltraGridColumn("Insured Name");
    UltraGridColumn ultraGridColumn7 = new UltraGridColumn("EffectiveDate");
    UltraGridColumn ultraGridColumn8 = new UltraGridColumn("ExpirationDate");
    UltraGridColumn ultraGridColumn9 = new UltraGridColumn("LOB");
    UltraGridColumn ultraGridColumn10 = new UltraGridColumn("Company");
    UltraGridColumn ultraGridColumn11 = new UltraGridColumn("Producer");
    UltraGridColumn ultraGridColumn12 = new UltraGridColumn("Check Number");
    UltraGridColumn ultraGridColumn13 = new UltraGridColumn("AR Amount");
    UltraGridColumn ultraGridColumn14 = new UltraGridColumn("AP Amount");
    UltraGridColumn ultraGridColumn15 = new UltraGridColumn("Exchange Amount");
    UltraGridColumn ultraGridColumn16 = new UltraGridColumn("Un-Accounted Amount");
    UltraGridColumn ultraGridColumn17 = new UltraGridColumn("ARRem");
    UltraGridColumn ultraGridColumn18 = new UltraGridColumn("APRem");
    UltraGridColumn ultraGridColumn19 = new UltraGridColumn("ExchRem");
    UltraGridColumn ultraGridColumn20 = new UltraGridColumn("UnacctRem");
    Appearance appearance2 = new Appearance();
    Appearance appearance3 = new Appearance();
    Appearance appearance4 = new Appearance();
    Appearance appearance5 = new Appearance();
    Appearance appearance6 = new Appearance();
    Appearance appearance7 = new Appearance();
    ScrollBarLook scrollBarLook = new ScrollBarLook();
    Appearance appearance8 = new Appearance();
    Appearance appearance9 = new Appearance();
    Appearance appearance10 = new Appearance();
    Appearance appearance11 = new Appearance();
    Appearance appearance12 = new Appearance();
    Appearance appearance13 = new Appearance();
    Appearance appearance14 = new Appearance();
    Appearance appearance15 = new Appearance();
    Appearance appearance16 = new Appearance();
    Appearance appearance17 = new Appearance();
    Appearance appearance18 = new Appearance();
    Appearance appearance19 = new Appearance();
    UltraToolbar ultraToolbar = new UltraToolbar("UltraToolbar1");
    ButtonTool buttonTool1 = new ButtonTool("CANCEL");
    ButtonTool buttonTool2 = new ButtonTool("PRINT");
    ButtonTool buttonTool3 = new ButtonTool("EXPORT");
    ButtonTool buttonTool4 = new ButtonTool("CANCEL");
    Appearance appearance20 = new Appearance();
    ButtonTool buttonTool5 = new ButtonTool("PRINT");
    Appearance appearance21 = new Appearance();
    ButtonTool buttonTool6 = new ButtonTool("EXPORT");
    Appearance appearance22 = new Appearance();
    this.gridEntityView = new UltraGrid();
    this.label1 = new Label();
    this.label2 = new Label();
    this.label3 = new Label();
    this.label4 = new Label();
    this.label5 = new Label();
    this.activeEntitySearch1 = new ActiveEntitySearch();
    this.mgaDateTimePicker1 = new MGADateTimePicker();
    this.comboOfficeLocation = new MGASimpleComboBox();
    this.textControlNumber = new MGATextBox();
    this.mgaTextBox1 = new MGATextBox();
    this.mgaTextBox2 = new MGATextBox();
    this.mgaDateTimePicker2 = new MGADateTimePicker();
    this.label6 = new Label();
    this.label7 = new Label();
    this.mgaSimpleComboBox1 = new MGASimpleComboBox();
    this.label8 = new Label();
    this.mgaButton1 = new MGAButton();
    this.mgaButton2 = new MGAButton();
    this.FormEntityActivityView_Fill_Panel = new UltraPanel();
    this._FormEntityActivityView_Toolbars_Dock_Area_Left = new UltraToolbarsDockArea();
    this._FormEntityActivityView_Toolbars_Dock_Area_Right = new UltraToolbarsDockArea();
    this._FormEntityActivityView_Toolbars_Dock_Area_Top = new UltraToolbarsDockArea();
    this._FormEntityActivityView_Toolbars_Dock_Area_Bottom = new UltraToolbarsDockArea();
    this.panel1 = new Panel();
    this.ultraToolbarsManager1 = new UltraToolbarsManager(this.components);
    this.dsEntityView1 = new dsEntityView();
    ((ISupportInitialize) this.gridEntityView).BeginInit();
    ((ISupportInitialize) this.mgaDateTimePicker1).BeginInit();
    ((ISupportInitialize) this.comboOfficeLocation).BeginInit();
    ((ISupportInitialize) this.textControlNumber).BeginInit();
    ((ISupportInitialize) this.mgaTextBox1).BeginInit();
    ((ISupportInitialize) this.mgaTextBox2).BeginInit();
    ((ISupportInitialize) this.mgaDateTimePicker2).BeginInit();
    ((ISupportInitialize) this.mgaSimpleComboBox1).BeginInit();
    ((ISupportInitialize) this.mgaButton1).BeginInit();
    ((ISupportInitialize) this.mgaButton2).BeginInit();
    ((Control) this.FormEntityActivityView_Fill_Panel.ClientArea).SuspendLayout();
    ((Control) this.FormEntityActivityView_Fill_Panel).SuspendLayout();
    this.panel1.SuspendLayout();
    ((ISupportInitialize) this.ultraToolbarsManager1).BeginInit();
    this.dsEntityView1.BeginInit();
    this.SuspendLayout();
    ((UltraGridBase) this.gridEntityView).DataSource = (object) this.dsEntityView1;
    ((AppearanceBase) appearance1).BackColor = Color.White;
    ((AppearanceBase) appearance1).BorderColor = Color.FromArgb((int) sbyte.MaxValue, 157, 185);
    ((UltraGridBase) this.gridEntityView).DisplayLayout.Appearance = (AppearanceBase) appearance1;
    ((UltraGridBase) this.gridEntityView).DisplayLayout.AutoFitStyle = (AutoFitStyle) 1;
    ((HeaderBase) ultraGridColumn1.Header).VisiblePosition = 0;
    ultraGridColumn1.Width = 46;
    ((HeaderBase) ultraGridColumn2.Header).VisiblePosition = 1;
    ultraGridColumn2.Width = 72;
    ((HeaderBase) ultraGridColumn3.Header).VisiblePosition = 2;
    ultraGridColumn3.Width = 68;
    ((HeaderBase) ultraGridColumn4.Header).VisiblePosition = 3;
    ultraGridColumn4.Width = 66;
    ((HeaderBase) ultraGridColumn5.Header).VisiblePosition = 4;
    ultraGridColumn5.Width = 68;
    ((HeaderBase) ultraGridColumn6.Header).VisiblePosition = 5;
    ultraGridColumn6.Width = 68;
    ((HeaderBase) ultraGridColumn7.Header).VisiblePosition = 6;
    ultraGridColumn7.Hidden = true;
    ultraGridColumn7.Width = 46;
    ((HeaderBase) ultraGridColumn8.Header).VisiblePosition = 7;
    ultraGridColumn8.Hidden = true;
    ultraGridColumn8.Width = 46;
    ((HeaderBase) ultraGridColumn9.Header).VisiblePosition = 8;
    ultraGridColumn9.Width = 68;
    ((HeaderBase) ultraGridColumn10.Header).VisiblePosition = 9;
    ultraGridColumn10.Width = 68;
    ((HeaderBase) ultraGridColumn11.Header).VisiblePosition = 10;
    ultraGridColumn11.Width = 68;
    ((HeaderBase) ultraGridColumn12.Header).VisiblePosition = 11;
    ultraGridColumn12.Width = 68;
    ((HeaderBase) ultraGridColumn13.Header).VisiblePosition = 12;
    ultraGridColumn13.Width = 56;
    ((HeaderBase) ultraGridColumn14.Header).VisiblePosition = 13;
    ultraGridColumn14.Width = 56;
    ((HeaderBase) ultraGridColumn15.Header).VisiblePosition = 14;
    ultraGridColumn15.Width = 75;
    ((HeaderBase) ultraGridColumn16.Header).VisiblePosition = 15;
    ultraGridColumn16.Width = 89;
    ((HeaderBase) ultraGridColumn17.Header).VisiblePosition = 16 /*0x10*/;
    ultraGridColumn17.Hidden = true;
    ultraGridColumn17.Width = 41;
    ((HeaderBase) ultraGridColumn18.Header).VisiblePosition = 17;
    ultraGridColumn18.Hidden = true;
    ultraGridColumn18.Width = 41;
    ((HeaderBase) ultraGridColumn19.Header).VisiblePosition = 18;
    ultraGridColumn19.Hidden = true;
    ultraGridColumn19.Width = 41;
    ((HeaderBase) ultraGridColumn20.Header).VisiblePosition = 19;
    ultraGridColumn20.Hidden = true;
    ultraGridColumn20.Width = 41;
    ultraGridBand.Columns.AddRange(new object[20]
    {
      (object) ultraGridColumn1,
      (object) ultraGridColumn2,
      (object) ultraGridColumn3,
      (object) ultraGridColumn4,
      (object) ultraGridColumn5,
      (object) ultraGridColumn6,
      (object) ultraGridColumn7,
      (object) ultraGridColumn8,
      (object) ultraGridColumn9,
      (object) ultraGridColumn10,
      (object) ultraGridColumn11,
      (object) ultraGridColumn12,
      (object) ultraGridColumn13,
      (object) ultraGridColumn14,
      (object) ultraGridColumn15,
      (object) ultraGridColumn16,
      (object) ultraGridColumn17,
      (object) ultraGridColumn18,
      (object) ultraGridColumn19,
      (object) ultraGridColumn20
    });
    ((UltraGridBase) this.gridEntityView).DisplayLayout.BandsSerializer.Add((object) ultraGridBand);
    ((UltraGridBase) this.gridEntityView).DisplayLayout.BorderStyle = (UIElementBorderStyle) 4;
    ((AppearanceBase) appearance2).BackColor = Color.FromArgb((int) byte.MaxValue, 240 /*0xF0*/, 194);
    ((AppearanceBase) appearance2).BorderColor = Color.FromArgb((int) sbyte.MaxValue, 157, 185);
    ((AppearanceBase) appearance2).ForeColor = Color.Black;
    ((UltraGridBase) this.gridEntityView).DisplayLayout.Override.ActiveRowAppearance = (AppearanceBase) appearance2;
    ((UltraGridBase) this.gridEntityView).DisplayLayout.Override.AllowColSizing = (AllowColSizing) 3;
    ((UltraGridBase) this.gridEntityView).DisplayLayout.Override.AllowDelete = (DefaultableBoolean) 2;
    ((UltraGridBase) this.gridEntityView).DisplayLayout.Override.AllowUpdate = (DefaultableBoolean) 2;
    ((AppearanceBase) appearance3).BorderColor = Color.LightGray;
    ((UltraGridBase) this.gridEntityView).DisplayLayout.Override.CellAppearance = (AppearanceBase) appearance3;
    ((UltraGridBase) this.gridEntityView).DisplayLayout.Override.CellClickAction = (CellClickAction) 2;
    ((AppearanceBase) appearance4).BackColor = Color.FromArgb(207, 221, 240 /*0xF0*/);
    ((UltraGridBase) this.gridEntityView).DisplayLayout.Override.HeaderAppearance = (AppearanceBase) appearance4;
    ((UltraGridBase) this.gridEntityView).DisplayLayout.Override.MaxSelectedRows = 1;
    ((AppearanceBase) appearance5).BackColor = Color.FromArgb(246, 250, 253);
    ((UltraGridBase) this.gridEntityView).DisplayLayout.Override.RowAlternateAppearance = (AppearanceBase) appearance5;
    ((AppearanceBase) appearance6).BorderColor = Color.LightGray;
    ((UltraGridBase) this.gridEntityView).DisplayLayout.Override.RowAppearance = (AppearanceBase) appearance6;
    ((UltraGridBase) this.gridEntityView).DisplayLayout.Override.RowSelectors = (DefaultableBoolean) 2;
    ((AppearanceBase) appearance7).BackColor = Color.Transparent;
    ((AppearanceBase) appearance7).ForeColor = Color.Black;
    ((UltraGridBase) this.gridEntityView).DisplayLayout.Override.SelectedRowAppearance = (AppearanceBase) appearance7;
    ((AppearanceBase) appearance8).BackColor = Color.WhiteSmoke;
    ((AppearanceBase) appearance8).BorderColor = Color.Silver;
    scrollBarLook.ButtonAppearance = (AppearanceBase) appearance8;
    ((AppearanceBase) appearance9).BackColor = Color.White;
    scrollBarLook.TrackAppearance = (AppearanceBase) appearance9;
    ((UltraGridBase) this.gridEntityView).DisplayLayout.ScrollBarLook = scrollBarLook;
    ((Control) this.gridEntityView).Dock = DockStyle.Fill;
    ((Control) this.gridEntityView).Location = new Point(0, 94);
    ((Control) this.gridEntityView).Name = "gridEntityView";
    ((Control) this.gridEntityView).Size = new Size(938, 585);
    ((Control) this.gridEntityView).TabIndex = 0;
    ((UltraControlBase) this.gridEntityView).UseFlatMode = (DefaultableBoolean) 1;
    ((UltraControlBase) this.gridEntityView).UseOsThemes = (DefaultableBoolean) 2;
    this.label1.AutoSize = true;
    this.label1.BackColor = Color.Transparent;
    this.label1.Location = new Point(6, 9);
    this.label1.Name = "label1";
    this.label1.Size = new Size(36, 13);
    this.label1.TabIndex = 1;
    this.label1.Text = "Entity:";
    this.label2.AutoSize = true;
    this.label2.BackColor = Color.Transparent;
    this.label2.Location = new Point(377, 31 /*0x1F*/);
    this.label2.Name = "label2";
    this.label2.Size = new Size(85, 13);
    this.label2.TabIndex = 2;
    this.label2.Text = "Invoice Number:";
    this.label3.AutoSize = true;
    this.label3.BackColor = Color.Transparent;
    this.label3.Location = new Point(377, 9);
    this.label3.Name = "label3";
    this.label3.Size = new Size(78, 13);
    this.label3.TabIndex = 3;
    this.label3.Text = "Policy Number:";
    this.label4.AutoSize = true;
    this.label4.BackColor = Color.Transparent;
    this.label4.Location = new Point(6, 54);
    this.label4.Name = "label4";
    this.label4.Size = new Size(83, 13);
    this.label4.TabIndex = 4;
    this.label4.Text = "Control Number:";
    this.label5.AutoSize = true;
    this.label5.BackColor = Color.Transparent;
    this.label5.Location = new Point(6, 30);
    this.label5.Name = "label5";
    this.label5.Size = new Size(82, 13);
    this.label5.TabIndex = 5;
    this.label5.Text = "Office Location:";
    this.activeEntitySearch1.BackColor = Color.Transparent;
    this.activeEntitySearch1.Location = new Point(96 /*0x60*/, 9);
    this.activeEntitySearch1.Name = "activeEntitySearch1";
    this.activeEntitySearch1.Size = new Size(266, 19);
    this.activeEntitySearch1.TabIndex = 6;
    ((AppearanceBase) appearance10).BorderColor = Color.FromArgb((int) sbyte.MaxValue, 157, 185);
    this.mgaDateTimePicker1.Appearance = (AppearanceBase) appearance10;
    ((AppearanceBase) appearance11).AlphaLevel = (short) 14;
    ((AppearanceBase) appearance11).BackColor = Color.FromArgb(0, 0, 246, 253);
    ((AppearanceBase) appearance11).BackColor2 = Color.FromArgb(133, 162, 221);
    ((AppearanceBase) appearance11).BackColorAlpha = (Alpha) 2;
    ((AppearanceBase) appearance11).BackGradientAlignment = (GradientAlignment) 4;
    ((AppearanceBase) appearance11).BackGradientStyle = (GradientStyle) 5;
    ((AppearanceBase) appearance11).BorderAlpha = (Alpha) 1;
    ((AppearanceBase) appearance11).BorderColor = Color.FromArgb(78, 122, 171);
    ((AppearanceBase) appearance11).ForeColor = Color.FromArgb(49, 85, 153);
    ((AppearanceBase) appearance11).ForegroundAlpha = (Alpha) 2;
    this.mgaDateTimePicker1.ButtonAppearance = (AppearanceBase) appearance11;
    ((Control) this.mgaDateTimePicker1).Location = new Point(829, 12);
    this.mgaDateTimePicker1.MGAStyle = MGAStyles.Blue;
    ((Control) this.mgaDateTimePicker1).Name = "mgaDateTimePicker1";
    ((Control) this.mgaDateTimePicker1).Size = new Size(84, 19);
    ((Control) this.mgaDateTimePicker1).TabIndex = 7;
    ((UltraControlBase) this.mgaDateTimePicker1).UseFlatMode = (DefaultableBoolean) 1;
    ((UltraControlBase) this.mgaDateTimePicker1).UseOsThemes = (DefaultableBoolean) 2;
    this.comboOfficeLocation.BorderStyle = (UIElementBorderStyle) 4;
    this.comboOfficeLocation.DropDownStyle = (UltraComboStyle) 1;
    ((Control) this.comboOfficeLocation).Location = new Point(95, 31 /*0x1F*/);
    this.comboOfficeLocation.MGAStyle = MGAStyles.Blue;
    ((Control) this.comboOfficeLocation).Name = "comboOfficeLocation";
    ((Control) this.comboOfficeLocation).Size = new Size(267, 20);
    ((Control) this.comboOfficeLocation).TabIndex = 8;
    ((UltraControlBase) this.comboOfficeLocation).UseFlatMode = (DefaultableBoolean) 1;
    ((UltraControlBase) this.comboOfficeLocation).UseOsThemes = (DefaultableBoolean) 2;
    ((AppearanceBase) appearance12).BackColor = Color.White;
    ((AppearanceBase) appearance12).BorderColor = Color.FromArgb((int) sbyte.MaxValue, 157, 185);
    ((AppearanceBase) appearance12).ForeColor = Color.Black;
    ((TextEditorControlBase) this.textControlNumber).Appearance = (AppearanceBase) appearance12;
    ((Control) this.textControlNumber).BackColor = Color.White;
    ((Control) this.textControlNumber).Location = new Point(95, 55);
    this.textControlNumber.MGAStyle = MGAStyles.Blue;
    ((Control) this.textControlNumber).Name = "textControlNumber";
    ((Control) this.textControlNumber).Size = new Size(111, 19);
    ((Control) this.textControlNumber).TabIndex = 9;
    ((UltraControlBase) this.textControlNumber).UseFlatMode = (DefaultableBoolean) 1;
    ((UltraControlBase) this.textControlNumber).UseOsThemes = (DefaultableBoolean) 2;
    ((AppearanceBase) appearance13).BackColor = Color.White;
    ((AppearanceBase) appearance13).BorderColor = Color.FromArgb((int) sbyte.MaxValue, 157, 185);
    ((AppearanceBase) appearance13).ForeColor = Color.Black;
    ((TextEditorControlBase) this.mgaTextBox1).Appearance = (AppearanceBase) appearance13;
    ((Control) this.mgaTextBox1).BackColor = Color.White;
    ((Control) this.mgaTextBox1).Location = new Point(466, 33);
    this.mgaTextBox1.MGAStyle = MGAStyles.Blue;
    ((Control) this.mgaTextBox1).Name = "mgaTextBox1";
    ((Control) this.mgaTextBox1).Size = new Size(111, 19);
    ((Control) this.mgaTextBox1).TabIndex = 10;
    ((UltraControlBase) this.mgaTextBox1).UseFlatMode = (DefaultableBoolean) 1;
    ((UltraControlBase) this.mgaTextBox1).UseOsThemes = (DefaultableBoolean) 2;
    ((AppearanceBase) appearance14).BackColor = Color.White;
    ((AppearanceBase) appearance14).BorderColor = Color.FromArgb((int) sbyte.MaxValue, 157, 185);
    ((AppearanceBase) appearance14).ForeColor = Color.Black;
    ((TextEditorControlBase) this.mgaTextBox2).Appearance = (AppearanceBase) appearance14;
    ((Control) this.mgaTextBox2).BackColor = Color.White;
    ((Control) this.mgaTextBox2).Location = new Point(466, 10);
    this.mgaTextBox2.MGAStyle = MGAStyles.Blue;
    ((Control) this.mgaTextBox2).Name = "mgaTextBox2";
    ((Control) this.mgaTextBox2).Size = new Size(267, 19);
    ((Control) this.mgaTextBox2).TabIndex = 11;
    ((UltraControlBase) this.mgaTextBox2).UseFlatMode = (DefaultableBoolean) 1;
    ((UltraControlBase) this.mgaTextBox2).UseOsThemes = (DefaultableBoolean) 2;
    ((AppearanceBase) appearance15).BorderColor = Color.FromArgb((int) sbyte.MaxValue, 157, 185);
    this.mgaDateTimePicker2.Appearance = (AppearanceBase) appearance15;
    ((AppearanceBase) appearance16).AlphaLevel = (short) 14;
    ((AppearanceBase) appearance16).BackColor = Color.FromArgb(0, 0, 246, 253);
    ((AppearanceBase) appearance16).BackColor2 = Color.FromArgb(133, 162, 221);
    ((AppearanceBase) appearance16).BackColorAlpha = (Alpha) 2;
    ((AppearanceBase) appearance16).BackGradientAlignment = (GradientAlignment) 4;
    ((AppearanceBase) appearance16).BackGradientStyle = (GradientStyle) 5;
    ((AppearanceBase) appearance16).BorderAlpha = (Alpha) 1;
    ((AppearanceBase) appearance16).BorderColor = Color.FromArgb(78, 122, 171);
    ((AppearanceBase) appearance16).ForeColor = Color.FromArgb(49, 85, 153);
    ((AppearanceBase) appearance16).ForegroundAlpha = (Alpha) 2;
    this.mgaDateTimePicker2.ButtonAppearance = (AppearanceBase) appearance16;
    ((Control) this.mgaDateTimePicker2).Location = new Point(829, 34);
    this.mgaDateTimePicker2.MGAStyle = MGAStyles.Blue;
    ((Control) this.mgaDateTimePicker2).Name = "mgaDateTimePicker2";
    ((Control) this.mgaDateTimePicker2).Size = new Size(84, 19);
    ((Control) this.mgaDateTimePicker2).TabIndex = 12;
    ((UltraControlBase) this.mgaDateTimePicker2).UseFlatMode = (DefaultableBoolean) 1;
    ((UltraControlBase) this.mgaDateTimePicker2).UseOsThemes = (DefaultableBoolean) 2;
    this.label6.AutoSize = true;
    this.label6.BackColor = Color.Transparent;
    this.label6.Location = new Point(740, 34);
    this.label6.Name = "label6";
    this.label6.Size = new Size(82, 13);
    this.label6.TabIndex = 13;
    this.label6.Text = "Expiration Date:";
    this.label7.AutoSize = true;
    this.label7.BackColor = Color.Transparent;
    this.label7.Location = new Point(740, 12);
    this.label7.Name = "label7";
    this.label7.Size = new Size(78, 13);
    this.label7.TabIndex = 14;
    this.label7.Text = "Effective Date:";
    this.mgaSimpleComboBox1.BorderStyle = (UIElementBorderStyle) 4;
    this.mgaSimpleComboBox1.DropDownStyle = (UltraComboStyle) 1;
    ((Control) this.mgaSimpleComboBox1).Location = new Point(466, 56);
    this.mgaSimpleComboBox1.MGAStyle = MGAStyles.Blue;
    ((Control) this.mgaSimpleComboBox1).Name = "mgaSimpleComboBox1";
    ((Control) this.mgaSimpleComboBox1).Size = new Size(180, 20);
    ((Control) this.mgaSimpleComboBox1).TabIndex = 16 /*0x10*/;
    ((UltraControlBase) this.mgaSimpleComboBox1).UseFlatMode = (DefaultableBoolean) 1;
    ((UltraControlBase) this.mgaSimpleComboBox1).UseOsThemes = (DefaultableBoolean) 2;
    this.label8.AutoSize = true;
    this.label8.BackColor = Color.Transparent;
    this.label8.Location = new Point(377, 56);
    this.label8.Name = "label8";
    this.label8.Size = new Size(64 /*0x40*/, 13);
    this.label8.TabIndex = 15;
    this.label8.Text = "Billing Type:";
    ((AppearanceBase) appearance17).BackColor = Color.FromArgb(248, 248, 248);
    ((AppearanceBase) appearance17).BackColor2 = Color.FromArgb(250, 250, 250);
    ((AppearanceBase) appearance17).BackGradientStyle = (GradientStyle) 2;
    ((AppearanceBase) appearance17).BorderColor = Color.DarkGray;
    ((AppearanceBase) appearance17).Image = (object) Resources.magnifier;
    ((AppearanceBase) appearance17).ImageHAlign = (HAlign) 1;
    ((AppearanceBase) appearance17).ImageVAlign = (VAlign) 2;
    ((ControlBase) this.mgaButton1).Appearance = (AppearanceBase) appearance17;
    ((Control) this.mgaButton1).Location = new Point(829, 59);
    ((Control) this.mgaButton1).Name = "mgaButton1";
    ((Control) this.mgaButton1).Size = new Size(84, 25);
    ((Control) this.mgaButton1).TabIndex = 17;
    ((Control) this.mgaButton1).Text = "Search";
    ((UltraControlBase) this.mgaButton1).UseOsThemes = (DefaultableBoolean) 2;
    ((AppearanceBase) appearance18).BackColor = Color.FromArgb(248, 248, 248);
    ((AppearanceBase) appearance18).BackColor2 = Color.FromArgb(250, 250, 250);
    ((AppearanceBase) appearance18).BackGradientStyle = (GradientStyle) 2;
    ((AppearanceBase) appearance18).BorderColor = Color.DarkGray;
    ((AppearanceBase) appearance18).Image = (object) Resources.delete;
    ((AppearanceBase) appearance18).ImageHAlign = (HAlign) 1;
    ((AppearanceBase) appearance18).ImageVAlign = (VAlign) 2;
    ((ControlBase) this.mgaButton2).Appearance = (AppearanceBase) appearance18;
    ((Control) this.mgaButton2).Location = new Point(725, 59);
    ((Control) this.mgaButton2).Name = "mgaButton2";
    ((Control) this.mgaButton2).Size = new Size(97, 25);
    ((Control) this.mgaButton2).TabIndex = 18;
    ((Control) this.mgaButton2).Text = "Clear Search ";
    ((UltraControlBase) this.mgaButton2).UseOsThemes = (DefaultableBoolean) 2;
    ((AppearanceBase) appearance19).BackColor = Color.Transparent;
    this.FormEntityActivityView_Fill_Panel.Appearance = (AppearanceBase) appearance19;
    ((Control) this.FormEntityActivityView_Fill_Panel.ClientArea).Controls.Add((Control) this.gridEntityView);
    ((Control) this.FormEntityActivityView_Fill_Panel.ClientArea).Controls.Add((Control) this.panel1);
    ((Control) this.FormEntityActivityView_Fill_Panel).Cursor = Cursors.Default;
    ((Control) this.FormEntityActivityView_Fill_Panel).Dock = DockStyle.Fill;
    ((Control) this.FormEntityActivityView_Fill_Panel).Location = new Point(0, 43);
    ((Control) this.FormEntityActivityView_Fill_Panel).Name = "FormEntityActivityView_Fill_Panel";
    ((Control) this.FormEntityActivityView_Fill_Panel).Size = new Size(938, 679);
    ((Control) this.FormEntityActivityView_Fill_Panel).TabIndex = 0;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Left).AccessibleRole = AccessibleRole.Grouping;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Left).BackColor = Color.FromArgb(191, 219, (int) byte.MaxValue);
    this._FormEntityActivityView_Toolbars_Dock_Area_Left.DockedPosition = (DockedPosition) 2;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Left).ForeColor = SystemColors.ControlText;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Left).Location = new Point(0, 43);
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Left).Name = "_FormEntityActivityView_Toolbars_Dock_Area_Left";
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Left).Size = new Size(0, 679);
    this._FormEntityActivityView_Toolbars_Dock_Area_Left.ToolbarsManager = this.ultraToolbarsManager1;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Right).AccessibleRole = AccessibleRole.Grouping;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Right).BackColor = Color.FromArgb(191, 219, (int) byte.MaxValue);
    this._FormEntityActivityView_Toolbars_Dock_Area_Right.DockedPosition = (DockedPosition) 3;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Right).ForeColor = SystemColors.ControlText;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Right).Location = new Point(938, 43);
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Right).Name = "_FormEntityActivityView_Toolbars_Dock_Area_Right";
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Right).Size = new Size(0, 679);
    this._FormEntityActivityView_Toolbars_Dock_Area_Right.ToolbarsManager = this.ultraToolbarsManager1;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Top).AccessibleRole = AccessibleRole.Grouping;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Top).BackColor = Color.FromArgb(191, 219, (int) byte.MaxValue);
    this._FormEntityActivityView_Toolbars_Dock_Area_Top.DockedPosition = (DockedPosition) 0;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Top).ForeColor = SystemColors.ControlText;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Top).Location = new Point(0, 0);
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Top).Name = "_FormEntityActivityView_Toolbars_Dock_Area_Top";
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Top).Size = new Size(938, 43);
    this._FormEntityActivityView_Toolbars_Dock_Area_Top.ToolbarsManager = this.ultraToolbarsManager1;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Bottom).AccessibleRole = AccessibleRole.Grouping;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Bottom).BackColor = Color.FromArgb(191, 219, (int) byte.MaxValue);
    this._FormEntityActivityView_Toolbars_Dock_Area_Bottom.DockedPosition = (DockedPosition) 1;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Bottom).ForeColor = SystemColors.ControlText;
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Bottom).Location = new Point(0, 722);
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Bottom).Name = "_FormEntityActivityView_Toolbars_Dock_Area_Bottom";
    ((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Bottom).Size = new Size(938, 0);
    this._FormEntityActivityView_Toolbars_Dock_Area_Bottom.ToolbarsManager = this.ultraToolbarsManager1;
    this.panel1.Controls.Add((Control) this.mgaDateTimePicker1);
    this.panel1.Controls.Add((Control) this.mgaButton2);
    this.panel1.Controls.Add((Control) this.label1);
    this.panel1.Controls.Add((Control) this.mgaButton1);
    this.panel1.Controls.Add((Control) this.label2);
    this.panel1.Controls.Add((Control) this.mgaSimpleComboBox1);
    this.panel1.Controls.Add((Control) this.label3);
    this.panel1.Controls.Add((Control) this.label8);
    this.panel1.Controls.Add((Control) this.label4);
    this.panel1.Controls.Add((Control) this.label7);
    this.panel1.Controls.Add((Control) this.label5);
    this.panel1.Controls.Add((Control) this.label6);
    this.panel1.Controls.Add((Control) this.activeEntitySearch1);
    this.panel1.Controls.Add((Control) this.mgaDateTimePicker2);
    this.panel1.Controls.Add((Control) this.comboOfficeLocation);
    this.panel1.Controls.Add((Control) this.mgaTextBox2);
    this.panel1.Controls.Add((Control) this.textControlNumber);
    this.panel1.Controls.Add((Control) this.mgaTextBox1);
    this.panel1.Dock = DockStyle.Top;
    this.panel1.Location = new Point(0, 0);
    this.panel1.Name = "panel1";
    this.panel1.Size = new Size(938, 94);
    this.panel1.TabIndex = 19;
    this.ultraToolbarsManager1.DesignerFlags = 1;
    this.ultraToolbarsManager1.DockWithinContainer = (Control) this;
    this.ultraToolbarsManager1.DockWithinContainerBaseType = typeof (FormBase);
    this.ultraToolbarsManager1.Style = (ToolbarStyle) 8;
    ultraToolbar.DockedColumn = 0;
    ultraToolbar.DockedRow = 0;
    ((ToolBase) buttonTool2).InstanceProps.IsFirstInGroup = true;
    ((ToolBase) buttonTool3).InstanceProps.IsFirstInGroup = true;
    ((UltraToolbarBase) ultraToolbar).NonInheritedTools.AddRange(new ToolBase[3]
    {
      (ToolBase) buttonTool1,
      (ToolBase) buttonTool2,
      (ToolBase) buttonTool3
    });
    ultraToolbar.Text = "UltraToolbar1";
    this.ultraToolbarsManager1.Toolbars.AddRange(new UltraToolbar[1]
    {
      ultraToolbar
    });
    this.ultraToolbarsManager1.ToolbarSettings.AllowCustomize = (DefaultableBoolean) 2;
    this.ultraToolbarsManager1.ToolbarSettings.AllowDockBottom = (DefaultableBoolean) 2;
    this.ultraToolbarsManager1.ToolbarSettings.AllowDockLeft = (DefaultableBoolean) 2;
    this.ultraToolbarsManager1.ToolbarSettings.AllowDockRight = (DefaultableBoolean) 2;
    this.ultraToolbarsManager1.ToolbarSettings.AllowDockTop = (DefaultableBoolean) 2;
    this.ultraToolbarsManager1.ToolbarSettings.AllowFloating = (DefaultableBoolean) 2;
    this.ultraToolbarsManager1.ToolbarSettings.AllowHiding = (DefaultableBoolean) 2;
    this.ultraToolbarsManager1.ToolbarSettings.CaptionPlacement = (TextPlacement) 2;
    this.ultraToolbarsManager1.ToolbarSettings.FillEntireRow = (DefaultableBoolean) 1;
    this.ultraToolbarsManager1.ToolbarSettings.GrabHandleStyle = (GrabHandleStyle) 1;
    ((SettingsBase) this.ultraToolbarsManager1.ToolbarSettings).ToolDisplayStyle = (ToolDisplayStyle) 4;
    ((AppearanceBase) appearance20).Image = (object) Resources.delete;
    ((ToolPropsBase) ((ToolBase) buttonTool4).SharedPropsInternal).AppearancesSmall.Appearance = (AppearanceBase) appearance20;
    ((ToolPropsBase) ((ToolBase) buttonTool4).SharedPropsInternal).Caption = "Cancel";
    ((AppearanceBase) appearance21).Image = (object) Resources.printer;
    ((ToolPropsBase) ((ToolBase) buttonTool5).SharedPropsInternal).AppearancesSmall.Appearance = (AppearanceBase) appearance21;
    ((ToolPropsBase) ((ToolBase) buttonTool5).SharedPropsInternal).Caption = "Print Results";
    ((AppearanceBase) appearance22).Image = (object) Resources.ExcelIco1;
    ((ToolPropsBase) ((ToolBase) buttonTool6).SharedPropsInternal).AppearancesSmall.Appearance = (AppearanceBase) appearance22;
    ((ToolPropsBase) ((ToolBase) buttonTool6).SharedPropsInternal).Caption = "Export Results";
    ((ToolsCollectionBase) this.ultraToolbarsManager1.Tools).AddRange(new ToolBase[3]
    {
      (ToolBase) buttonTool4,
      (ToolBase) buttonTool5,
      (ToolBase) buttonTool6
    });
    this.dsEntityView1.DataSetName = "dsEntityView";
    this.dsEntityView1.SchemaSerializationMode = SchemaSerializationMode.IncludeSchema;
    this.AutoScaleDimensions = new SizeF(6f, 13f);
    this.AutoScaleMode = AutoScaleMode.Font;
    this.ClientSize = new Size(938, 722);
    this.Controls.Add((Control) this.FormEntityActivityView_Fill_Panel);
    this.Controls.Add((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Left);
    this.Controls.Add((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Right);
    this.Controls.Add((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Bottom);
    this.Controls.Add((Control) this._FormEntityActivityView_Toolbars_Dock_Area_Top);
    this.Name = nameof (FormEntityActivityView);
    this.StartPosition = FormStartPosition.CenterScreen;
    this.Text = "Entity Financial Activity View";
    ((ISupportInitialize) this.gridEntityView).EndInit();
    ((ISupportInitialize) this.mgaDateTimePicker1).EndInit();
    ((ISupportInitialize) this.comboOfficeLocation).EndInit();
    ((ISupportInitialize) this.textControlNumber).EndInit();
    ((ISupportInitialize) this.mgaTextBox1).EndInit();
    ((ISupportInitialize) this.mgaTextBox2).EndInit();
    ((ISupportInitialize) this.mgaDateTimePicker2).EndInit();
    ((ISupportInitialize) this.mgaSimpleComboBox1).EndInit();
    ((ISupportInitialize) this.mgaButton1).EndInit();
    ((ISupportInitialize) this.mgaButton2).EndInit();
    ((Control) this.FormEntityActivityView_Fill_Panel.ClientArea).ResumeLayout(false);
    ((Control) this.FormEntityActivityView_Fill_Panel).ResumeLayout(false);
    this.panel1.ResumeLayout(false);
    this.panel1.PerformLayout();
    ((ISupportInitialize) this.ultraToolbarsManager1).EndInit();
    this.dsEntityView1.EndInit();
    this.ResumeLayout(false);
  }
}
