// Decompiled with JetBrains decompiler
// Type: MGASystems.IMS.Accounting.GeneralLedger.Controls.GLAccountBalanceInformation
// Assembly: MgaSystems.IMS.Accounting.GeneralLedger, Version=2.0.0.0, Culture=neutral, PublicKeyToken=e175cb7c4ce15bbd
// MVID: DC511D5D-5AA9-4B52-8578-E2A0BCB046C3
// Assembly location: D:\augusta\fortegra\IMS Project\MgaSystems.IMS.Claims\lib\MgaSystems.IMS.Accounting.GeneralLedger.dll

using Infragistics.UltraChart.Resources.Appearance;
using Infragistics.UltraChart.Shared.Styles;
using MGASystems.Tools;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

#nullable disable
namespace MGASystems.IMS.Accounting.GeneralLedger.Controls;

public class GLAccountBalanceInformation : UserControl
{
  private EllipsePanel ellipsePanel1;
  private Label label1;
  private Label labelCurrentAccountBalance;
  private Infragistics.Win.UltraWinChart.UltraChart ultraChart2;
  private Infragistics.Win.UltraWinChart.UltraChart ultraChart1;
  private System.ComponentModel.Container components;

  public GLAccountBalanceInformation() => this.InitializeComponent();

  protected override void Dispose(bool disposing)
  {
    if (disposing && this.components != null)
      this.components.Dispose();
    base.Dispose(disposing);
  }

  private void InitializeComponent()
  {
    LineChartAppearance lineChartAppearance1 = new LineChartAppearance();
    LineChartAppearance lineChartAppearance2 = new LineChartAppearance();
    this.ellipsePanel1 = new EllipsePanel();
    this.label1 = new Label();
    this.labelCurrentAccountBalance = new Label();
    this.ultraChart2 = new Infragistics.Win.UltraWinChart.UltraChart();
    this.ultraChart1 = new Infragistics.Win.UltraWinChart.UltraChart();
    this.ellipsePanel1.SuspendLayout();
    ((ISupportInitialize) this.ultraChart2).BeginInit();
    ((ISupportInitialize) this.ultraChart1).BeginInit();
    this.SuspendLayout();
    this.ellipsePanel1.Controls.Add((Control) this.ultraChart2);
    this.ellipsePanel1.Controls.Add((Control) this.ultraChart1);
    this.ellipsePanel1.Controls.Add((Control) this.labelCurrentAccountBalance);
    this.ellipsePanel1.Controls.Add((Control) this.label1);
    this.ellipsePanel1.CornerOffset = 25;
    this.ellipsePanel1.Dock = DockStyle.Fill;
    this.ellipsePanel1.Location = new Point(0, 0);
    this.ellipsePanel1.Name = "ellipsePanel1";
    this.ellipsePanel1.Size = new Size(248, 400);
    this.ellipsePanel1.TabIndex = 0;
    this.label1.Font = new Font("Tahoma", 8f, FontStyle.Bold);
    this.label1.Location = new Point(8, 16 /*0x10*/);
    this.label1.Name = "label1";
    this.label1.Size = new Size(232, 16 /*0x10*/);
    this.label1.TabIndex = 0;
    this.label1.Text = "Current Account Balance";
    this.label1.TextAlign = ContentAlignment.MiddleCenter;
    this.labelCurrentAccountBalance.Font = new Font("Tahoma", 8f, FontStyle.Bold);
    this.labelCurrentAccountBalance.Location = new Point(8, 32 /*0x20*/);
    this.labelCurrentAccountBalance.Name = "labelCurrentAccountBalance";
    this.labelCurrentAccountBalance.Size = new Size(232, 16 /*0x10*/);
    this.labelCurrentAccountBalance.TabIndex = 1;
    this.labelCurrentAccountBalance.Text = "[Current Account Balance]";
    this.labelCurrentAccountBalance.TextAlign = ContentAlignment.MiddleCenter;
    this.ultraChart2.ChartType = (ChartType) 3;
    this.ultraChart2.Axis.X.Extent = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X.Labels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X.Labels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X.Labels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X.Labels.SeriesLabels).Flip = false;
    this.ultraChart2.Axis.X.Labels.SeriesLabels.FormatString = "";
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X.Labels.SeriesLabels).Orientation = (TextOrientation) 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X.Labels.SeriesLabels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X.Labels.SeriesLabels).VerticalAlign = StringAlignment.Center;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X.Labels).VerticalAlign = StringAlignment.Center;
    this.ultraChart2.Axis.X.ScrollScale.Height = 10;
    this.ultraChart2.Axis.X.ScrollScale.Visible = false;
    this.ultraChart2.Axis.X.ScrollScale.Width = 15;
    this.ultraChart2.Axis.X.TickmarkInterval = 0.0;
    this.ultraChart2.Axis.X2.Extent = 10;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X2.Labels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X2.Labels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X2.Labels.SeriesLabels).Flip = false;
    this.ultraChart2.Axis.X2.Labels.SeriesLabels.FormatString = "";
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X2.Labels.SeriesLabels).Orientation = (TextOrientation) 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X2.Labels.SeriesLabels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X2.Labels.SeriesLabels).VerticalAlign = StringAlignment.Center;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.X2.Labels).VerticalAlign = StringAlignment.Center;
    this.ultraChart2.Axis.X2.ScrollScale.Height = 10;
    this.ultraChart2.Axis.X2.ScrollScale.Visible = false;
    this.ultraChart2.Axis.X2.ScrollScale.Width = 15;
    this.ultraChart2.Axis.X2.TickmarkInterval = 0.0;
    this.ultraChart2.Axis.Y.Extent = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y.Labels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y.Labels).HorizontalAlign = StringAlignment.Far;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y.Labels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y.Labels.SeriesLabels).Flip = false;
    this.ultraChart2.Axis.Y.Labels.SeriesLabels.FormatString = "";
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y.Labels.SeriesLabels).HorizontalAlign = StringAlignment.Far;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y.Labels.SeriesLabels).Orientation = (TextOrientation) 2;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y.Labels.SeriesLabels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y.Labels.SeriesLabels).VerticalAlign = StringAlignment.Center;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y.Labels).VerticalAlign = StringAlignment.Center;
    this.ultraChart2.Axis.Y.ScrollScale.Height = 10;
    this.ultraChart2.Axis.Y.ScrollScale.Visible = false;
    this.ultraChart2.Axis.Y.ScrollScale.Width = 15;
    this.ultraChart2.Axis.Y.TickmarkInterval = 0.0;
    this.ultraChart2.Axis.Y2.Extent = 10;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y2.Labels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y2.Labels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y2.Labels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y2.Labels.SeriesLabels).Flip = false;
    this.ultraChart2.Axis.Y2.Labels.SeriesLabels.FormatString = "";
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y2.Labels.SeriesLabels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y2.Labels.SeriesLabels).Orientation = (TextOrientation) 2;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y2.Labels.SeriesLabels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y2.Labels.SeriesLabels).VerticalAlign = StringAlignment.Center;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Y2.Labels).VerticalAlign = StringAlignment.Center;
    this.ultraChart2.Axis.Y2.ScrollScale.Height = 10;
    this.ultraChart2.Axis.Y2.ScrollScale.Visible = false;
    this.ultraChart2.Axis.Y2.ScrollScale.Width = 15;
    this.ultraChart2.Axis.Y2.TickmarkInterval = 0.0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z.Labels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z.Labels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z.Labels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z.Labels.SeriesLabels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z.Labels.SeriesLabels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z.Labels.SeriesLabels).Orientation = (TextOrientation) 2;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z.Labels.SeriesLabels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z.Labels.SeriesLabels).VerticalAlign = StringAlignment.Center;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z.Labels).VerticalAlign = StringAlignment.Center;
    this.ultraChart2.Axis.Z.ScrollScale.Height = 10;
    this.ultraChart2.Axis.Z.ScrollScale.Visible = false;
    this.ultraChart2.Axis.Z.ScrollScale.Width = 15;
    this.ultraChart2.Axis.Z.TickmarkInterval = 0.0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z2.Labels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z2.Labels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z2.Labels).Orientation = (TextOrientation) 2;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z2.Labels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z2.Labels.SeriesLabels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z2.Labels.SeriesLabels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z2.Labels.SeriesLabels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z2.Labels.SeriesLabels).VerticalAlign = StringAlignment.Center;
    ((AxisLabelAppearanceBase) this.ultraChart2.Axis.Z2.Labels).VerticalAlign = StringAlignment.Center;
    this.ultraChart2.Axis.Z2.ScrollScale.Height = 10;
    this.ultraChart2.Axis.Z2.ScrollScale.Visible = false;
    this.ultraChart2.Axis.Z2.ScrollScale.Width = 15;
    this.ultraChart2.Axis.Z2.TickmarkInterval = 0.0;
    this.ultraChart2.Border.CornerRadius = 5;
    this.ultraChart2.Data.EmptyStyle.LineStyle.DrawStyle = (LineDrawStyle) 1;
    this.ultraChart2.Data.EmptyStyle.LineStyle.EndStyle = (LineCapStyle) 0;
    this.ultraChart2.Data.EmptyStyle.LineStyle.MidPointAnchors = false;
    this.ultraChart2.Data.EmptyStyle.LineStyle.StartStyle = (LineCapStyle) 0;
    ((Control) this.ultraChart2).ForeColor = Color.Black;
    lineChartAppearance1.MidPointAnchors = false;
    lineChartAppearance1.Thickness = 1;
    this.ultraChart2.LineChart = lineChartAppearance1;
    ((Control) this.ultraChart2).Location = new Point(40, 232);
    ((Control) this.ultraChart2).Name = "ultraChart2";
    ((Control) this.ultraChart2).Size = new Size(160 /*0xA0*/, 144 /*0x90*/);
    this.ultraChart2.TabIndex = 5;
    this.ultraChart2.Tooltips.Font = new Font("Microsoft Sans Serif", 7.8f);
    this.ultraChart2.Tooltips.UseControl = false;
    this.ultraChart1.ChartType = (ChartType) 3;
    this.ultraChart1.Axis.X.Extent = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X.Labels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X.Labels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X.Labels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X.Labels.SeriesLabels).Flip = false;
    this.ultraChart1.Axis.X.Labels.SeriesLabels.FormatString = "";
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X.Labels.SeriesLabels).Orientation = (TextOrientation) 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X.Labels.SeriesLabels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X.Labels.SeriesLabels).VerticalAlign = StringAlignment.Center;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X.Labels).VerticalAlign = StringAlignment.Center;
    this.ultraChart1.Axis.X.ScrollScale.Height = 10;
    this.ultraChart1.Axis.X.ScrollScale.Visible = false;
    this.ultraChart1.Axis.X.ScrollScale.Width = 15;
    this.ultraChart1.Axis.X.TickmarkInterval = 0.0;
    this.ultraChart1.Axis.X2.Extent = 5;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X2.Labels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X2.Labels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X2.Labels.SeriesLabels).Flip = false;
    this.ultraChart1.Axis.X2.Labels.SeriesLabels.FormatString = "";
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X2.Labels.SeriesLabels).Orientation = (TextOrientation) 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X2.Labels.SeriesLabels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X2.Labels.SeriesLabels).VerticalAlign = StringAlignment.Center;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.X2.Labels).VerticalAlign = StringAlignment.Center;
    this.ultraChart1.Axis.X2.ScrollScale.Height = 10;
    this.ultraChart1.Axis.X2.ScrollScale.Visible = false;
    this.ultraChart1.Axis.X2.ScrollScale.Width = 15;
    this.ultraChart1.Axis.X2.TickmarkInterval = 0.0;
    this.ultraChart1.Axis.Y.Extent = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y.Labels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y.Labels).HorizontalAlign = StringAlignment.Far;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y.Labels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y.Labels.SeriesLabels).Flip = false;
    this.ultraChart1.Axis.Y.Labels.SeriesLabels.FormatString = "";
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y.Labels.SeriesLabels).HorizontalAlign = StringAlignment.Far;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y.Labels.SeriesLabels).Orientation = (TextOrientation) 2;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y.Labels.SeriesLabels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y.Labels.SeriesLabels).VerticalAlign = StringAlignment.Center;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y.Labels).VerticalAlign = StringAlignment.Center;
    this.ultraChart1.Axis.Y.ScrollScale.Height = 10;
    this.ultraChart1.Axis.Y.ScrollScale.Visible = false;
    this.ultraChart1.Axis.Y.ScrollScale.Width = 15;
    this.ultraChart1.Axis.Y.TickmarkInterval = 0.0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y2.Labels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y2.Labels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y2.Labels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y2.Labels.SeriesLabels).Flip = false;
    this.ultraChart1.Axis.Y2.Labels.SeriesLabels.FormatString = "";
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y2.Labels.SeriesLabels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y2.Labels.SeriesLabels).Orientation = (TextOrientation) 2;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y2.Labels.SeriesLabels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y2.Labels.SeriesLabels).VerticalAlign = StringAlignment.Center;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Y2.Labels).VerticalAlign = StringAlignment.Center;
    this.ultraChart1.Axis.Y2.ScrollScale.Height = 10;
    this.ultraChart1.Axis.Y2.ScrollScale.Visible = false;
    this.ultraChart1.Axis.Y2.ScrollScale.Width = 15;
    this.ultraChart1.Axis.Y2.TickmarkInterval = 0.0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z.Labels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z.Labels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z.Labels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z.Labels.SeriesLabels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z.Labels.SeriesLabels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z.Labels.SeriesLabels).Orientation = (TextOrientation) 2;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z.Labels.SeriesLabels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z.Labels.SeriesLabels).VerticalAlign = StringAlignment.Center;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z.Labels).VerticalAlign = StringAlignment.Center;
    this.ultraChart1.Axis.Z.ScrollScale.Height = 10;
    this.ultraChart1.Axis.Z.ScrollScale.Visible = false;
    this.ultraChart1.Axis.Z.ScrollScale.Width = 15;
    this.ultraChart1.Axis.Z.TickmarkInterval = 0.0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z2.Labels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z2.Labels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z2.Labels).Orientation = (TextOrientation) 2;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z2.Labels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z2.Labels.SeriesLabels).Flip = false;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z2.Labels.SeriesLabels).HorizontalAlign = StringAlignment.Near;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z2.Labels.SeriesLabels).OrientationAngle = 0;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z2.Labels.SeriesLabels).VerticalAlign = StringAlignment.Center;
    ((AxisLabelAppearanceBase) this.ultraChart1.Axis.Z2.Labels).VerticalAlign = StringAlignment.Center;
    this.ultraChart1.Axis.Z2.ScrollScale.Height = 10;
    this.ultraChart1.Axis.Z2.ScrollScale.Visible = false;
    this.ultraChart1.Axis.Z2.ScrollScale.Width = 15;
    this.ultraChart1.Axis.Z2.TickmarkInterval = 0.0;
    this.ultraChart1.Border.CornerRadius = 5;
    this.ultraChart1.Data.EmptyStyle.LineStyle.DrawStyle = (LineDrawStyle) 1;
    this.ultraChart1.Data.EmptyStyle.LineStyle.EndStyle = (LineCapStyle) 0;
    this.ultraChart1.Data.EmptyStyle.LineStyle.MidPointAnchors = false;
    this.ultraChart1.Data.EmptyStyle.LineStyle.StartStyle = (LineCapStyle) 0;
    ((Control) this.ultraChart1).Font = new Font("Tahoma", 8f);
    ((Control) this.ultraChart1).ForeColor = Color.Black;
    lineChartAppearance2.Thickness = 1;
    this.ultraChart1.LineChart = lineChartAppearance2;
    ((Control) this.ultraChart1).Location = new Point(40, 64 /*0x40*/);
    ((Control) this.ultraChart1).Name = "ultraChart1";
    ((Control) this.ultraChart1).Size = new Size(160 /*0xA0*/, 144 /*0x90*/);
    this.ultraChart1.TabIndex = 2;
    this.ultraChart1.Tooltips.Font = new Font("Microsoft Sans Serif", 7.8f);
    this.ultraChart1.Tooltips.UseControl = false;
    this.BackColor = Color.White;
    this.Controls.Add((Control) this.ellipsePanel1);
    this.Font = new Font("Tahoma", 8f);
    this.ForeColor = Color.Black;
    this.Name = nameof (GLAccountBalanceInformation);
    this.Size = new Size(248, 400);
    this.ellipsePanel1.ResumeLayout(false);
    ((ISupportInitialize) this.ultraChart2).EndInit();
    ((ISupportInitialize) this.ultraChart1).EndInit();
    this.ResumeLayout(false);
  }
}
