// Decompiled with JetBrains decompiler
// Type: MGASystems.IMS.AdHocReportManager.frmAdHocReportManager
// Assembly: MGASystems.IMS.AdHocReportManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 82F2F291-BD8F-4EDC-8925-41D0C4FA14AC
// Assembly location: D:\augusta\fortegra\IMS Project\MgaSystems.IMS.AdHocReportManager.dll

using GrapeCity.ActiveReports;
using GrapeCity.ActiveReports.SectionReportModel;
using MGASystems.Common;
using MGASystems.Data;
using MGASystems.IMS.Forms;
using MGASystems.IMS.Reporting;
using MGASystems.IMS.Reporting.AutomationReports;
using MGASystems.IMS.Reporting.ReportControls;
using Microsoft.Win32;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Text;
using System.Windows.Forms;
using System.Windows.Forms.Layout;
using System.Xml;

#nullable disable
namespace MGASystems.IMS.AdHocReportManager;

public class frmAdHocReportManager : Form
{
  private AdHocReport _report;
  public Guid OpenReportGUID;
  private DataGridViewButtonColumn editCriteriaButton = new DataGridViewButtonColumn();
  private string _layout;
  private string _AutoGeneratedLayout = "";
  private string VisualStudioDevEnvPath = "";
  private bool IsGrapeCityInstalled;
  private List<string> _ReturnParameters = new List<string>();
  private List<Tuple<int, string>> automationDocGroups = new List<Tuple<int, string>>();
  private IContainer components;
  private MenuStrip menuStrip1;
  private ToolStripMenuItem reportToolStripMenuItem;
  private ToolStripMenuItem newReportToolStripMenuItem;
  private ToolStripMenuItem loadReportToolStripMenuItem;
  private Panel panel1;
  private TextBox txtName;
  private Label label1;
  private TabControl tabControl1;
  private TabPage tabPage1;
  private TabPage tabPage2;
  private SaveFileDialog saveFileDialog1;
  private OpenFileDialog openFileDialog1;
  private ToolStrip toolStrip1;
  private Panel panelBottom;
  private TextBox txtDescription;
  private TextBox txtGroup;
  private Label label3;
  private Label label2;
  private CheckBox chkPublished;
  private Label label5;
  private Label label4;
  private CheckBox chkScreen;
  private Panel panel3;
  private DataGridView dataGridView1;
  private Button btnMoveUpCriteria;
  private Button btnMoveDnCriteria;
  private Button btnDelCriteria;
  private Button btnAddCriteria;
  private TextBox txtTitle;
  private Label label6;
  private Button btnSave;
  private TabPage tabPage3;
  private TextBox txtSQL;
  private ToolStripButton toolStripButton1;
  private DataGridView gvCriteria;
  private ToolStripDropDownButton ddbParams;
  private ToolStripMenuItem editToolStripMenuItem;
  private ToolStripMenuItem createToolStripMenuItem;
  private ToolStripMenuItem saToolStripMenuItem;
  private ToolStripMenuItem toDatabaseToolStripMenuItem;
  private ToolStripMenuItem toFileToolStripMenuItem;
  private ToolStripMenuItem exportToSQLToolStripMenuItem;
  private ToolStripMenuItem deleteReportToolStripMenuItem;
  private TabPage tabPage4;
  private TextBox txtColWidth;
  private Label label7;
  private Label label9;
  private TextBox txtSumFields;
  private Label label8;
  private TabPage tabPage5;
  public ucPermissions ucPermissions1;
  private Label label10;
  private TextBox txtSubTitle;
  private ToolStripDropDownButton ddbParamsSubTitle;
  private Label label12;
  private TextBox txtMarginTop;
  private Label label11;
  private RadioButton rbLandscape;
  private RadioButton rbPortrait;
  private Label label16;
  private TextBox txtMarginRight;
  private TextBox txtMarginLeft;
  private TextBox txtMarginBottom;
  private Label label15;
  private Label label14;
  private Label label13;
  private TextBox txtTableNames;
  private Label label17;
  private ToolStripMenuItem loadReportFromFileToolStripMenuItem;
  private ToolStripMenuItem historyToolStripMenuItem;
  private ToolStripMenuItem thisReportOnlyToolStripMenuItem;
  private ToolStripMenuItem allAdHocReportsToolStripMenuItem;
  private Button btnEditLayout;
  private Panel pnlEditLayout;
  private ToolTip toolTip1;
  private Button btnRemoveLayout;
  private CheckBox chkAutoGen;
  private CheckBox chkThreaded;
  private Label label19;
  private CheckBox chkLargeExport;
  private Label label20;
  private ErrorProvider errError;
  private ErrorProvider errRecommend;
  private Label label21;
  private ComboBox cmbReportType;

  public frmAdHocReportManager()
  {
    this.InitializeComponent();
    this._report = new AdHocReport();
    this.ucPermissions1.InitPermissions(this._report);
    this.SetUpBindings();
  }

  private void frmAdHocReportManager_Load(object sender, EventArgs e)
  {
    this.VisualStudioDevEnvPath = this.GetLatestVS();
    if (this.VisualStudioDevEnvPath != "")
      this.VisualStudioDevEnvPath += "devenv.exe";
    this.IsGrapeCityInstalled = this.isGrapeCityInstalled();
    this.LargeDataExportValidation(false);
    this.PopulateDocumentTypeCombo();
    this.SetupVisualElements();
  }

  private void SetupVisualElements()
  {
    this.thisReportOnlyToolStripMenuItem.Enabled = this._report != null;
    if (this._report == null)
      return;
    this.chkScreen.CheckedChanged -= new EventHandler(this.chkScreen_CheckedChanged);
    this.cmbReportType.SelectedIndexChanged -= new EventHandler(this.cmbReportType_SelectedIndexChanged);
    if (CurrentUser.Instance.UserName.ToLower() == "admin1")
      this.cmbReportType.Visible = true;
    else
      this.cmbReportType.Visible = false;
    if (this.cmbReportType.SelectedValue != null && this.cmbReportType.SelectedValue.GetType() == typeof (int))
    {
      if ((int) this.cmbReportType.SelectedValue > 0)
      {
        this.chkScreen.Checked = true;
        this.chkScreen.Enabled = false;
        this.chkThreaded.Checked = false;
        this.chkThreaded.Enabled = false;
        this.chkLargeExport.Checked = false;
        this.chkLargeExport.Enabled = false;
        this.txtTableNames.Enabled = false;
        this.txtSubTitle.Enabled = false;
      }
      else
      {
        this.chkScreen.Enabled = true;
        this.chkThreaded.Enabled = true;
        this.chkLargeExport.Enabled = true;
        this.txtTableNames.Enabled = true;
        this.txtSubTitle.Enabled = true;
      }
    }
    if (!this.chkScreen.Checked)
    {
      this.txtColWidth.Enabled = false;
      this.pnlEditLayout.Visible = false;
      this.txtMarginBottom.Enabled = false;
      this.txtMarginLeft.Enabled = false;
      this.txtMarginRight.Enabled = false;
      this.txtMarginTop.Enabled = false;
    }
    else
    {
      this.txtColWidth.Enabled = true;
      this.pnlEditLayout.Visible = true;
      this.txtMarginBottom.Enabled = true;
      this.txtMarginLeft.Enabled = true;
      this.txtMarginRight.Enabled = true;
      this.txtMarginTop.Enabled = true;
    }
    this.pnlEditLayout.Visible = this.VisualStudioDevEnvPath != "" && this.IsGrapeCityInstalled && this.chkScreen.Checked;
    this.btnRemoveLayout.Enabled = this._report.isLayoutDefined;
    this.chkAutoGen.Checked = !this.btnRemoveLayout.Enabled;
    this.chkAutoGen.Enabled = !this.btnRemoveLayout.Enabled;
    this.chkAutoGen.Enabled = !this.btnRemoveLayout.Enabled;
    this.chkScreen.CheckedChanged += new EventHandler(this.chkScreen_CheckedChanged);
    this.cmbReportType.SelectedIndexChanged += new EventHandler(this.cmbReportType_SelectedIndexChanged);
  }

  private void PopulateDocumentTypeCombo()
  {
    this.cmbReportType.SelectedIndexChanged -= new EventHandler(this.cmbReportType_SelectedIndexChanged);
    this.automationDocGroups.Add(new Tuple<int, string>(0, "Report"));
    this.automationDocGroups.Add(new Tuple<int, string>(1, "Policy Document"));
    this.cmbReportType.DataSource = (object) this.automationDocGroups;
    this.cmbReportType.ValueMember = "Item1";
    this.cmbReportType.DisplayMember = "Item2";
    this.cmbReportType.SelectedIndexChanged += new EventHandler(this.cmbReportType_SelectedIndexChanged);
  }

  private void newReportToolStripMenuItem_Click(object sender, EventArgs e)
  {
    if (!this._report.Saved && MessageBox.Show("Report was not saved to the database. Are you sure you want to quit and lose all changes?", "Not Saved", MessageBoxButtons.YesNo) != DialogResult.Yes)
      return;
    this._report = new AdHocReport();
    this.ucPermissions1.InitPermissions(this._report);
    this.SetUpBindings();
  }

  private void btnSave_Click(object sender, EventArgs e)
  {
    if (!this.LargeDataExportValidation(true) || !this.ReportControlsValidation() || !this._report.Save())
      return;
    string text = $"Report '{this._report.ReportName}' saved successfully.";
    this.ucPermissions1.InitPermissions(this._report);
    if (!this.ucPermissions1.isPermissionSet())
    {
      int num = (int) MessageBox.Show(text + "\nHowever execution permissions does not allow to run this report by any user except administrator. Please set permissions.", "Report Saved", MessageBoxButtons.OK);
    }
    else
    {
      this.ucPermissions1.UpdateSecurityResourceName();
      AutoClosingMessageBox.Show(text, "Report Saved", 1000);
    }
  }

  private void frmAdHocReports_FormClosing(object sender, FormClosingEventArgs e)
  {
    if (this._report == null || this._report.Saved || MessageBox.Show("Report was not saved to the database. Are you sure you want to quit and lose all changes?", "Not Saved", MessageBoxButtons.YesNo) == DialogResult.Yes)
      return;
    e.Cancel = true;
  }

  private void tabControl1_SelectedIndexChanged(object sender, EventArgs e)
  {
    this.PopulateParamsDropDown();
  }

  private void toolStripButton1_Click(object sender, EventArgs e)
  {
    if (this.txtSQL.Text.Length <= 6)
      return;
    this._report.Save();
    Type reportType = this._report.ReportType;
    if (this.IsAutoDoc)
    {
      frmControlNo frmControlNo = new frmControlNo(this.IsRequireQuoteOptions);
      if (frmControlNo.ShowDialog() != DialogResult.OK)
        return;
      IQuoteDocument objectEx = ObjectFactory.Instance.CreateObjectEX(this._report.ReportType, (object) this._report.GUID, (object) frmControlNo.QuoteGuid) as IQuoteDocument;
      if (objectEx.RequiresQuoteOptionGuids())
        objectEx.SetQuoteOptionGuids(frmControlNo.QuoteOptionGuids);
      SectionReport report = objectEx as SectionReport;
      report.Run();
      new frmPrint(report).Show();
      SubReport subReport = new SubReport();
    }
    else
    {
      frmGenericReportLauncher genericReportLauncher = new frmGenericReportLauncher(reportType, "Test", this._report.getReportControls, this._report.GUID);
      genericReportLauncher.ShowInTaskbar = false;
      genericReportLauncher.AutoScroll = true;
      genericReportLauncher.MdiParent = MDIControls.Instance.MDIParent;
      try
      {
        genericReportLauncher.Show();
      }
      catch (Exception ex)
      {
        int num = (int) MessageBox.Show("Error:/r/n" + ex.Message, "Cannot execute report", MessageBoxButtons.OK, MessageBoxIcon.Hand);
      }
    }
  }

  private bool ReportControlsValidation()
  {
    string text = "";
    bool flag = true;
    foreach (DataRow row in (InternalDataCollectionBase) this._report.Criteria.Rows)
    {
      if (row["CriteriaID"] != null)
      {
        if (row["ReturnType1"] != null && row["SQLParam1Name"] == null)
          text = $"{text}Return value for criteria '{row["Description"].ToString()}' has not assigned to SQL parameter. \r\n";
        if (row["ReturnType2"] != null && row["SQLParam2Name"] == null)
          text = $"{text}Second return value for criteria '{row["Description"].ToString()}' has not assigned to SQL parameter. \r\n";
      }
    }
    List<string> stringList = new List<string>();
    foreach (DataRow row in (InternalDataCollectionBase) new lstAdHocControls().GetAdHocControls("", 500, this._report.DocumentAutomationGroup).Rows)
      stringList.Add(row["ControlID"].ToString());
    foreach (DataRow row in (InternalDataCollectionBase) this._report.Criteria.Rows)
    {
      if (row["CriteriaID"] != null && !stringList.Contains(row["CriteriaID"].ToString()))
        text = $"{text}Criteria '{row["Description"].ToString().Substring(0, row["Description"].ToString().IndexOf('('))}' is not valid for choosen report type. \r\n";
    }
    if (text != "")
    {
      int num = (int) MessageBox.Show(text, "Criteria problems", MessageBoxButtons.OK, MessageBoxIcon.Hand);
      flag = false;
    }
    return flag;
  }

  private void btnAddCriteria_Click(object sender, EventArgs e)
  {
    frmAddCriteria frmAddCriteria = new frmAddCriteria(this._report.DocumentAutomationGroup);
    if (frmAddCriteria.ShowDialog((IWin32Window) this) != DialogResult.OK)
      return;
    string[] strArray = frmAddCriteria.ResultCriteria.Split(';');
    DataRow row = this._report.Criteria.NewRow();
    object obj1 = this._report.Criteria.Compute("max(LineNo)", string.Empty);
    object obj2 = !obj1.Equals((object) DBNull.Value) ? (object) ((int) obj1 + 1) : (object) 0;
    row["LineNo"] = (object) (int) obj2;
    row["Description"] = (object) strArray[1];
    row["CriteriaID"] = (object) strArray[0];
    row["ReturnType1"] = (object) strArray[13];
    row["ReturnType2"] = (object) strArray[14];
    row["ParametersCount"] = (object) strArray[2];
    this._report.Criteria.Rows.Add(row);
    this.OrganizeCriteriaGV();
    this.gvCriteria.Rows[this.gvCriteria.Rows.Count - 1].Selected = true;
    this.EditCriterion(this.gvCriteria.Rows[this.gvCriteria.Rows.Count - 1]);
  }

  private void tabPage2_Enter(object sender, EventArgs e) => this.OrganizeCriteriaGV();

  private void ddbParams_DropDownItemClicked(object sender, ToolStripItemClickedEventArgs e)
  {
    if (e.ClickedItem.Text == "<ERROR>")
    {
      int num = (int) MessageBox.Show("Error in parameter name. Please return to 'Criteria' tab to fix it.", "Error", MessageBoxButtons.OK);
    }
    else
      this.txtSQL.SelectedText = e.ClickedItem.Text;
  }

  private void ddbParamsSubTitle_DropDownItemClicked(object sender, ToolStripItemClickedEventArgs e)
  {
    if (e.ClickedItem.Text == "<ERROR>")
    {
      int num = (int) MessageBox.Show("Error in parameter name. Please return to 'Criteria' tab to fix it.", "Error", MessageBoxButtons.OK);
    }
    else
      this.txtSubTitle.SelectedText = e.ClickedItem.Text;
  }

  private void toFileToolStripMenuItem_Click(object sender, EventArgs e)
  {
    this.saveFileDialog1.Filter = "IMS AdHoc Reports|*.imsr|All Files|*.*";
    this.saveFileDialog1.DefaultExt = "*.imsr";
    if (this.saveFileDialog1.ShowDialog() != DialogResult.OK)
      return;
    this._report.SaveToFile(this.saveFileDialog1.FileName);
  }

  private void btnDelCriteria_Click(object sender, EventArgs e)
  {
    if (this.gvCriteria.CurrentRow == null)
      return;
    this.gvCriteria.Rows.Remove(this.gvCriteria.CurrentRow);
  }

  private void btnMoveUpCriteria_Click(object sender, EventArgs e)
  {
    if (this.gvCriteria.CurrentRow == null || this.gvCriteria.CurrentRow.Index == 0)
      return;
    int num1 = (int) this.gvCriteria.Rows[this.gvCriteria.CurrentRow.Index].Cells["LineNo"].Value;
    int num2 = (int) this.gvCriteria.Rows[this.gvCriteria.CurrentRow.Index - 1].Cells["LineNo"].Value;
    DataRow dataRow1 = this._report.Criteria.Select(" LineNo=" + num1.ToString())[0];
    DataRow dataRow2 = this._report.Criteria.Select(" LineNo=" + num2.ToString())[0];
    dataRow1["LineNo"] = (object) num2;
    // ISSUE: variable of a boxed type
    __Boxed<int> local = (System.ValueType) num1;
    dataRow2["LineNo"] = (object) local;
    this.gvCriteria.Sort(this.gvCriteria.Columns["LineNo"], ListSortDirection.Ascending);
    this.gvCriteria.Refresh();
  }

  private void btnMoveDnCriteria_Click(object sender, EventArgs e)
  {
    if (this.gvCriteria.CurrentRow == null || this.gvCriteria.CurrentRow.Index == this.gvCriteria.Rows.Count - 1)
      return;
    int num1 = (int) this.gvCriteria.Rows[this.gvCriteria.CurrentRow.Index].Cells["LineNo"].Value;
    int num2 = (int) this.gvCriteria.Rows[this.gvCriteria.CurrentRow.Index + 1].Cells["LineNo"].Value;
    DataRow dataRow1 = this._report.Criteria.Select(" LineNo=" + num1.ToString())[0];
    DataRow dataRow2 = this._report.Criteria.Select(" LineNo=" + num2.ToString())[0];
    dataRow1["LineNo"] = (object) num2;
    // ISSUE: variable of a boxed type
    __Boxed<int> local = (System.ValueType) num1;
    dataRow2["LineNo"] = (object) local;
    this.gvCriteria.Sort(this.gvCriteria.Columns["LineNo"], ListSortDirection.Ascending);
    this.gvCriteria.Refresh();
  }

  private void exportToSQLToolStripMenuItem_Click(object sender, EventArgs e)
  {
    this.saveFileDialog1.Filter = "SQL Files|*.sql|All Files|*.*";
    this.saveFileDialog1.DefaultExt = "*.sql";
    if (this.saveFileDialog1.ShowDialog() != DialogResult.OK)
      return;
    this._report.ExportToSQL(this.saveFileDialog1.FileName);
  }

  private void createToolStripMenuItem_Click(object sender, EventArgs e)
  {
    if (MessageBox.Show("This will create a copy of the current report in the database with the new Guid. Do you want this?", "Copy report?", MessageBoxButtons.YesNo) != DialogResult.Yes)
      return;
    this._report.Duplicate();
  }

  private void deleteReportToolStripMenuItem_Click(object sender, EventArgs e)
  {
    int num = (int) new frmDeleteReport(this.ucPermissions1).ShowDialog((IWin32Window) this);
  }

  private void txtSubTitle_Leave(object sender, EventArgs e)
  {
    this.ddbParamsSubTitle.Visible = false;
  }

  private void txtSubTitle_Enter(object sender, EventArgs e)
  {
    this.ddbParamsSubTitle.Visible = true;
  }

  private void tabPage2_Click(object sender, EventArgs e) => this.OrganizeCriteriaGV();

  private void txtSQL_Enter(object sender, EventArgs e) => this.ddbParams.Visible = true;

  private void txtSQL_Leave(object sender, EventArgs e) => this.ddbParams.Visible = false;

  private void gvCriteria_CellClick(object sender, DataGridViewCellEventArgs e)
  {
    DataGridView dataGridView = (DataGridView) sender;
    if (e.ColumnIndex < 0 || !(dataGridView.Columns[e.ColumnIndex] is DataGridViewButtonColumn) || e.RowIndex < 0)
      return;
    this.EditCriterion(dataGridView.Rows[e.RowIndex]);
  }

  private void loadReportFromFileToolStripMenuItem_Click(object sender, EventArgs e)
  {
    if (this.openFileDialog1.ShowDialog() != DialogResult.OK)
      return;
    this._report.ReadFromFile(this.openFileDialog1.FileName);
    this.ucPermissions1.InitPermissions(this._report);
    this.SetUpBindings();
    this.PopulateParamsDropDown();
    this.SetupVisualElements();
  }

  private void cmbReportType_SelectedIndexChanged(object sender, EventArgs e)
  {
    this.SetupVisualElements();
  }

  private void thisReportOnlyToolStripMenuItem_Click(object sender, EventArgs e)
  {
    int num = (int) new frmAdHocHistory(this._report.GUID, this._report.ReportName).ShowDialog();
  }

  private void allAdHocReportsToolStripMenuItem_Click(object sender, EventArgs e)
  {
    int num = (int) new frmAdHocHistory().ShowDialog();
  }

  private void btnEditLayout_Click(object sender, EventArgs e)
  {
    if (this._report.SQL == null || this._report.SQL == "")
    {
      int num = (int) MessageBox.Show((IWin32Window) MDIControls.Instance.MDIParent, "Please define SQL first.", "Layout Editor", MessageBoxButtons.OK);
    }
    else
    {
      if (MessageBox.Show((IWin32Window) MDIControls.Instance.MDIParent, "Defining layout will render useless following settings:\n Report Subtitle\n Report Title\n Column widths\n Summary Fields\n Margins\n Paper Orientation \nAll of these settings should be redefined in te layout editor.", "Layout Editor", MessageBoxButtons.OKCancel) == DialogResult.Cancel)
        return;
      this._layout = this._report.Layout;
      if (this._layout.Trim() == "")
        this._layout = "<?xml version=\"1.0\" encoding=\"utf-8\"?><ActiveReportsLayout Version=\"3.2\" PrintWidth=\"9360\" DocumentName=\"ActiveReports Document\" ScriptLang=\"C#\" MasterReport=\"0\"><StyleSheet><Style Name=\"Normal\" Value=\"font-family: Arial; font-style: normal; text-decoration: none; font-weight: normal; font-size: 10pt; color: Black; text-align: left; vertical-align: top; ddo-char-set: 1\" /><Style Name=\"Heading1\" Value=\"font-family: Arial; font-size: 16pt; font-style: normal; font-weight: bold\" /><Style Name=\"Heading2\" Value=\"font-family: Times New Roman; font-size: 14pt; font-style: italic; font-weight: bold\" /><Style Name=\"Heading3\" Value=\"font-family: Arial; font-size: 13pt; font-style: normal; font-weight: bold\" /></StyleSheet><Sections><Section Type=\"PageHeader\" Name=\"PageHeader\" Height=\"360\" BackColor=\"16777215\" /><Section Type=\"Detail\" Name=\"Detail\" Height=\"2880\" BackColor=\"16777215\" /><Section Type=\"PageFooter\" Name=\"PageFooter\" Height=\"360\" BackColor=\"16777215\" /></Sections><ReportComponentTray /><PageSettings /><Parameters /></ActiveReportsLayout>";
      string strDataSetNode = this.GenDataset();
      if (strDataSetNode == null)
        return;
      XmlDocument xmlDocument = new XmlDocument();
      if (this.chkAutoGen.Checked && this._AutoGeneratedLayout != "")
        this._layout = this._AutoGeneratedLayout;
      XmlDocument layout = this.AddDataSourceToLayout(this._layout, strDataSetNode);
      string str = $"{Path.GetTempPath()}{this._report.GUID.ToString()}.rpx";
      if (File.Exists(str))
        File.Delete(str);
      layout.Save(str);
      Process process = new Process();
      process.StartInfo.FileName = this.VisualStudioDevEnvPath;
      process.StartInfo.Arguments = str;
      process.Start();
      process.WaitForExit();
      StreamReader txtReader = new StreamReader(str, Encoding.GetEncoding("utf-16"));
      layout.Load((TextReader) txtReader);
      this._report.Layout = this.RemoveDataSourceFromLayout(layout);
      this._report.Save();
      this.btnRemoveLayout.Enabled = this._report.isLayoutDefined;
      this.chkAutoGen.Checked = !this.btnRemoveLayout.Enabled;
      this.chkAutoGen.Enabled = !this.btnRemoveLayout.Enabled;
    }
  }

  private string RemoveDataSourceFromLayout(XmlDocument xmLayout)
  {
    XmlNode oldChild = xmLayout.DocumentElement.SelectSingleNode("//DataSources");
    if (oldChild != null)
      xmLayout.DocumentElement.RemoveChild(oldChild);
    return xmLayout.OuterXml;
  }

  private void chkScreen_CheckedChanged(object sender, EventArgs e)
  {
    if (!this.LargeDataExportValidation(false))
    {
      this.chkScreen.Checked = false;
      int num = (int) MessageBox.Show("Large Data cannot be displayed - only exported. Please uncheck 'Large Export' on the 'Misc' tab. \r\n", "Large Data Export limitations", MessageBoxButtons.OK, MessageBoxIcon.Hand);
    }
    else
      this.SetupVisualElements();
  }

  private void chkThreaded_CheckedChanged(object sender, EventArgs e)
  {
    this.LargeDataExportValidation(false);
  }

  private void loadReportToolStripMenuItem_Click(object sender, EventArgs e)
  {
    frmLoadReport frmLoadReport = new frmLoadReport();
    if (frmLoadReport.ShowDialog((IWin32Window) this) != DialogResult.OK)
      return;
    this._report = new AdHocReport(frmLoadReport.ResultGuid);
    this.SetUpBindings();
    this.ucPermissions1.InitPermissions(this._report);
    this.PopulateParamsDropDown();
    this.SetupVisualElements();
  }

  private void pnlEditLayout_VisibleChanged(object sender, EventArgs e)
  {
    this.btnRemoveLayout.Enabled = this._report.isLayoutDefined;
  }

  private void btnRemoveLayout_Click(object sender, EventArgs e)
  {
    if (MessageBox.Show("Layout cannot be restored later. Deleting layout is permanent and irreversable.\n\nDo you want to continue?", "Deleting Layout", MessageBoxButtons.YesNo, MessageBoxIcon.Exclamation) == DialogResult.Yes)
      this._report.Layout = "";
    this.btnRemoveLayout.Enabled = this._report.isLayoutDefined;
    this.chkAutoGen.Checked = !this.btnRemoveLayout.Enabled;
    this.chkAutoGen.Enabled = !this.btnRemoveLayout.Enabled;
  }

  private void chkLargeExport_CheckedChanged(object sender, EventArgs e)
  {
    bool Verbose = this.chkLargeExport.Tag.ToString() == "1";
    this.chkLargeExport.Tag = (object) "1";
    if (!this.chkLargeExport.Checked)
    {
      this.label8.Enabled = true;
      this.txtSumFields.Enabled = true;
      this.LargeDataExportValidation(false);
    }
    else if (this.LargeDataExportValidation(Verbose))
    {
      this.label8.Enabled = false;
      this.txtSumFields.Enabled = false;
    }
    else
      this.chkLargeExport.Checked = false;
  }

  private void EnableControls()
  {
    this.txtName.Enabled = true;
    foreach (Control control in (ArrangedElementCollection) this.tabPage1.Controls)
    {
      if (!control.Enabled)
        control.Enabled = true;
    }
    foreach (Control control in (ArrangedElementCollection) this.panel3.Controls)
    {
      if (!control.Enabled)
        control.Enabled = true;
    }
    foreach (Control control in (ArrangedElementCollection) this.tabPage3.Controls)
    {
      if (!control.Enabled)
        control.Enabled = true;
    }
  }

  private void DisableControls()
  {
    this.txtName.Enabled = false;
    foreach (Control control in (ArrangedElementCollection) this.Controls)
    {
      if (control.Name.IndexOf("menu") < 0)
        control.Enabled = false;
    }
  }

  private bool LargeDataExportValidation(bool Verbose)
  {
    string text = "";
    bool flag = true;
    this.errError.Clear();
    this.errRecommend.Clear();
    if (!this.chkLargeExport.Checked)
      return flag;
    if (this.chkScreen.Checked)
    {
      string str = "Large Data cannot be displayed - only exported.";
      text = $"{text}{str} Please uncheck 'Report Screen Output' on the 'Report Properties' tab. \r\n";
      this.errError.SetError((Control) this.chkScreen, str);
      this.errError.SetError((Control) this.chkLargeExport, str);
      flag = false;
    }
    if (!this.chkThreaded.Checked)
    {
      string str = "Please check 'Is Threaded' on the 'Report Properties' tab. \r\n";
      text += "It is highly recommended to run Large Data reports in threaded mode. Please check 'Is Threaded' on the 'Report Properties' tab. \r\n";
      this.errRecommend.SetError((Control) this.chkThreaded, str);
      if (flag)
        this.errRecommend.SetError((Control) this.chkLargeExport, str);
    }
    if (this.txtSumFields.Text.Trim() != "")
    {
      string str = "Large Data Export reports does not support 'Summary Fields' \r\n";
      text += str;
      this.errRecommend.SetError((Control) this.txtSumFields, str);
    }
    if (Verbose && text != "")
    {
      if (flag)
      {
        int num1 = (int) MessageBox.Show(text, "Large Data Export limitations", MessageBoxButtons.OK, MessageBoxIcon.Asterisk);
      }
      else
      {
        int num2 = (int) MessageBox.Show(text, "Large Data Export limitations", MessageBoxButtons.OK, MessageBoxIcon.Hand);
      }
    }
    return flag;
  }

  private void SetUpBindings()
  {
    this.txtName.DataBindings.Clear();
    this.txtGroup.DataBindings.Clear();
    this.txtDescription.DataBindings.Clear();
    this.txtTitle.DataBindings.Clear();
    this.chkScreen.DataBindings.Clear();
    this.chkPublished.DataBindings.Clear();
    this.txtSQL.DataBindings.Clear();
    this.txtColWidth.DataBindings.Clear();
    this.txtSumFields.DataBindings.Clear();
    this.txtTableNames.DataBindings.Clear();
    this.txtSubTitle.DataBindings.Clear();
    this.txtMarginTop.DataBindings.Clear();
    this.txtMarginBottom.DataBindings.Clear();
    this.txtMarginLeft.DataBindings.Clear();
    this.txtMarginRight.DataBindings.Clear();
    this.rbLandscape.DataBindings.Clear();
    this.rbPortrait.DataBindings.Clear();
    this.chkThreaded.DataBindings.Clear();
    this.chkLargeExport.DataBindings.Clear();
    this.cmbReportType.DataBindings.Clear();
    this.txtName.DataBindings.Add("Text", (object) this._report, "ReportName");
    this.txtGroup.DataBindings.Add("Text", (object) this._report, "GroupName");
    this.txtDescription.DataBindings.Add("Text", (object) this._report, "Description");
    this.txtTitle.DataBindings.Add("Text", (object) this._report, "Title");
    this.chkLargeExport.DataBindings.Add("Checked", (object) this._report, "isLargeExport");
    this.chkScreen.DataBindings.Add("Checked", (object) this._report, "AllowPrint");
    this.chkPublished.DataBindings.Add("Checked", (object) this._report, "Published");
    this.txtSQL.DataBindings.Add("Text", (object) this._report, "SQL");
    this.txtColWidth.DataBindings.Add("Text", (object) this._report, "ColumnWidth");
    this.txtSumFields.DataBindings.Add("Text", (object) this._report, "SummaryFields");
    this.txtTableNames.DataBindings.Add("Text", (object) this._report, "TableNames");
    this.txtSubTitle.DataBindings.Add("Text", (object) this._report, "SubTitle");
    this.txtMarginTop.DataBindings.Add("Text", (object) this._report, "MarginTop");
    this.txtMarginBottom.DataBindings.Add("Text", (object) this._report, "MarginBottom");
    this.txtMarginLeft.DataBindings.Add("Text", (object) this._report, "MarginLeft");
    this.txtMarginRight.DataBindings.Add("Text", (object) this._report, "MarginRight");
    this.rbLandscape.DataBindings.Add("Checked", (object) this._report, "isPaperOrientationLandscape");
    this.rbPortrait.DataBindings.Add("Checked", (object) this._report, "isPaperOrientationPortrait");
    this.chkThreaded.DataBindings.Add("Checked", (object) this._report, "isThreaded");
    this.cmbReportType.DataBindings.Add("SelectedValue", (object) this._report, "DocumentAutomationGroup");
    this.gvCriteria.DataSource = (object) this._report.Criteria;
    this.gvCriteria.Columns["LineNo"].Visible = false;
    this.gvCriteria.Columns["CriteriaID"].Visible = false;
    this.gvCriteria.Columns["ReturnType1"].Visible = false;
    this.gvCriteria.Columns["ReturnType2"].Visible = false;
    this.gvCriteria.Columns["ParametersCount"].Visible = false;
    this.gvCriteria.Columns["Description"].Width = 400;
    this.gvCriteria.Columns["LineNo"].SortMode = DataGridViewColumnSortMode.Automatic;
    this.gvCriteria.Sort(this.gvCriteria.Columns["LineNo"], ListSortDirection.Ascending);
    this.editCriteriaButton.Name = "Edit";
    this.editCriteriaButton.Width = 30;
    this.editCriteriaButton.Text = "...";
    if (this.gvCriteria.Columns["Edit"] == null)
      this.gvCriteria.Columns.Insert(0, (DataGridViewColumn) this.editCriteriaButton);
    this.OrganizeCriteriaGV();
  }

  private void OrganizeCriteriaGV()
  {
    foreach (DataGridViewRow row in (IEnumerable) this.gvCriteria.Rows)
    {
      if (row.Cells["ParametersCount"].Value == null)
        break;
      int num = int.Parse(row.Cells["ParametersCount"].Value.ToString());
      if (num < 1)
      {
        row.Cells["Parameter00"].ReadOnly = true;
        row.Cells["Parameter00"].Style.BackColor = System.Drawing.Color.Gray;
      }
      if (num < 2)
      {
        row.Cells["Parameter01"].ReadOnly = true;
        row.Cells["Parameter01"].Style.BackColor = System.Drawing.Color.Gray;
      }
      if (num < 3)
      {
        row.Cells["Parameter02"].ReadOnly = true;
        row.Cells["Parameter02"].Style.BackColor = System.Drawing.Color.Gray;
      }
      if (num < 4)
      {
        row.Cells["Parameter03"].ReadOnly = true;
        row.Cells["Parameter03"].Style.BackColor = System.Drawing.Color.Gray;
      }
      if (num < 5)
      {
        row.Cells["Parameter04"].ReadOnly = true;
        row.Cells["Parameter04"].Style.BackColor = System.Drawing.Color.Gray;
      }
      if (num < 6)
      {
        row.Cells["Parameter05"].ReadOnly = true;
        row.Cells["Parameter05"].Style.BackColor = System.Drawing.Color.Gray;
      }
      if (num < 7)
      {
        row.Cells["Parameter06"].ReadOnly = true;
        row.Cells["Parameter06"].Style.BackColor = System.Drawing.Color.Gray;
      }
      if (num < 8)
      {
        row.Cells["Parameter07"].ReadOnly = true;
        row.Cells["Parameter07"].Style.BackColor = System.Drawing.Color.Gray;
      }
      if (num < 9)
      {
        row.Cells["Parameter08"].ReadOnly = true;
        row.Cells["Parameter08"].Style.BackColor = System.Drawing.Color.Gray;
      }
      if (num < 10)
      {
        row.Cells["Parameter09"].ReadOnly = true;
        row.Cells["Parameter09"].Style.BackColor = System.Drawing.Color.Gray;
      }
      if (row.Cells["ReturnType2"].Value.Equals((object) DBNull.Value) || row.Cells["ReturnType2"].Value.ToString() == "")
      {
        row.Cells["SQLParam2Name"].ReadOnly = true;
        row.Cells["SQLParam2Name"].Style.BackColor = System.Drawing.Color.Gray;
      }
    }
  }

  private void PopulateParamsDropDown()
  {
    try
    {
      SqlCommand cmd = new SqlCommand(this._report.SQL.Trim(), new SqlConnection(DefaultDatabase.ConnectionString));
      if (cmd.CommandText.Substring(0, 6).ToUpper() == "SELECT")
        cmd.CommandType = CommandType.Text;
      else
        cmd.CommandType = CommandType.StoredProcedure;
      if (cmd.Connection.State != ConnectionState.Open)
        cmd.Connection.Open();
      this.DeriveParameters(cmd);
      cmd.Connection.Close();
      this.ddbParams.DropDownItems.Clear();
      this.ddbParamsSubTitle.DropDownItems.Clear();
      this._ReturnParameters.Clear();
      foreach (SqlParameter parameter in (DbParameterCollection) cmd.Parameters)
      {
        this.ddbParams.DropDownItems.Add(parameter.ParameterName);
        this.ddbParamsSubTitle.DropDownItems.Add(parameter.ParameterName);
        this._ReturnParameters.Add(parameter.ParameterName);
      }
    }
    catch (Exception ex)
    {
    }
  }

  private SqlParameterCollection DeriveParameters(SqlCommand cmd)
  {
    if (cmd.CommandType == CommandType.StoredProcedure)
    {
      SqlCommandBuilder.DeriveParameters(cmd);
      cmd.Parameters.RemoveAt(cmd.Parameters.IndexOf("@RETURN_VALUE"));
    }
    else
    {
      cmd.Parameters.Clear();
      int startIndex1 = 0;
      string commandText = cmd.CommandText;
      char[] anyOf = new char[4]{ ' ', '=', ',', ')' };
      int startIndex2;
      for (; commandText.IndexOf("@", startIndex1) > 0; startIndex1 = startIndex2 + 1)
      {
        startIndex2 = commandText.IndexOf("@", startIndex1);
        int num = commandText.IndexOfAny(anyOf, startIndex2);
        if (num < 1)
          num = commandText.Length;
        string str = commandText.Substring(startIndex2, num - startIndex2);
        SqlParameter sqlParameter = new SqlParameter();
        sqlParameter.ParameterName = str;
        if (!cmd.Parameters.Contains(str) && str != "@RETURN_VALUE")
          cmd.Parameters.Add(sqlParameter);
      }
    }
    return cmd.Parameters;
  }

  private XmlDocument AddDataSourceToLayout(string _layout, string strDataSetNode)
  {
    if (strDataSetNode == null)
      return (XmlDocument) null;
    XmlDocument layout = new XmlDocument();
    layout.LoadXml(_layout);
    XmlNode lastChild = layout.DocumentElement.LastChild;
    XmlNode node = layout.CreateNode(XmlNodeType.Element, "DataSources", (string) null);
    XmlElement element = layout.CreateElement("SqlDbDataSource");
    element.SetAttribute("Connect", DefaultDatabase.ConnectionString);
    element.SetAttribute("SQL", strDataSetNode);
    node.AppendChild((XmlNode) element);
    layout.DocumentElement.InsertAfter(node, lastChild);
    return layout;
  }

  private void EditCriterion(DataGridViewRow dgr)
  {
    int num = (int) new frmEditCriteria((dgr.DataBoundItem as DataRowView).Row, this._report.DocumentAutomationGroup)
    {
      ReturnParameters = this._ReturnParameters.ToArray()
    }.ShowDialog();
  }

  private string GetLatestVS()
  {
    foreach (Version version in new List<Version>()
    {
      new Version("14.0"),
      new Version("13.0"),
      new Version("12.0"),
      new Version("11.0"),
      new Version("10.0")
    })
    {
      string latestVs = !Environment.Is64BitOperatingSystem ? (string) Registry.GetValue($"HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\VisualStudio\\{version.Major}.{version.Minor}\\", "InstallDir", (object) null) : (string) Registry.GetValue($"HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Microsoft\\VisualStudio\\{version.Major}.{version.Minor}\\", "InstallDir", (object) null);
      if (latestVs != null)
        return latestVs;
    }
    return "";
  }

  private bool isGrapeCityInstalled()
  {
    return (!Environment.Is64BitOperatingSystem ? RegistryKey.OpenBaseKey(RegistryHive.CurrentUser, RegistryView.Registry32) : RegistryKey.OpenBaseKey(RegistryHive.CurrentUser, RegistryView.Registry64)).OpenSubKey("Software\\GrapeCity\\ActiveReports") != null;
  }

  private string GenDataset()
  {
    this._report.Save();
    Type reportType = typeof (AdHocReportDisplay);
    string str1 = "";
    BaseReportControl[] getReportControls = this._report.getReportControls;
    Guid guid = this._report.GUID;
    frmAdHocReportLauncher hocReportLauncher = new frmAdHocReportLauncher(reportType, "Gathering Data for Designer", getReportControls, guid);
    hocReportLauncher.ShowInTaskbar = false;
    hocReportLauncher.AutoScroll = true;
    if (hocReportLauncher.ShowDialog() == DialogResult.Cancel)
      return (string) null;
    SqlCommand sqlCommand = hocReportLauncher.SQLCommand;
    this._AutoGeneratedLayout = hocReportLauncher.Layout;
    string str2 = sqlCommand.CommandText;
    if (sqlCommand.CommandType == CommandType.StoredProcedure)
    {
      foreach (SqlParameter parameter in (DbParameterCollection) sqlCommand.Parameters)
      {
        if (parameter.Value != null)
          str1 = $"{str1}{parameter.ParameterName}={this.FormatSqlParameter(parameter.Value.ToString(), parameter.DbType.ToString())}, ";
      }
      hocReportLauncher.Dispose();
      if (str1.Length > 2)
        str1 = str1.Substring(0, str1.Length - 2);
      return $"{str2} {str1}";
    }
    foreach (SqlParameter parameter in (DbParameterCollection) sqlCommand.Parameters)
    {
      if (parameter.Value != null)
        str2 = str2.Replace(parameter.ParameterName, this.FormatSqlParameter(parameter.Value.ToString(), parameter.DbType.ToString()));
    }
    return str2;
  }

  private string FormatSqlParameter(string strParameterValue, string strParameterType)
  {
    return !(strParameterType.ToLower() == "boolean") ? $"'{strParameterValue.Trim()}'" : (strParameterValue.Trim().ToLower() == "true" || strParameterValue.Trim() == "1" ? "1" : "0");
  }

  private bool IsSQLText => !(this.txtSQL.Text.Substring(0, 6).ToUpper() != "SELECT");

  private bool IsAutoDoc => (int) this.cmbReportType.SelectedValue == 1;

  private bool IsRequireQuoteOptions
  {
    get
    {
      foreach (DataRow row in (InternalDataCollectionBase) this._report.Criteria.Rows)
      {
        if (row["CriteriaID"].ToString() == "201")
          return true;
      }
      return false;
    }
  }

  protected override void Dispose(bool disposing)
  {
    if (disposing && this.components != null)
      this.components.Dispose();
    base.Dispose(disposing);
  }

  private void InitializeComponent()
  {
    this.components = (IContainer) new System.ComponentModel.Container();
    ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (frmAdHocReportManager));
    this.menuStrip1 = new MenuStrip();
    this.reportToolStripMenuItem = new ToolStripMenuItem();
    this.newReportToolStripMenuItem = new ToolStripMenuItem();
    this.loadReportToolStripMenuItem = new ToolStripMenuItem();
    this.loadReportFromFileToolStripMenuItem = new ToolStripMenuItem();
    this.saToolStripMenuItem = new ToolStripMenuItem();
    this.toDatabaseToolStripMenuItem = new ToolStripMenuItem();
    this.toFileToolStripMenuItem = new ToolStripMenuItem();
    this.deleteReportToolStripMenuItem = new ToolStripMenuItem();
    this.exportToSQLToolStripMenuItem = new ToolStripMenuItem();
    this.editToolStripMenuItem = new ToolStripMenuItem();
    this.createToolStripMenuItem = new ToolStripMenuItem();
    this.historyToolStripMenuItem = new ToolStripMenuItem();
    this.thisReportOnlyToolStripMenuItem = new ToolStripMenuItem();
    this.allAdHocReportsToolStripMenuItem = new ToolStripMenuItem();
    this.panel1 = new Panel();
    this.txtName = new TextBox();
    this.label1 = new Label();
    this.tabControl1 = new TabControl();
    this.tabPage1 = new TabPage();
    this.label21 = new Label();
    this.cmbReportType = new ComboBox();
    this.chkThreaded = new CheckBox();
    this.label19 = new Label();
    this.label10 = new Label();
    this.txtSubTitle = new TextBox();
    this.txtTitle = new TextBox();
    this.label6 = new Label();
    this.chkPublished = new CheckBox();
    this.label5 = new Label();
    this.label4 = new Label();
    this.chkScreen = new CheckBox();
    this.txtDescription = new TextBox();
    this.txtGroup = new TextBox();
    this.label3 = new Label();
    this.label2 = new Label();
    this.tabPage3 = new TabPage();
    this.txtSQL = new TextBox();
    this.tabPage2 = new TabPage();
    this.gvCriteria = new DataGridView();
    this.dataGridView1 = new DataGridView();
    this.panel3 = new Panel();
    this.btnMoveUpCriteria = new Button();
    this.btnMoveDnCriteria = new Button();
    this.btnDelCriteria = new Button();
    this.btnAddCriteria = new Button();
    this.tabPage4 = new TabPage();
    this.chkLargeExport = new CheckBox();
    this.label20 = new Label();
    this.pnlEditLayout = new Panel();
    this.chkAutoGen = new CheckBox();
    this.btnRemoveLayout = new Button();
    this.btnEditLayout = new Button();
    this.rbLandscape = new RadioButton();
    this.rbPortrait = new RadioButton();
    this.label16 = new Label();
    this.txtMarginRight = new TextBox();
    this.txtMarginLeft = new TextBox();
    this.txtMarginBottom = new TextBox();
    this.label15 = new Label();
    this.label14 = new Label();
    this.label13 = new Label();
    this.label12 = new Label();
    this.txtMarginTop = new TextBox();
    this.label11 = new Label();
    this.label9 = new Label();
    this.txtTableNames = new TextBox();
    this.label17 = new Label();
    this.txtSumFields = new TextBox();
    this.label8 = new Label();
    this.txtColWidth = new TextBox();
    this.label7 = new Label();
    this.tabPage5 = new TabPage();
    this.ucPermissions1 = new ucPermissions();
    this.saveFileDialog1 = new SaveFileDialog();
    this.openFileDialog1 = new OpenFileDialog();
    this.toolStrip1 = new ToolStrip();
    this.toolStripButton1 = new ToolStripButton();
    this.ddbParams = new ToolStripDropDownButton();
    this.ddbParamsSubTitle = new ToolStripDropDownButton();
    this.panelBottom = new Panel();
    this.btnSave = new Button();
    this.toolTip1 = new ToolTip(this.components);
    this.errError = new ErrorProvider(this.components);
    this.errRecommend = new ErrorProvider(this.components);
    this.menuStrip1.SuspendLayout();
    this.panel1.SuspendLayout();
    this.tabControl1.SuspendLayout();
    this.tabPage1.SuspendLayout();
    this.tabPage3.SuspendLayout();
    this.tabPage2.SuspendLayout();
    ((ISupportInitialize) this.gvCriteria).BeginInit();
    ((ISupportInitialize) this.dataGridView1).BeginInit();
    this.panel3.SuspendLayout();
    this.tabPage4.SuspendLayout();
    this.pnlEditLayout.SuspendLayout();
    this.tabPage5.SuspendLayout();
    this.toolStrip1.SuspendLayout();
    this.panelBottom.SuspendLayout();
    ((ISupportInitialize) this.errError).BeginInit();
    ((ISupportInitialize) this.errRecommend).BeginInit();
    this.SuspendLayout();
    this.menuStrip1.Items.AddRange(new ToolStripItem[3]
    {
      (ToolStripItem) this.reportToolStripMenuItem,
      (ToolStripItem) this.editToolStripMenuItem,
      (ToolStripItem) this.historyToolStripMenuItem
    });
    this.menuStrip1.Location = new Point(0, 0);
    this.menuStrip1.Name = "menuStrip1";
    this.menuStrip1.Size = new Size(835, 24);
    this.menuStrip1.TabIndex = 0;
    this.menuStrip1.Text = "menuStrip1";
    this.reportToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[6]
    {
      (ToolStripItem) this.newReportToolStripMenuItem,
      (ToolStripItem) this.loadReportToolStripMenuItem,
      (ToolStripItem) this.loadReportFromFileToolStripMenuItem,
      (ToolStripItem) this.saToolStripMenuItem,
      (ToolStripItem) this.deleteReportToolStripMenuItem,
      (ToolStripItem) this.exportToSQLToolStripMenuItem
    });
    this.reportToolStripMenuItem.Name = "reportToolStripMenuItem";
    this.reportToolStripMenuItem.Size = new Size(54, 20);
    this.reportToolStripMenuItem.Text = "Report";
    this.newReportToolStripMenuItem.Name = "newReportToolStripMenuItem";
    this.newReportToolStripMenuItem.Size = new Size(218, 22);
    this.newReportToolStripMenuItem.Text = "New Report";
    this.newReportToolStripMenuItem.Click += new EventHandler(this.newReportToolStripMenuItem_Click);
    this.loadReportToolStripMenuItem.Name = "loadReportToolStripMenuItem";
    this.loadReportToolStripMenuItem.Size = new Size(218, 22);
    this.loadReportToolStripMenuItem.Text = "Load Report from Database";
    this.loadReportToolStripMenuItem.Click += new EventHandler(this.loadReportToolStripMenuItem_Click);
    this.loadReportFromFileToolStripMenuItem.Name = "loadReportFromFileToolStripMenuItem";
    this.loadReportFromFileToolStripMenuItem.Size = new Size(218, 22);
    this.loadReportFromFileToolStripMenuItem.Text = "Load Report from File";
    this.loadReportFromFileToolStripMenuItem.Click += new EventHandler(this.loadReportFromFileToolStripMenuItem_Click);
    this.saToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[2]
    {
      (ToolStripItem) this.toDatabaseToolStripMenuItem,
      (ToolStripItem) this.toFileToolStripMenuItem
    });
    this.saToolStripMenuItem.Name = "saToolStripMenuItem";
    this.saToolStripMenuItem.Size = new Size(218, 22);
    this.saToolStripMenuItem.Text = "Save";
    this.toDatabaseToolStripMenuItem.Name = "toDatabaseToolStripMenuItem";
    this.toDatabaseToolStripMenuItem.Size = new Size(138, 22);
    this.toDatabaseToolStripMenuItem.Text = "To Database";
    this.toDatabaseToolStripMenuItem.Click += new EventHandler(this.btnSave_Click);
    this.toFileToolStripMenuItem.Name = "toFileToolStripMenuItem";
    this.toFileToolStripMenuItem.Size = new Size(138, 22);
    this.toFileToolStripMenuItem.Text = "To File";
    this.toFileToolStripMenuItem.Click += new EventHandler(this.toFileToolStripMenuItem_Click);
    this.deleteReportToolStripMenuItem.Name = "deleteReportToolStripMenuItem";
    this.deleteReportToolStripMenuItem.Size = new Size(218, 22);
    this.deleteReportToolStripMenuItem.Text = "Delete Report";
    this.deleteReportToolStripMenuItem.Click += new EventHandler(this.deleteReportToolStripMenuItem_Click);
    this.exportToSQLToolStripMenuItem.Name = "exportToSQLToolStripMenuItem";
    this.exportToSQLToolStripMenuItem.Size = new Size(218, 22);
    this.exportToSQLToolStripMenuItem.Text = "Export to SQL";
    this.exportToSQLToolStripMenuItem.Click += new EventHandler(this.exportToSQLToolStripMenuItem_Click);
    this.editToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[1]
    {
      (ToolStripItem) this.createToolStripMenuItem
    });
    this.editToolStripMenuItem.Name = "editToolStripMenuItem";
    this.editToolStripMenuItem.Size = new Size(39, 20);
    this.editToolStripMenuItem.Text = "Edit";
    this.createToolStripMenuItem.Name = "createToolStripMenuItem";
    this.createToolStripMenuItem.Size = new Size(139, 22);
    this.createToolStripMenuItem.Text = "Create Copy";
    this.createToolStripMenuItem.Click += new EventHandler(this.createToolStripMenuItem_Click);
    this.historyToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[2]
    {
      (ToolStripItem) this.thisReportOnlyToolStripMenuItem,
      (ToolStripItem) this.allAdHocReportsToolStripMenuItem
    });
    this.historyToolStripMenuItem.Name = "historyToolStripMenuItem";
    this.historyToolStripMenuItem.Size = new Size(57, 20);
    this.historyToolStripMenuItem.Text = "History";
    this.thisReportOnlyToolStripMenuItem.Enabled = false;
    this.thisReportOnlyToolStripMenuItem.Name = "thisReportOnlyToolStripMenuItem";
    this.thisReportOnlyToolStripMenuItem.Size = new Size(171, 22);
    this.thisReportOnlyToolStripMenuItem.Text = "This report only";
    this.thisReportOnlyToolStripMenuItem.Click += new EventHandler(this.thisReportOnlyToolStripMenuItem_Click);
    this.allAdHocReportsToolStripMenuItem.Name = "allAdHocReportsToolStripMenuItem";
    this.allAdHocReportsToolStripMenuItem.Size = new Size(171, 22);
    this.allAdHocReportsToolStripMenuItem.Text = "All AdHoc Reports";
    this.allAdHocReportsToolStripMenuItem.Click += new EventHandler(this.allAdHocReportsToolStripMenuItem_Click);
    this.panel1.Controls.Add((Control) this.txtName);
    this.panel1.Controls.Add((Control) this.label1);
    this.panel1.Dock = DockStyle.Top;
    this.panel1.Location = new Point(0, 49);
    this.panel1.Name = "panel1";
    this.panel1.Size = new Size(835, 31 /*0x1F*/);
    this.panel1.TabIndex = 1;
    this.txtName.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
    this.txtName.Location = new Point(79, 6);
    this.txtName.Name = "txtName";
    this.txtName.Size = new Size(744, 20);
    this.txtName.TabIndex = 1;
    this.label1.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
    this.label1.AutoSize = true;
    this.label1.Location = new Point(3, 9);
    this.label1.Name = "label1";
    this.label1.Size = new Size(70, 13);
    this.label1.TabIndex = 0;
    this.label1.Text = "Report Name";
    this.tabControl1.Controls.Add((Control) this.tabPage1);
    this.tabControl1.Controls.Add((Control) this.tabPage3);
    this.tabControl1.Controls.Add((Control) this.tabPage2);
    this.tabControl1.Controls.Add((Control) this.tabPage4);
    this.tabControl1.Controls.Add((Control) this.tabPage5);
    this.tabControl1.Dock = DockStyle.Fill;
    this.tabControl1.Location = new Point(0, 80 /*0x50*/);
    this.tabControl1.Name = "tabControl1";
    this.tabControl1.SelectedIndex = 0;
    this.tabControl1.Size = new Size(835, 348);
    this.tabControl1.TabIndex = 2;
    this.tabControl1.SelectedIndexChanged += new EventHandler(this.tabControl1_SelectedIndexChanged);
    this.tabPage1.Controls.Add((Control) this.label21);
    this.tabPage1.Controls.Add((Control) this.cmbReportType);
    this.tabPage1.Controls.Add((Control) this.chkThreaded);
    this.tabPage1.Controls.Add((Control) this.label19);
    this.tabPage1.Controls.Add((Control) this.label10);
    this.tabPage1.Controls.Add((Control) this.txtSubTitle);
    this.tabPage1.Controls.Add((Control) this.txtTitle);
    this.tabPage1.Controls.Add((Control) this.label6);
    this.tabPage1.Controls.Add((Control) this.chkPublished);
    this.tabPage1.Controls.Add((Control) this.label5);
    this.tabPage1.Controls.Add((Control) this.label4);
    this.tabPage1.Controls.Add((Control) this.chkScreen);
    this.tabPage1.Controls.Add((Control) this.txtDescription);
    this.tabPage1.Controls.Add((Control) this.txtGroup);
    this.tabPage1.Controls.Add((Control) this.label3);
    this.tabPage1.Controls.Add((Control) this.label2);
    this.tabPage1.Location = new Point(4, 22);
    this.tabPage1.Name = "tabPage1";
    this.tabPage1.Padding = new Padding(3);
    this.tabPage1.Size = new Size(827, 322);
    this.tabPage1.TabIndex = 0;
    this.tabPage1.Text = "Report Properties";
    this.tabPage1.ToolTipText = "General Report Properties";
    this.tabPage1.UseVisualStyleBackColor = true;
    this.label21.AutoSize = true;
    this.label21.Location = new Point(512 /*0x0200*/, 243);
    this.label21.Name = "label21";
    this.label21.Size = new Size(66, 13);
    this.label21.TabIndex = 17;
    this.label21.Text = "Report Type";
    this.cmbReportType.FormattingEnabled = true;
    this.cmbReportType.Location = new Point(584, 239);
    this.cmbReportType.Name = "cmbReportType";
    this.cmbReportType.Size = new Size(235, 21);
    this.cmbReportType.TabIndex = 16 /*0x10*/;
    this.cmbReportType.SelectedIndexChanged += new EventHandler(this.cmbReportType_SelectedIndexChanged);
    this.chkThreaded.AutoSize = true;
    this.chkThreaded.Location = new Point(133, 286);
    this.chkThreaded.Name = "chkThreaded";
    this.chkThreaded.Size = new Size(286, 17);
    this.chkThreaded.TabIndex = 15;
    this.chkThreaded.Text = "(if checked, report will be generated in separate thread)";
    this.chkThreaded.UseVisualStyleBackColor = true;
    this.chkThreaded.CheckedChanged += new EventHandler(this.chkThreaded_CheckedChanged);
    this.label19.AutoSize = true;
    this.label19.Location = new Point(8, 286);
    this.label19.Name = "label19";
    this.label19.Size = new Size(64 /*0x40*/, 13);
    this.label19.TabIndex = 14;
    this.label19.Text = "Is Threaded";
    this.label10.AutoSize = true;
    this.label10.Location = new Point(8, 165);
    this.label10.Name = "label10";
    this.label10.Size = new Size(77, 13);
    this.label10.TabIndex = 11;
    this.label10.Text = "Report Subtitle";
    this.txtSubTitle.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
    this.txtSubTitle.Location = new Point(133, 162);
    this.txtSubTitle.Multiline = true;
    this.txtSubTitle.Name = "txtSubTitle";
    this.txtSubTitle.Size = new Size(686, 62);
    this.txtSubTitle.TabIndex = 10;
    this.txtSubTitle.Enter += new EventHandler(this.txtSubTitle_Enter);
    this.txtSubTitle.Leave += new EventHandler(this.txtSubTitle_Leave);
    this.txtTitle.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
    this.txtTitle.Location = new Point(133, 98);
    this.txtTitle.Multiline = true;
    this.txtTitle.Name = "txtTitle";
    this.txtTitle.Size = new Size(686, 62);
    this.txtTitle.TabIndex = 9;
    this.label6.AutoSize = true;
    this.label6.Location = new Point(8, 101);
    this.label6.Name = "label6";
    this.label6.Size = new Size(62, 13);
    this.label6.TabIndex = 8;
    this.label6.Text = "Report Title";
    this.chkPublished.AutoSize = true;
    this.chkPublished.Location = new Point(133, 264);
    this.chkPublished.Name = "chkPublished";
    this.chkPublished.Size = new Size(232, 17);
    this.chkPublished.TabIndex = 7;
    this.chkPublished.Text = "(if checked report will be visible to end user)";
    this.chkPublished.UseVisualStyleBackColor = true;
    this.label5.AutoSize = true;
    this.label5.Location = new Point(8, 265);
    this.label5.Name = "label5";
    this.label5.Size = new Size(88, 13);
    this.label5.TabIndex = 6;
    this.label5.Text = "Report Published";
    this.label4.AutoSize = true;
    this.label4.Location = new Point(8, 243);
    this.label4.Name = "label4";
    this.label4.Size = new Size(111, 13);
    this.label4.TabIndex = 5;
    this.label4.Text = "Report Screen Output";
    this.chkScreen.AutoSize = true;
    this.chkScreen.Location = new Point(133, 242);
    this.chkScreen.Name = "chkScreen";
    this.chkScreen.Size = new Size(245, 17);
    this.chkScreen.TabIndex = 4;
    this.chkScreen.Text = "(screen and excel if checked, excel only if not)";
    this.chkScreen.UseVisualStyleBackColor = true;
    this.chkScreen.CheckedChanged += new EventHandler(this.chkScreen_CheckedChanged);
    this.txtDescription.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
    this.txtDescription.Location = new Point(133, 34);
    this.txtDescription.Multiline = true;
    this.txtDescription.Name = "txtDescription";
    this.txtDescription.Size = new Size(686, 62);
    this.txtDescription.TabIndex = 3;
    this.txtGroup.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
    this.txtGroup.Location = new Point(133, 12);
    this.txtGroup.Name = "txtGroup";
    this.txtGroup.Size = new Size(686, 20);
    this.txtGroup.TabIndex = 2;
    this.label3.AutoSize = true;
    this.label3.Location = new Point(8, 37);
    this.label3.Name = "label3";
    this.label3.Size = new Size(95, 13);
    this.label3.TabIndex = 1;
    this.label3.Text = "Report Description";
    this.label2.AutoSize = true;
    this.label2.Location = new Point(8, 15);
    this.label2.Name = "label2";
    this.label2.Size = new Size(71, 13);
    this.label2.TabIndex = 0;
    this.label2.Text = "Report Group";
    this.tabPage3.Controls.Add((Control) this.txtSQL);
    this.tabPage3.Location = new Point(4, 22);
    this.tabPage3.Name = "tabPage3";
    this.tabPage3.Size = new Size(827, 322);
    this.tabPage3.TabIndex = 2;
    this.tabPage3.Text = "SQL";
    this.tabPage3.UseVisualStyleBackColor = true;
    this.txtSQL.Dock = DockStyle.Fill;
    this.txtSQL.Location = new Point(0, 0);
    this.txtSQL.Multiline = true;
    this.txtSQL.Name = "txtSQL";
    this.txtSQL.ScrollBars = ScrollBars.Both;
    this.txtSQL.Size = new Size(827, 322);
    this.txtSQL.TabIndex = 0;
    this.txtSQL.WordWrap = false;
    this.txtSQL.Enter += new EventHandler(this.txtSQL_Enter);
    this.txtSQL.Leave += new EventHandler(this.txtSQL_Leave);
    this.tabPage2.Controls.Add((Control) this.gvCriteria);
    this.tabPage2.Controls.Add((Control) this.dataGridView1);
    this.tabPage2.Controls.Add((Control) this.panel3);
    this.tabPage2.Location = new Point(4, 22);
    this.tabPage2.Name = "tabPage2";
    this.tabPage2.Padding = new Padding(3);
    this.tabPage2.Size = new Size(827, 322);
    this.tabPage2.TabIndex = 1;
    this.tabPage2.Text = "Criteria";
    this.tabPage2.UseVisualStyleBackColor = true;
    this.tabPage2.Click += new EventHandler(this.tabPage2_Click);
    this.tabPage2.Enter += new EventHandler(this.tabPage2_Enter);
    this.gvCriteria.AllowUserToAddRows = false;
    this.gvCriteria.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
    this.gvCriteria.Dock = DockStyle.Fill;
    this.gvCriteria.Location = new Point(3, 3);
    this.gvCriteria.MultiSelect = false;
    this.gvCriteria.Name = "gvCriteria";
    this.gvCriteria.Size = new Size(821, 279);
    this.gvCriteria.TabIndex = 2;
    this.gvCriteria.CellClick += new DataGridViewCellEventHandler(this.gvCriteria_CellClick);
    this.dataGridView1.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
    this.dataGridView1.Dock = DockStyle.Fill;
    this.dataGridView1.Location = new Point(3, 3);
    this.dataGridView1.Name = "dataGridView1";
    this.dataGridView1.Size = new Size(821, 279);
    this.dataGridView1.TabIndex = 1;
    this.panel3.Controls.Add((Control) this.btnMoveUpCriteria);
    this.panel3.Controls.Add((Control) this.btnMoveDnCriteria);
    this.panel3.Controls.Add((Control) this.btnDelCriteria);
    this.panel3.Controls.Add((Control) this.btnAddCriteria);
    this.panel3.Dock = DockStyle.Bottom;
    this.panel3.Location = new Point(3, 282);
    this.panel3.Name = "panel3";
    this.panel3.Size = new Size(821, 37);
    this.panel3.TabIndex = 0;
    this.btnMoveUpCriteria.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
    this.btnMoveUpCriteria.Location = new Point(5, 7);
    this.btnMoveUpCriteria.Name = "btnMoveUpCriteria";
    this.btnMoveUpCriteria.Size = new Size(75, 23);
    this.btnMoveUpCriteria.TabIndex = 3;
    this.btnMoveUpCriteria.Text = "Move Up";
    this.btnMoveUpCriteria.UseVisualStyleBackColor = true;
    this.btnMoveUpCriteria.Click += new EventHandler(this.btnMoveUpCriteria_Click);
    this.btnMoveDnCriteria.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left;
    this.btnMoveDnCriteria.Location = new Point(86, 7);
    this.btnMoveDnCriteria.Name = "btnMoveDnCriteria";
    this.btnMoveDnCriteria.Size = new Size(75, 23);
    this.btnMoveDnCriteria.TabIndex = 2;
    this.btnMoveDnCriteria.Text = "Move Down";
    this.btnMoveDnCriteria.UseVisualStyleBackColor = true;
    this.btnMoveDnCriteria.Click += new EventHandler(this.btnMoveDnCriteria_Click);
    this.btnDelCriteria.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Right;
    this.btnDelCriteria.Location = new Point(741, 7);
    this.btnDelCriteria.Name = "btnDelCriteria";
    this.btnDelCriteria.Size = new Size(75, 23);
    this.btnDelCriteria.TabIndex = 1;
    this.btnDelCriteria.Text = "Delete";
    this.btnDelCriteria.UseVisualStyleBackColor = true;
    this.btnDelCriteria.Click += new EventHandler(this.btnDelCriteria_Click);
    this.btnAddCriteria.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Right;
    this.btnAddCriteria.Location = new Point(660, 7);
    this.btnAddCriteria.Name = "btnAddCriteria";
    this.btnAddCriteria.Size = new Size(75, 23);
    this.btnAddCriteria.TabIndex = 0;
    this.btnAddCriteria.Text = "Add";
    this.btnAddCriteria.UseVisualStyleBackColor = true;
    this.btnAddCriteria.Click += new EventHandler(this.btnAddCriteria_Click);
    this.tabPage4.Controls.Add((Control) this.chkLargeExport);
    this.tabPage4.Controls.Add((Control) this.label20);
    this.tabPage4.Controls.Add((Control) this.pnlEditLayout);
    this.tabPage4.Controls.Add((Control) this.rbLandscape);
    this.tabPage4.Controls.Add((Control) this.rbPortrait);
    this.tabPage4.Controls.Add((Control) this.label16);
    this.tabPage4.Controls.Add((Control) this.txtMarginRight);
    this.tabPage4.Controls.Add((Control) this.txtMarginLeft);
    this.tabPage4.Controls.Add((Control) this.txtMarginBottom);
    this.tabPage4.Controls.Add((Control) this.label15);
    this.tabPage4.Controls.Add((Control) this.label14);
    this.tabPage4.Controls.Add((Control) this.label13);
    this.tabPage4.Controls.Add((Control) this.label12);
    this.tabPage4.Controls.Add((Control) this.txtMarginTop);
    this.tabPage4.Controls.Add((Control) this.label11);
    this.tabPage4.Controls.Add((Control) this.label9);
    this.tabPage4.Controls.Add((Control) this.txtTableNames);
    this.tabPage4.Controls.Add((Control) this.label17);
    this.tabPage4.Controls.Add((Control) this.txtSumFields);
    this.tabPage4.Controls.Add((Control) this.label8);
    this.tabPage4.Controls.Add((Control) this.txtColWidth);
    this.tabPage4.Controls.Add((Control) this.label7);
    this.tabPage4.Location = new Point(4, 22);
    this.tabPage4.Name = "tabPage4";
    this.tabPage4.Size = new Size(827, 322);
    this.tabPage4.TabIndex = 3;
    this.tabPage4.Text = "Misc";
    this.tabPage4.UseVisualStyleBackColor = true;
    this.chkLargeExport.AutoSize = true;
    this.chkLargeExport.Location = new Point(133, 92);
    this.chkLargeExport.Name = "chkLargeExport";
    this.chkLargeExport.Size = new Size(460, 17);
    this.chkLargeExport.TabIndex = 22;
    this.chkLargeExport.Tag = (object) "0";
    this.chkLargeExport.Text = "Check if large amount of data export expected for prevention of \"Out Of Memory\" exception.";
    this.chkLargeExport.UseVisualStyleBackColor = true;
    this.chkLargeExport.CheckedChanged += new EventHandler(this.chkLargeExport_CheckedChanged);
    this.label20.AutoSize = true;
    this.label20.Location = new Point(8, 94);
    this.label20.Name = "label20";
    this.label20.Size = new Size(67, 13);
    this.label20.TabIndex = 21;
    this.label20.Text = "Large Export";
    this.pnlEditLayout.Controls.Add((Control) this.chkAutoGen);
    this.pnlEditLayout.Controls.Add((Control) this.btnRemoveLayout);
    this.pnlEditLayout.Controls.Add((Control) this.btnEditLayout);
    this.pnlEditLayout.Location = new Point(133, 181);
    this.pnlEditLayout.Name = "pnlEditLayout";
    this.pnlEditLayout.Size = new Size(271, 73);
    this.pnlEditLayout.TabIndex = 20;
    this.pnlEditLayout.Visible = false;
    this.pnlEditLayout.VisibleChanged += new EventHandler(this.pnlEditLayout_VisibleChanged);
    this.chkAutoGen.AutoSize = true;
    this.chkAutoGen.Location = new Point(13, 6);
    this.chkAutoGen.Name = "chkAutoGen";
    this.chkAutoGen.Size = new Size(243, 17);
    this.chkAutoGen.TabIndex = 21;
    this.chkAutoGen.Text = "Automatically generate simple layout from data";
    this.chkAutoGen.UseVisualStyleBackColor = true;
    this.btnRemoveLayout.Enabled = false;
    this.btnRemoveLayout.Location = new Point(135, 28);
    this.btnRemoveLayout.Name = "btnRemoveLayout";
    this.btnRemoveLayout.Size = new Size(106, 25);
    this.btnRemoveLayout.TabIndex = 20;
    this.btnRemoveLayout.Text = "Remove Layout";
    this.btnRemoveLayout.UseVisualStyleBackColor = true;
    this.btnRemoveLayout.Click += new EventHandler(this.btnRemoveLayout_Click);
    this.btnEditLayout.Location = new Point(13, 28);
    this.btnEditLayout.Name = "btnEditLayout";
    this.btnEditLayout.Size = new Size(106, 25);
    this.btnEditLayout.TabIndex = 19;
    this.btnEditLayout.Text = "Edit Layout";
    this.btnEditLayout.UseVisualStyleBackColor = true;
    this.btnEditLayout.Click += new EventHandler(this.btnEditLayout_Click);
    this.rbLandscape.AutoSize = true;
    this.rbLandscape.Location = new Point(206, 146);
    this.rbLandscape.Name = "rbLandscape";
    this.rbLandscape.Size = new Size(78, 17);
    this.rbLandscape.TabIndex = 18;
    this.rbLandscape.Text = "Landscape";
    this.rbLandscape.UseVisualStyleBackColor = true;
    this.rbPortrait.AutoSize = true;
    this.rbPortrait.Checked = true;
    this.rbPortrait.Location = new Point(133, 146);
    this.rbPortrait.Name = "rbPortrait";
    this.rbPortrait.Size = new Size(58, 17);
    this.rbPortrait.TabIndex = 17;
    this.rbPortrait.TabStop = true;
    this.rbPortrait.Text = "Portrait";
    this.rbPortrait.UseVisualStyleBackColor = true;
    this.label16.AutoSize = true;
    this.label16.Location = new Point(8, 146);
    this.label16.Name = "label16";
    this.label16.Size = new Size(89, 13);
    this.label16.TabIndex = 16 /*0x10*/;
    this.label16.Text = "Paper Orientation";
    this.txtMarginRight.Location = new Point(400, 117);
    this.txtMarginRight.Name = "txtMarginRight";
    this.txtMarginRight.Size = new Size(38, 20);
    this.txtMarginRight.TabIndex = 15;
    this.txtMarginLeft.Location = new Point(321, 117);
    this.txtMarginLeft.Name = "txtMarginLeft";
    this.txtMarginLeft.Size = new Size(35, 20);
    this.txtMarginLeft.TabIndex = 14;
    this.txtMarginBottom.Location = new Point(249, 117);
    this.txtMarginBottom.Name = "txtMarginBottom";
    this.txtMarginBottom.Size = new Size(35, 20);
    this.txtMarginBottom.TabIndex = 13;
    this.label15.AutoSize = true;
    this.label15.Location = new Point(362, 120);
    this.label15.Name = "label15";
    this.label15.Size = new Size(32 /*0x20*/, 13);
    this.label15.TabIndex = 12;
    this.label15.Text = "Right";
    this.label14.AutoSize = true;
    this.label14.Location = new Point(290, 120);
    this.label14.Name = "label14";
    this.label14.Size = new Size(25, 13);
    this.label14.TabIndex = 11;
    this.label14.Text = "Left";
    this.label13.AutoSize = true;
    this.label13.Location = new Point(203, 120);
    this.label13.Name = "label13";
    this.label13.Size = new Size(40, 13);
    this.label13.TabIndex = 10;
    this.label13.Text = "Bottom";
    this.label12.AutoSize = true;
    this.label12.Location = new Point(130, 120);
    this.label12.Name = "label12";
    this.label12.Size = new Size(26, 13);
    this.label12.TabIndex = 9;
    this.label12.Text = "Top";
    this.txtMarginTop.Location = new Point(162, 117);
    this.txtMarginTop.Name = "txtMarginTop";
    this.txtMarginTop.Size = new Size(35, 20);
    this.txtMarginTop.TabIndex = 8;
    this.label11.AutoSize = true;
    this.label11.Location = new Point(8, 120);
    this.label11.Name = "label11";
    this.label11.Size = new Size(47, 13);
    this.label11.TabIndex = 7;
    this.label11.Text = "Margins:";
    this.label9.AutoSize = true;
    this.label9.Location = new Point(8, 299);
    this.label9.Name = "label9";
    this.label9.Size = new Size(189, 13);
    this.label9.TabIndex = 6;
    this.label9.Text = "*List of values delimited with semicolon";
    this.txtTableNames.Location = new Point(133, 65);
    this.txtTableNames.Name = "txtTableNames";
    this.txtTableNames.Size = new Size(673, 20);
    this.txtTableNames.TabIndex = 5;
    this.label17.AutoSize = true;
    this.label17.Location = new Point(8, 68);
    this.label17.Name = "label17";
    this.label17.Size = new Size(107, 13);
    this.label17.TabIndex = 4;
    this.label17.Text = "Table/Sheet Names*";
    this.txtSumFields.Location = new Point(133, 39);
    this.txtSumFields.Name = "txtSumFields";
    this.txtSumFields.Size = new Size(673, 20);
    this.txtSumFields.TabIndex = 5;
    this.label8.AutoSize = true;
    this.label8.Location = new Point(8, 42);
    this.label8.Name = "label8";
    this.label8.Size = new Size(84, 13);
    this.label8.TabIndex = 4;
    this.label8.Text = "Summary Fields*";
    this.txtColWidth.Location = new Point(133, 13);
    this.txtColWidth.Name = "txtColWidth";
    this.txtColWidth.Size = new Size(673, 20);
    this.txtColWidth.TabIndex = 3;
    this.label7.AutoSize = true;
    this.label7.Location = new Point(8, 16 /*0x10*/);
    this.label7.Name = "label7";
    this.label7.Size = new Size(96 /*0x60*/, 13);
    this.label7.TabIndex = 1;
    this.label7.Text = "Column widths (in)*";
    this.tabPage5.Controls.Add((Control) this.ucPermissions1);
    this.tabPage5.Location = new Point(4, 22);
    this.tabPage5.Name = "tabPage5";
    this.tabPage5.Size = new Size(827, 322);
    this.tabPage5.TabIndex = 4;
    this.tabPage5.Text = "Permissions";
    this.tabPage5.UseVisualStyleBackColor = true;
    this.ucPermissions1.Dock = DockStyle.Fill;
    this.ucPermissions1.Location = new Point(0, 0);
    this.ucPermissions1.Name = "ucPermissions1";
    this.ucPermissions1.Size = new Size(827, 322);
    this.ucPermissions1.TabIndex = 0;
    this.saveFileDialog1.DefaultExt = "*.imsr";
    this.saveFileDialog1.Filter = "IMS AdHoc Reports|*.imsr|All Files|*.*";
    this.openFileDialog1.DefaultExt = "*.imsr";
    this.openFileDialog1.FileName = "openFileDialog1";
    this.openFileDialog1.Filter = "IMS AdHoc Reports|*.imsr|All Files|*.*";
    this.toolStrip1.Items.AddRange(new ToolStripItem[3]
    {
      (ToolStripItem) this.toolStripButton1,
      (ToolStripItem) this.ddbParams,
      (ToolStripItem) this.ddbParamsSubTitle
    });
    this.toolStrip1.Location = new Point(0, 24);
    this.toolStrip1.Name = "toolStrip1";
    this.toolStrip1.Size = new Size(835, 25);
    this.toolStrip1.TabIndex = 3;
    this.toolStrip1.Text = "toolStrip1";
    this.toolStripButton1.DisplayStyle = ToolStripItemDisplayStyle.Text;
    this.toolStripButton1.Font = new Font("Arial", 11.25f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.toolStripButton1.ForeColor = System.Drawing.Color.Red;
    this.toolStripButton1.Image = (Image) componentResourceManager.GetObject("toolStripButton1.Image");
    this.toolStripButton1.ImageTransparentColor = System.Drawing.Color.Magenta;
    this.toolStripButton1.Name = "toolStripButton1";
    this.toolStripButton1.Size = new Size(23, 22);
    this.toolStripButton1.Text = "!";
    this.toolStripButton1.Click += new EventHandler(this.toolStripButton1_Click);
    this.ddbParams.DisplayStyle = ToolStripItemDisplayStyle.Text;
    this.ddbParams.Image = (Image) componentResourceManager.GetObject("ddbParams.Image");
    this.ddbParams.ImageTransparentColor = System.Drawing.Color.Magenta;
    this.ddbParams.Name = "ddbParams";
    this.ddbParams.Size = new Size(106, 22);
    this.ddbParams.Text = "Insert Parameter";
    this.ddbParams.Visible = false;
    this.ddbParams.DropDownItemClicked += new ToolStripItemClickedEventHandler(this.ddbParams_DropDownItemClicked);
    this.ddbParamsSubTitle.DisplayStyle = ToolStripItemDisplayStyle.Text;
    this.ddbParamsSubTitle.Image = (Image) componentResourceManager.GetObject("ddbParamsSubTitle.Image");
    this.ddbParamsSubTitle.ImageTransparentColor = System.Drawing.Color.Magenta;
    this.ddbParamsSubTitle.Name = "ddbParamsSubTitle";
    this.ddbParamsSubTitle.Size = new Size(106, 22);
    this.ddbParamsSubTitle.Text = "Insert Parameter";
    this.ddbParamsSubTitle.Visible = false;
    this.ddbParamsSubTitle.DropDownItemClicked += new ToolStripItemClickedEventHandler(this.ddbParamsSubTitle_DropDownItemClicked);
    this.panelBottom.Controls.Add((Control) this.btnSave);
    this.panelBottom.Dock = DockStyle.Bottom;
    this.panelBottom.Location = new Point(0, 428);
    this.panelBottom.Name = "panelBottom";
    this.panelBottom.Size = new Size(835, 37);
    this.panelBottom.TabIndex = 4;
    this.btnSave.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
    this.btnSave.Location = new Point(667, 6);
    this.btnSave.Name = "btnSave";
    this.btnSave.Size = new Size(156, 23);
    this.btnSave.TabIndex = 0;
    this.btnSave.Text = "Save Report To Database";
    this.btnSave.UseVisualStyleBackColor = true;
    this.btnSave.Click += new EventHandler(this.btnSave_Click);
    this.toolTip1.ToolTipTitle = "Control disabled due to report layout presence.";
    this.errError.ContainerControl = (ContainerControl) this;
    this.errRecommend.ContainerControl = (ContainerControl) this;
    this.errRecommend.Icon = (Icon) componentResourceManager.GetObject("errRecommend.Icon");
    this.AutoScaleDimensions = new SizeF(6f, 13f);
    this.AutoScaleMode = AutoScaleMode.Font;
    this.ClientSize = new Size(835, 465);
    this.Controls.Add((Control) this.tabControl1);
    this.Controls.Add((Control) this.panel1);
    this.Controls.Add((Control) this.toolStrip1);
    this.Controls.Add((Control) this.menuStrip1);
    this.Controls.Add((Control) this.panelBottom);
    this.MainMenuStrip = this.menuStrip1;
    this.Name = nameof (frmAdHocReportManager);
    this.Text = "AdHoc Report Manager";
    this.FormClosing += new FormClosingEventHandler(this.frmAdHocReports_FormClosing);
    this.Load += new EventHandler(this.frmAdHocReportManager_Load);
    this.menuStrip1.ResumeLayout(false);
    this.menuStrip1.PerformLayout();
    this.panel1.ResumeLayout(false);
    this.panel1.PerformLayout();
    this.tabControl1.ResumeLayout(false);
    this.tabPage1.ResumeLayout(false);
    this.tabPage1.PerformLayout();
    this.tabPage3.ResumeLayout(false);
    this.tabPage3.PerformLayout();
    this.tabPage2.ResumeLayout(false);
    ((ISupportInitialize) this.gvCriteria).EndInit();
    ((ISupportInitialize) this.dataGridView1).EndInit();
    this.panel3.ResumeLayout(false);
    this.tabPage4.ResumeLayout(false);
    this.tabPage4.PerformLayout();
    this.pnlEditLayout.ResumeLayout(false);
    this.pnlEditLayout.PerformLayout();
    this.tabPage5.ResumeLayout(false);
    this.toolStrip1.ResumeLayout(false);
    this.toolStrip1.PerformLayout();
    this.panelBottom.ResumeLayout(false);
    ((ISupportInitialize) this.errError).EndInit();
    ((ISupportInitialize) this.errRecommend).EndInit();
    this.ResumeLayout(false);
    this.PerformLayout();
  }
}
